### ISSUE TITLE
Incorrect selection from the list regions with identical names / Выбор регионов с одинаковыми именами 

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#105]
EN: When choosing a region from the list (including in the regional filter), the regions with identical names are incorrectly selected. The region is always selected (from several of the same name), which has a lower identifier. #106

As an example, with the selection of any from the multiple "Kamensky District", will be selected only one district of Altai Kray.

----

RU: Когда выбираешь из списка регион с неуникальным названием, то выбирается всегда регион с наименьшим номером. Нужно, чтобы ключом для выбора был уникальный номер, а не название.

![image](https://user-images.githubusercontent.com/60163100/72857798-c50bc080-3ccf-11ea-8bd7-954c5c77be29.png)

**Comment by paul-k-pastvu** [comment]
Также есть необходимость как-то различать уже выбранные в шапке фильтра, к примеру.
Т.е. когда я всё же выбрал 3 разных Ленинских района - я должен понимать, какой из них чей.
Поэтому может быть такой путь обхода:
при вводе нового региона проверять, нет ли дублирования названия. И если есть - требовать ввести доп. краткий "суффикс" (новое свойство). Т.е. уникальным ключом будет не название региона, а название + суффикс. Таким образом, имея:
1) Выборгский район Петербурга > вводим суффикс "СПб"/"SPb"
2) Выборгский район Лен. области > вводим суффикс "ЛО"/"LO"
При отображении в дереве будет:

-Ленинградская область
—- Выборгский район (ЛО)
- Санкт-Петербург
—- Выборгский район (СПб)

Т.е. снова имеем сквозной список уникальных названий регионов и ошибку эту обходим
Далее,
1) в фильтре галерей отображать эти комбинированные названия
2) в адресной строке на страницах изображений - оставить всё как есть, т.к. родительский регион там и так отображается в явном виде
3) в подписях к миниатюрам в галереях и т.п. - тоже "композитное" название
4) в поисковой подсказке пр выборе региона - также отображать новые композитные названия

**Comment by anvaruk** [comment]
in case more examples needed 

trying to select:  Belarus - Brest Oblast - Brest
![image](https://user-images.githubusercontent.com/2795267/83433954-84684480-a431-11ea-9baf-b841af700c31.png)

reverts to a region in France with the same name
![image](https://user-images.githubusercontent.com/2795267/83433986-91853380-a431-11ea-9007-2223d1563547.png)

**Comment by kabalin** [comment]
Можно ли считать этот тикет решенным, если нет, то чего не хватает?

![image](https://user-images.githubusercontent.com/329780/211436023-8b5a2a05-9472-474d-aaf6-36f8a060914f.png)
