### ISSUE TITLE
Inability to distinguish Antarctica as a separate region

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#120]
Currently is an inability to distinguish Antarctica as a separate region (feature of the site’s cartographic platform). All photos from there relate to "International waters".

Problem: missing a regional item for links from Antarctica photos without coordinates.

**Comment by kabalin** [comment]
@paul-k-pastvu check if http://download.geofabrik.de/antarctica.html and https://osmdata.openstreetmap.de/data/icesheet.html of any help to address this issue.

**Comment by kabalin** [comment]
> @paul-k-pastvu check if http://download.geofabrik.de/antarctica.html and https://osmdata.openstreetmap.de/data/icesheet.html of any help to address this issue.

I spent some time looking at this, this is not what we need, this is a coastline and icesheet, nothing to do with administrative division we use. But what if we use existing OSM relations instead that represent Antarctic territorial claims:

Antarctica (Antarctic Treaty area): https://www.openstreetmap.org/relation/2186646

Subareas (territorial claims listed in brackets, see https://www.wikidata.org/wiki/Q21590062):
- Adélie Land (France): https://www.openstreetmap.org/relation/3810329
- Australian Antarctic Territory (Australia): https://www.openstreetmap.org/relation/3394111
- British Antarctic Territory (UK): https://www.openstreetmap.org/relation/3394112
- Chilean Antarctic Territory (Chile): https://www.openstreetmap.org/relation/3394115
- Ross Dependency (New Zeland): https://www.openstreetmap.org/relation/3394113
- Queen Maud Land (Norway): https://www.openstreetmap.org/relation/3245621
- Peter I Island (Norway): https://www.openstreetmap.org/relation/2955118
- Argentine Antarctica (Argentina): https://www.openstreetmap.org/relation/3394110
   - South Shetland Islands (Argentina): https://www.openstreetmap.org/relation/938065
      - King George Island (largest and inhabited): https://www.openstreetmap.org/relation/1889211
      - It is possible to add other islands (see members of South Shetland Islands relations or https://en.wikipedia.org/wiki/South_Shetland_Islands#Islands), but probably not needed unless we have photos on them. 
    - South Orkney Islands (Argentina and Britain): https://www.openstreetmap.org/relation/938061

**Comment by paul-k-pastvu** [comment]
Павел Климашкин писал когда-то, что там какая-то проблема, связанная с используемой проекцией.
Так-то чего бы проще - и делить её совсем не нужно, пусть будет одним пятном.

**Comment by kabalin** [comment]
Проблема с проекцией EPSG:3857 которую мы используем заключается в том, что мы не можем установить точки южнее широты 85.06°S, т.е. мы на карте видим только "окантовку" Антарктиды ([подробнее](https://blog.jochentopf.com/2013-02-04-antarctica-in-openstreetmap.html)). Но OSM использует ту же самую проекцию, поэтому все relation территорий должны работать, если их описать как любой другой регион.

Я для примера добавил локально https://www.openstreetmap.org/relation/2186646 и https://www.openstreetmap.org/relation/188921, все корректно сохранилось.

![image](https://user-images.githubusercontent.com/329780/193933345-5044f8ff-75f9-468b-994a-d7df7a3b7413.png)

**Comment by kabalin** [comment]
> Так-то чего бы проще - и делить её совсем не нужно, пусть будет одним пятном.

Одним пятном конечно проще, но снимков в этой части много не загружают, поэтому маловероятно что кто-то попросит выделить какую-то отдельную территорию внутри Антарктиды. Может быть один раз ее разделить хотя бы на те крупные участки, что я выше выделил выше и больше к этому вопросу не возвращаться (я могу в принципе и сам их добавить, если ты одобришь). Будет повод после этого изменения сделать снапшот регионов для тестовой базы, не обновляли давно.

**Comment by paul-k-pastvu** [comment]
Я за ;)

ср, 5 окт. 2022 г., 00:29 Ruslan Kabalin ***@***.***>:

**Comment by kabalin** [comment]
Добавил, но не все что планировал:
![image](https://user-images.githubusercontent.com/329780/194310555-c59e3b3d-c0f0-489e-83a0-59daefa857ac.png)

Дело в том, что территории Британии, Чили и Аргентины частично наложены друг на друга (спорные), поэтому я их не добавил. Отдельно группы островов (Южные Шетландские и Оркнейские) тоже выделять не стал. Не знаю, может австралийскую территорию теперь тоже убрать, просто получается некоторое несоответсвие что некоторые территории есть, а некоторых со схожим статусом нет. @paul-k-pastvu что посоветуешь (или можешь сам исправить как лучше)?

**Comment by paul-k-pastvu** [comment]
Да не проблема. Нет и нет. Если кому-то будут очень надо, - что-то придумаем.
