### ISSUE TITLE
User profile option for disabling email notification / Опция для полного отключения уведомлений по эл. почте

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#122]
User profile settings, "Subscription and notifications" section.
Add the new option for disabling email notification (by his/her actual subscriptions).

Current options:
![image](https://user-images.githubusercontent.com/60163100/73748524-ae9f4380-476a-11ea-8ecb-7d15f87acc4b.png)

**Dependencies**: If option «Disable email notification» will be set to ON, that option"Minimum interval between sendings" should be disabled.

**Warning:** This will not be affected to function " Subscribe automatically on the comment submission".

**Comment by paul-k-pastvu** [comment]
Вот эта задача вроде бы небольшая и сравнительно частотная. 
Сейчас, если участник не хочет получать почту от сайта, то выходит, что мы насильно рассылаем спам, так как отписаться невозможно - или нужно пройти по всем своим подпискам и с каждого фото снять галочку, что довольно трудоемко.

**Comment by kabalin** [comment]
Еще вопрос к @paul-k-pastvu, если уведомления какое-то время отключены, а затем пользователь включает их, должен ли он получить по почте уведомления о всех изменениях которые он "пропустил"? Если да, будет ли схожая логика для ситуации когда пользователь не получал уведомления из за того, что ему запрещено было логиниться?

**Comment by kabalin** [comment]
Конечное решение - сделать отдельный переключатель как было предложено изначально, это связано с реализацией механизма уведомлений. Частота рассылки учитывается при постановке в очередь отправки (коллекция `UserNoty`), в то время как опция запрета уведомления влияет на флаг необходимости уведомления (поле `subscribe_noty` в`UserObjectRel`), т.е. корректнее ее учитывать отдельно.
![image](https://user-images.githubusercontent.com/329780/176639813-dc2d2156-0aa4-4685-83a8-7a2bd0debfa2.png)

Так же добавлен механизм запрета отправки уведомлений пользователям, которым запрещено логиниться. Это не связано с переключателем запрета уведомлений, ограничение учитывается при постановке флага необходимости уведомления - если пользователю заперщено логиниться - уведомления приходить не будут.

**Comment by paul-k-pastvu** [comment]
Мне - OK

**Comment by kabalin** [comment]
English version (pushed after resolving merge conflict in template, if anything needs changing let me know):
![image](https://user-images.githubusercontent.com/329780/177034874-f6c05e97-71f8-447a-af57-c2a83760cdaa.png)
