### ISSUE TITLE
Invalid HTML code in the "source" field (and also in the description)

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#127]
An error appears in a certain sequence of actions: Invalid HTML code in the "source" field (and also in the description).

1. See image https://pastvu.com/p/591487 in the edit mode:
![image](https://user-images.githubusercontent.com/60163100/73770294-37c77200-478d-11ea-8ef9-159234b1db1c.png)

2. When switching to this image by clicking to ann thumbnail in the top of right map, 
![image](https://user-images.githubusercontent.com/60163100/73771107-b53fb200-478e-11ea-8f59-503cb0b814b5.png)
we have seen next situation in the source field:
![image](https://user-images.githubusercontent.com/60163100/73771144-d2748080-478e-11ea-8ea8-ae1cc5ed95ac.png)

Conditions of appears (for reproducing the situation): 
1) Photo in the "New" status
2) URL was added in the **first** editing of file description. After second saving this bug not a reproducing

**Comment by aeifn** [comment]
Место, где эта строка генерируется:
https://github.com/PastVu/pastvu/blob/cf30f6215f9d7ddcd0833362e0706a404ae14208/commons/Utils.js#L279
