### ISSUE TITLE
Check region by point - replace Google calling to OSM/Yandex request

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#131]
Popup menu in the https://pastvu.com/admin/region/check :

![image](https://user-images.githubusercontent.com/60163100/73966259-b86da600-4926-11ea-8815-2724717b370c.png)

Some errors from Google.

Maybe remove this or replace it to OSM / Yandex request instead?

**Comment by kabalin** [comment]
Google geocoding requires API key these days: https://maps.googleapis.com/maps/api/geocode/json?latlng=40.714224,-73.961452

**Comment by mkgrgis** [comment]
There is OSM Overpass mechanism
https://www.openstreetmap.org/query?lat=55.60093&lon=37.67484&xhr=1
![изображение](https://user-images.githubusercontent.com/41448637/98136531-176e4480-1ed2-11eb-9600-c5825f8bc776.png)
or there is OSM Nominatim for ex. https://nominatim.openstreetmap.org/ui/reverse.html?format=html&lat=59.6942440819683&lon=30.443973541259766&zoom=18

**Comment by paul-k-pastvu** [comment]
Я бы предложил и саму карту, и эту функцию заменить на OSM, недолго думая.
Вообще поставиь в админский интерфейс ту же карту с тем же селектором, что и основная. Мне так было бы сильно удобнее.

**Comment by kabalin** [comment]
> Я бы предложил и саму карту, и эту функцию заменить на OSM, недолго думая.

Карта там и так OSM, патч для использования Nominatim  здесь #228 

> Вообще поставиь в админский интерфейс ту же карту с тем же селектором, что и основная. Мне так было бы сильно удобнее.

Ну это в отдельный тикет лучше вынести.

**Comment by paul-k-pastvu** [comment]
> Ну это в отдельный тикет лучше вынести.

Ну это так, к слову. 10-й приоритет.

**Comment by mkgrgis** [comment]
Реализованный механизм расчищает дорогу к https://github.com/PastVu/pastvu/issues/142. Там становится возможна автопривязка большинства регионов.

**Comment by paul-k-pastvu** [comment]
> Реализованный механизм расчищает дорогу к #142. Там становится возможна автопривязка большинства регионов.

Да, это кстати. Но тут вот какое дело: зачача #142 сформулирована очень рамочно и очень неконкретно. И, по сути, пока чтт нужна ровно одному человкеку - тому админу, который занимается регионами, то есть пока что в основном мне. Так что я понизил ей приоритет пока что. Остальное напишу там.

**Comment by paul-k-pastvu** [comment]
The best:

![image](https://user-images.githubusercontent.com/60163100/98453536-46ebae00-216b-11eb-9967-c9b82aa2ceac.png)

**Comment by paul-k-pastvu** [comment]
Ещё вопрос апо этой задаче - а нельзя ли делать ссылками уровни из Nominatim? Чтобы они вели на соответствующие объекты nominatim.openstreetmap.org ?

**Comment by mkgrgis** [comment]
Там скорре можно приеделать ссылки на отношения ОСМ, которые можно качать в geoJSON через https://github.com/tyrasd/osmtogeojson и отрисовывать на этой же карте или просматривать вживую на ОСМ.

**Comment by kabalin** [comment]
> Ещё вопрос по этой задаче - а нельзя ли делать ссылками уровни из Nominatim? Чтобы они вели на соответствующие объекты nominatim.openstreetmap.org ?

#242

**Comment by paul-k-pastvu** [comment]
Багрепорт от @klimashkin - 
![image](https://user-images.githubusercontent.com/60163100/98471342-9ded9380-21fc-11eb-84da-f79ff79afba1.png)

**Comment by kabalin** [comment]
Хм, может быть локальный кэш? У меня работает.

**Comment by paul-k-pastvu** [comment]
> Хм, может быть локальный кэш? У меня работает.

Очистка кеша не помогла. Я там выше обновил багрепорт - я вижу две связанные проблемы.

**Comment by paul-k-pastvu** [comment]
> Там скорре можно приеделать ссылки на отношения ОСМ, которые можно качать в geoJSON через https://github.com/tyrasd/osmtogeojson и отрисовывать на этой же карте или просматривать вживую на ОСМ. 

Отрисовывать - это приятно, но роскошь. Кроме того, напоминаю, что там бардак, и это могут быть вообще не отношения, а хоть Node, хоть Way, причем в любом месте иерархии.

> Кстати, к координатам сверху лучше, для избежания путаницы, приписать φ= для широты и λ= для долготы, т.к. указывают в разном порядке в разных странах. А так будет международная геодезическая нотация, которую не нужно переводить.

Не возражаю.

**Comment by paul-k-pastvu** [comment]
> > Названия регионов Nominatim отображаются не на языке интерфейса сайта, а на языке интерфейса пользовательского окружения (браузера или ОС)
> Это я не менял, нужно чтобы по-русски всегда?

Если включен русский интерфейс сайта - запрашивать русские (если нету - то что он там возвращает в в виде дефолтных)

Если включен английский интерфнес сайта - запрашивать английские (если нету в явном виде - дефолтные)

**Comment by kabalin** [comment]
> Если включен русский интерфейс сайта - запрашивать русские (если нету - то что он там возвращает в в виде дефолтных)
> 
> Если включен английский интерфнес сайта - запрашивать английские (если нету в явном виде - дефолтные)

Добавил язык в запрос. Пробуйте еще раз, если опять не работает я уберу шаблоны для формирования ссылки (у меня по прежнему упорно работает в Хроме).

![Screenshot](https://user-images.githubusercontent.com/329780/98472083-7e4c7000-21e8-11eb-9e97-ba62e38b19aa.png)

**Comment by kabalin** [comment]
Могу сделать ссылку не на последнюю запись, а на все записи (но ссылка будет вести на одну и ту-же страницу) или вообще вынести ее отдельной строкой ниже последнего элемента.

**Comment by kabalin** [comment]
> * по п.1. - может, это давно так было, просто никто туда не заглядывал.

Да, только русский вариант был. Добавил коммит в #242 чтобы учитывался язык.

**Comment by mkgrgis** [comment]
Упустили мелочь https://github.com/PastVu/pastvu/issues/131#issuecomment-723535463

**Comment by paul-k-pastvu** [comment]
Язык победили, но ссылка на OSM указывает куда-то не туда:

![image](https://user-images.githubusercontent.com/60163100/99197228-25f60f00-27a2-11eb-947b-19fbaac67320.png)

Сейчас: https://nominatim.openstreetmap.org/ui/details.html?place_id=115595528

Должно быть: https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=173763

**Comment by kabalin** [comment]
Добавил, но кажется не совсем то что вы хотели. Там в ответе API нет информации по всей цепочке, только данные по точке (см https://nominatim.org/release-docs/develop/api/Output/#json). Для ссылки я сначала использовал `place_id` (как сейчас работает), но можно ссылку сделать как у вас в примере с `osm_id` (см патч #269), а вот прямо чтобы район показывал так нельзя (я не нашел), но вы там можете в открывшемся окне нажать на "детали" в последней колонке напротив интересующего вас элемента и попасть куда надо.

**Comment by kabalin** [comment]
Вроде бы все сделано по этой задаче, закрываю.
