### ISSUE TITLE
default map is not loading on zoom 18 / Настройка максимального уровня приближения независимо для каждой карты

### ISSUE THREAD

**Issue by anvaruk** [PastVu/pastvu#139]
when a new visitor opens a page in most cases map does not load
default settings - OSM Kosmosnimki zoom 18 does not work

change provider or zoom to 17

![image](https://user-images.githubusercontent.com/2795267/74028791-1d66e180-49a3-11ea-9d35-c37f12dc6e41.png)

**Comment by paul-k-pastvu** [comment]
Maybe add settings for display map variants and their default zoom into administrative dashboard?
This may be variable from time to time...

**Comment by aeifn** [comment]
Исправлено коммитом: https://github.com/PastVu/pastvu/commit/52af0654b218bff6b8ad288683c617c84f206f1d
