### ISSUE TITLE
HTML markup in the image tooltips (list of comments)  / убрать вылезающий HTML код во всплывающей подсказке

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#145]
There is seen HTML markup in the image tooltips (list of comments):

![image](https://user-images.githubusercontent.com/60163100/74173025-625c7380-4c42-11ea-8513-7ab7aaae30e4.png)

**Comment by aeifn** [comment]
Что-то не могу воспроизвести, можно ссылку, где это появляется?

**Comment by paul-k-pastvu** [comment]
> Что-то не могу воспроизвести, можно ссылку, где это появляется?

В списке комментариев пользователя. Наведи мышку на превью изображения:

![image](https://user-images.githubusercontent.com/60163100/97065082-a2d30600-15b3-11eb-817b-b49d720dac47.png)
