### ISSUE TITLE
Improve highlighting of new unread comments

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#158]
Users ask to make customizable color for highlighting of new unread comments:

![image](https://user-images.githubusercontent.com/60163100/75202836-94f78780-577d-11ea-9509-2437e4060a00.png)

Proposal: add in the user profile new option for set color for highlighting of new unread comments.

Realization: 

1. input field for set of color code (with switch for RGB and HEX format)
2. live preview field
3. (optional) selection by picking to RGB-palette or selection from web-palette; see https://tools.seo-zona.ru/color.html (as example); may be use one from free components to this.

**Comment by aeifn** [comment]
Можно просто сделать цвет поярче.

**Comment by mkgrgis** [comment]
Или обводить яркой рамкой?

**Comment by paul-k-pastvu** [comment]
> Или обводить яркой рамкой? Или приделать яркую полосу по левой границе?

Слева и так есть полоса, можно сделать её поярче и потолще

**Comment by paul-k-pastvu** [comment]
> Можно просто сделать цвет поярче.

Сейчас для класса .c.isnew стоит `background-color: rgba(174,255,184,0.1);`
Это вот так:

![image](https://user-images.githubusercontent.com/60163100/99196117-4f5f6c80-279b-11eb-8a2b-b7909aa43f50.png)

Если поменять на `rgba(174,255,184,0.3);` (то есть просто уменьшить прозрачность), то будет так:
![image](https://user-images.githubusercontent.com/60163100/99196140-71f18580-279b-11eb-8e6a-99209fbab351.png)

Если на `rgba(174,255,184,0.**5**);`
![image](https://user-images.githubusercontent.com/60163100/99196162-9e0d0680-279b-11eb-8c7a-ed577c9eb09f.png)

**Comment by kabalin** [comment]
> Я бы для начала поставил 0.3 и посмотрел на реакцию

0.3 и полоску слева сделать 2px толщиной:

![image](https://user-images.githubusercontent.com/329780/194062395-4b79dfde-a4e5-4286-b7a4-fbc86bdf7b51.png)

Тоже самое в истории:

![image](https://user-images.githubusercontent.com/329780/194063414-a565395e-d5f3-4def-99af-d794b44858de.png)

Подойдет?

**Comment by paul-k-pastvu** [comment]
да, согласен
