### ISSUE TITLE
"Share this photo" dialog upgrade / Обновить диалог "Поделиться этим фото"

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#162]
Needs to upgrade "Share this photo" dialog:
![image](https://user-images.githubusercontent.com/60163100/75394755-e6c91a80-5901-11ea-8989-0a537c5dbe3d.png)

1. Remove "G+" (closed) (**bug**)
2. (-) Add Instagram integration
3. Change wording in the caption: "Share this photo" -> "Share this image" (**bug**)
4. Add "copy link" clickable icon
5. Add "Share via Email" option
6. Add QR-code
7. Add HTML code for site/blog 

See Yandex sharing options:
![image](https://user-images.githubusercontent.com/60163100/75395035-90a8a700-5902-11ea-83f1-13955a498bfe.png)

**Comment by aeifn** [comment]
Seems that instagram sharing is not possible from desktop.

**Comment by paul-k-pastvu** [comment]
> Seems that instagram sharing is not possible from desktop.

Then we don't need it yet. You can add Pinterest instead - https://sharethis.com/social-media-buttons/pinterest-pin-share-button/ - ?

**Comment by aeifn** [comment]
Выполнено частично. Можно отредактировать и переоткрыть или оставшееся раздробить на отдельные задачи.

**Comment by paul-k-pastvu** [comment]
> Выполнено частично. Можно отредактировать и переоткрыть или оставшееся раздробить на отдельные задачи (так удобнее их линковать с пулреквестами).

Хорошо. Я не хотел плодить совсем мелкие задачи, ну джа ладно.
