### ISSUE TITLE
Improving the ways for indicate the direction of the image / Улучшение способов указания направления

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#170]
EN: We need to improve the way we indicate the direction of the image: 
1. increase the number of available directions (at least to 16, better — more) 
2. make it graphic so that we can not only select directions from the list but be able to move the arrow with the mouse

RU: Нам нужно улучшить способ указания направления снимка:
1. увеличить число доступных направлений (как минимум до 16, лучше - больше)
2. сделать его графическим, чтобы не только выбирать направления из списка, но иметь возможность двигать стрелку мышкой

----
See example (from transphoto.ru):
![image](https://user-images.githubusercontent.com/60163100/76175824-66d36800-61bf-11ea-9ca8-48115b6e2140.png)

----
Related with #200

**Comment by kabalin** [comment]
Обсуждение реализации в https://github.com/PastVu/pastvu/pull/201#issuecomment-720188219 и далее.

**Comment by mkgrgis** [comment]
Создан макет непрерывного выбора угла с большой точностью и наглядной демонстрации направления. Предлагаю закрыть эту заявку как примитивную относительно макета логики выбора направления из https://github.com/PastVu/pastvu/pull/201.
