### ISSUE TITLE
Does API service work?

### ISSUE THREAD

**Issue by pensnarik** [PastVu/pastvu#174]
From the source code I see that is possible to make API requests but I couldn't find any documentation and working API URL for the live service. I want to create a bot that will notify user about new photos in a given area and I looks like it's possible to do by using `giveNearestPhotos` API method. Could you please refer me to the documentation? Thanks.

**Comment by anvaruk** [comment]
API is operational but current server infrastructure cannot support public access at the moment
some discussions on telegram - pastvu_dev

**Comment by aeifn** [comment]
Сейчас вот работает https://pastvu.com/api2?method=photo.giveForPage&params={"cid":5}

**Comment by aeifn** [comment]
Should we run separate application for api?
If so, how to start api instance: by
`node ./bin/run.js --srcipt ./api.js` (does not work out of the box)
or by
`node ./bin/run.js --script ./app.js`, and then proxying /api2 uri?

**Comment by mkgrgis** [comment]
I think proxying /api2 uri is more useful. For the simplest queries IMHO addresses from https://github.com/PastVu/pastvu/issues/172 will be more clear. For example JSON from https://pastvu.com/api2?method=photo.giveForPage&params={%22cid%22:871154} contains to much data.
Is there any way to filter, for example, only `.photo` or `.photo.geo` attributes?

**Comment by aeifn** [comment]
The api is now started as separate instance at https://pastvu.com/api2, and ready for production.

The next important step is to provide some reference, tutorials and examples on api.

**Comment by aeifn** [comment]
The good place to collect examples is https://github.com/PastVu/pastvu/wiki/API

**Comment by mkgrgis** [comment]
Feature request for fast calls have been actualised https://github.com/PastVu/pastvu/issues/172.

**Comment by aeifn** [comment]
Running another full app replica wasn`t a good idea, as it duplicates emails. Reverted to previous state.

**Comment by mkgrgis** [comment]
What about Exif and GeoJSON API for images on area like [L.Panoramio](https://github.com/shurshur/Leaflet.Panoramio/blob/master/Panoramio.js) or [L.Flickr](https://github.com/shurshur/Leaflet.Flickr/blob/master/Flickr.js) ? Where can I encapsulate current image data in standard JSON objects? Can You, @aeifn patch for processing an API parameter like `outFormat='geoJSON'` and make void function for processing image data to GeoJSON and EXIF, I'll code and complete PR?

**Comment by aeifn** [comment]
> From the source code I see that is possible to make API requests but I couldn't find any documentation and working API URL for the live service. I want to create a bot that will notify user about new photos in a given area and I looks like it's possible to do by using `giveNearestPhotos` API method. Could you please refer me to the documentation? Thanks.

To sum up, the API works: https://pastvu.com/api2.

Documentation is available here: https://github.com/PastVu/pastvu/wiki/API
