### ISSUE TITLE
About page small update / Обновление информации "О проекте"

### ISSUE THREAD

**Issue by anvaruk** [PastVu/pastvu#180]
https://pastvu.com/about is out of date
ideally should include part editable from /admin 
as well as listing all admins and moderators

**Comment by aeifn** [comment]
Now we can just edit static page https://github.com/PastVu/pastvu/blob/cf30f6215f9d7ddcd0833362e0706a404ae14208/views/module/diff/about.pug

**Comment by paul-k-pastvu** [comment]
> Now we can just edit static page https://github.com/PastVu/pastvu/blob/cf30f6215f9d7ddcd0833362e0706a404ae14208/views/module/diff/about.pug

Hm, but where is the English version?

**Comment by paul-k-pastvu** [comment]
Вообще, мне так не нравится (и непонятно, как это редактировать).

Меня бы устроил простенький редактор статических страниц (вот хоть тот же плагин для редактирования новостей), только чтобы были доступны для выбора стили и классы оформления из нашего CSS

И, соответственно, возможность создавать статические страницы (Help, FAQ, References и т.п.) и выводить их в интерфейс как-то более "юзер-френдли".

**Comment by aeifn** [comment]
> Hm, but where is the English version?

В ветке 'en': https://github.com/PastVu/pastvu/blob/en/views/module/diff/about.pug

**Comment by paul-k-pastvu** [comment]
В общем, я вижу код, и даже понимаю, как его можно поменять - но где посмотреть, как это будет выглядеть?

----
Нам нужен отдельный модуль для статических страниц, который позволит как-то их конструировать, а не программировать.

Сейчас есть две таких страницы:

1. About
2. Rules

Предлагаю вывести вывести обе страницы в административный режим (сделать там раздел Pages), прикрутив к ним для начала тот же плагин, что и в редакторе новостей. Единственно, что нужно как-то уметь там  форматировать с использованием стилей сайта.

Там же можно сделать функцию добавления новых страниц. 

У всех статических страниц 

- должна быть опция "Show in help section" - если задана, страница отображается в разделе справки; а также порядковый номер отображения в списке;
- должна быть настройка прав доступа по уровням (если не задана, то доступна всем, можно сделать доступ только модераторам и администраторам или только админам).

В хидере сайта должна появиться новая ссылка "Help":
![image](https://user-images.githubusercontent.com/60163100/99469578-18808680-2954-11eb-9a45-779e22f62b8b.png)

На ней должен отображаться список ссылок на статические страницы, для которых установлен признак "Show in help section" (с учетом прав доступа).

**Comment by aeifn** [comment]
> В общем, я вижу код, и даже понимаю, как его можно поменять - но где посмотреть, как это будет выглядеть?

Самый простой способ — запустить сайт у себя локально в докере: https://github.com/pastvu/pastvu#run-with-docker

**Comment by paul-k-pastvu** [comment]
> > В общем, я вижу код, и даже понимаю, как его можно поменять - но где посмотреть, как это будет выглядеть?
> Самый простой способ — запустить сайт у себя локально в докере: https://github.com/pastvu/pastvu#run-with-docker

...предварительно поставив и подняв у себя всё, что там написано выше, а также собственно локальную версию репозитория Git? Нет, спасибо. Я веду к тому, что статические страницы нужно редактировать, а не программировать.

**Comment by paul-k-pastvu** [comment]
Нам нужен отдельный модуль для статических страниц, который позволит как-то их конструировать, а не программировать.

Сейчас есть две таких страницы:

1. About
2. Rules

Предлагаю вывести вывести обе страницы в административный режим (сделать там раздел Pages), прикрутив к ним для начала тот же плагин, что и в редакторе новостей. Единственно, что нужно как-то уметь там  форматировать HTML с использованием стилей сайта.

Там же можно сделать функцию добавления новых страниц. 

У всех статических страниц 

- должна быть опция "Show in help section" - если задана, страница отображается в разделе справки; а также порядковый номер отображения в списке;
- должна быть настройка прав доступа по уровням (если не задана, то доступна всем, можно сделать доступ только модераторам и администраторам или только админам).

В хидере сайта должна появиться новая ссылка "Help":
![image](https://user-images.githubusercontent.com/60163100/99469578-18808680-2954-11eb-9a45-779e22f62b8b.png)

На ней должен отображаться список ссылок на статические страницы, для которых установлен признак "Show in help section" (с учетом прав доступа).

**Comment by aeifn** [comment]
> ...предварительно поставив и подняв у себя всё, что там написано выше

Справедливости ради, все что описано в README выше, поднимать совсем не обязательно, достаточно выполнить команды, указанные в секции `run with docker` :)

**Comment by paul-k-pastvu** [comment]
> > ...предварительно поставив и подняв у себя всё, что там написано выше
> 
> Справедливости ради, все, что описано в README выше, поднимать совсем не обязательно, достаточно выполнить команды, указанные в секции `run with docker` :)
> upd., offtop: Переместил инструкцию по запуску в докере наверх в README, дабы не отпугивать потенциальных контрибьюторов сложностью ручных настроек.

Я из ридми не понял, как это будет связано с кодом на Гитхабе. Надеюсь, программистам это понятно.
Но я выше написал вообще о другом аспекте. Нам НУЖНЫ редактируемые (а не программируемые) статические странички, в т.ч. текст правил.

**Comment by paul-k-pastvu** [comment]
Давайте вернем эту задачу к исходному названию, что-то типа "About page small update",   и я просто перечислю желаемые изменения. А для большой задачи заведу новый тикет.

**Comment by paul-k-pastvu** [comment]
#288

**Comment by paul-k-pastvu** [comment]
Итак, пожелание раз, из 2-х пунктов (голосуйте смайликами): отобразить актуальный состав команды.

1. Добавить админа _p_k (Павел К.) с текстом примерно таким (уточняйте):
    - RU: `Формализация пожеланий и отслеживание исправлений, анализ пользовательского опыта, отношения с сообществом`
    - EN: `Formalization feature requests and tracking of bug fixing, analysis of user experience, community relations`
Фоновая иконка для "карусели":
![image](https://user-images.githubusercontent.com/60163100/99590575-90a38680-29fe-11eb-9999-a15979aa98f0.png)

2. Админа Alexey Duck (Duche) перенести в отдельный раздел "Благодарности" / "Acknowledgments", поменяв его описание
    - RU: `Продюсер проекта в 2009 – 2018 годах`
    - EN: `Producer of the project from 2009 to 2018`

**Comment by paul-k-pastvu** [comment]
Пожелание два: под "Благодаорностями" поместить раздел "История проекта" / "Project History"  с текстом:

   - EN: 
This project was started in 2009 by [Ilya Varlamov](https://varlamov.ru/).
Initially, this was a local project and dedicated to historical photos of Moscow, the capital city of Russia. The first domain name was oldmos.ru. This was originally conceived as a crowdsourcing project with a broad number of contributors.
After a short time was added second site oldsp.ru - for historical photos of St.-Petersburg, the second-largest megapolis in Russia.
In 2013 two projects were merged and migrated into global site PastVu - with a global scope. Principal maintainer and software architect of the new site becomes Pavel Klimashkin.
In 2020, the project became open source, and new maintainers joined the development.
Over the years, many people have uploaded, attributed, and geo-located images (photographs, paintings, drawings), under the leading of regional and global moderators and administrators team.
   - RU:
Проект был основан в 2009 году [Ильей Варламовым](https://varlamov.ru/).
Изначально это был локальный проект oldmos.ru, посвящённый историческим фотографиям Москвы. Проект изначально создавался как краудсорсинговый с широким кругом участников.
Через короткое время был создан второй сайт oldsp.ru — для исторических фотографий Санкт-Петербурга.
В 2013 году два проекта были объединены и перенесены на новом домене PastVu.com, при этом проект получил глобальный охват. Главным разработчиком и программным архитектором нового сайта стал [Павел Климашкин](https://github.com/klimashkin).
В 2020 году код проекта стал открытым и разработке подключились новые участники.
В течение этих лет множество участников проекта загружали, атрибутировали и привязывали к картке изображения (фотографии, картины, рисунки) под руководством команды региональных и глобальных модераторов и администраторов.

**Comment by paul-k-pastvu** [comment]
Пожелание три: в разделе "История проекта" / "Project History" создать подраздел "Вехи" / "Milestones"  в  виде горизонтального таймлайна: под каждым годом список событий со ссылками на новости сайта (потом подкорректируем и детализируем) - см. https://github.com/PastVu/pastvu/wiki/Project-history-(en)

2009  -  2013  -  2019
...
...

**Comment by paul-k-pastvu** [comment]
Пожелание четыре: Все разделы отделить горизонтальной чертой, ккаой раньше отделялась строка про краудфандинг

**Comment by paul-k-pastvu** [comment]
Пожелание пять: коллаж, наверное, можн будет убрать

**Comment by paul-k-pastvu** [comment]
Вопрос, добавлять ли туда же всех разработчиков по мере их появления, или сделать потом отдельную страничку?

Если добавлять, то уже сейчас можно включать Руслана Кабалина и Михаила (mkgrgis).

**Comment by aeifn** [comment]
> Вопрос, добавлять ли туда же всех разработчиков по мере их появления, или сделать потом отдельную страничку?
> 
> Если добавлять, то уже сейчас можно включать Руслана Кабалина и Михаила (mkgrgis).

Эта страница лучше всего отображает вклад разработчиков: https://github.com/PastVu/pastvu/graphs/contributors?type=a

**Comment by paul-k-pastvu** [comment]
> > Вопрос, добавлять ли туда же всех разработчиков по мере их появления, или сделать потом отдельную страничку?
> > Если добавлять, то уже сейчас можно включать Руслана Кабалина и Михаила (mkgrgis).
> 
> Эта страница лучше всего отображает вклад разработчиков: https://github.com/PastVu/pastvu/graphs/contributors?type=a

1) Нужно ли где-то на неё сослаться?
2) Я всегда за то, чтобы написать что-то текстом.

И ещё - добавь, пожалуйста, фоновую картинку 100х100 для своего юзерпика (для "карусели"), свой текст также поправь, если я был неточен - см. выше "пожелание раз".

**Comment by mkgrgis** [comment]
Ниже ссылки на основную страницу проекта https://github.com/PastVu/pastvu можно добавить ссылку
"На GitHub нам помогали".

**Comment by paul-k-pastvu** [comment]
> Ниже ссылки на основную страницу проекта https://github.com/PastVu/pastvu можно добавить ссылку
> "На GitHub нам помогали".

И как там указать персонально Вас? Что конкретно написать? 

1. Только ник, 
2. ник с краткой аннотацией, 
3. ник и ссылку на профиль участника GitHub, 
4. ник и ссылку на профиль участника PastVu
5. 

?

**Comment by mkgrgis** [comment]
Ссылку на "На GitHub нам помогали" лучше поставить на https://github.com/PastVu/pastvu/graphs/contributors?type=a
Снизу должна хорошо смотреться таблица с именем, двумя никами и двумя ссылками на никах: на профиль участника GitHub и на профиль участника PastVu. Меня пока можно не указывать, вклад не так велик. Как сделаю выбор направлений, можно будет подумать. +91 строка от меня курам на смех.

**Comment by paul-k-pastvu** [comment]
> Ссылку на "На GitHub нам помогали" лучше поставить на https://github.com/PastVu/pastvu/graphs/contributors?type=a

Согласен. Это я всё для примера спрашиваю, на будущее.

**Comment by kabalin** [comment]
Касательно высплывающего окна страницы "О проекте", предлагаю его оставить в сокращенном виде:
- Остается информация о версии, копирайт openstreetmap, мозайка снимков в нижней части, ссылка на github
- "Лица проекта" - переносятся на страницу документации "О проекте" (https://docs.pastvu.com/intro)
- Добавляется параграф с общей информацией о проекте (кратко) и ссылка на документацию.

Получается примерно так (без общей информации о проекте которая будет впоследствии добавлена):
![image](https://user-images.githubusercontent.com/329780/193450074-36ac6a30-7969-4ea2-b95f-43d332fadc01.png)

Все остальные изменения, предлагаемые в комментариях выше, можно рассматривать в контексте страницы документации (мы этот тикет можем перенести в проект [`docs`](https://github.com/pastvu/docs) для удобства или создать новый с ссылкой на этот)

**Comment by paul-k-pastvu** [comment]
Да, так и нужно сделать.

вс, 2 окт. 2022 г. в 17:44, Ruslan Kabalin ***@***.***>:
