### ISSUE TITLE
Update MongoDB to 4.4 / Обновление MongoDB до версии 4.4

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#191]
Currently we use mongo 3.2.22 which is going to be deprecated.

Problem is that database can`t be automatically migrated without modifications.

Need to determine, what exactly we need to change in database.

**Comment by mkgrgis** [comment]
Is there any full document about tree format for the DB? Not in code, but exactly only DB structure?
I can sketch some fast API calls or more regular Pg structure for the DB, see https://habr.com/ru/company/otus/blog/523322/ , § "Таблицы — это типы" and https://habr.com/ru/company/itsumma/blog/436416/

**Comment by aeifn** [comment]
There is only a database dump as a reference: https://varlamov.me/pastvu/github/pastvu.tar.gz

**Comment by mkgrgis** [comment]
Thanks. I have seen. I need to learn basic MongoDB operations. Is there any analogue of xsd or some autodoc about typical DB elements, not examples of data?

**Comment by aeifn** [comment]
> Is there any analogue of xsd or some autodoc about typical DB elements, not examples of data?

Not, unless to build it from data.

**Comment by mkgrgis** [comment]
Thanks. I think there is no official autodoc builder for PastVu DB?

**Comment by aeifn** [comment]
Остаются еще критические обновления, которые ломают приложение 
log4js@6.3.0
mongoose@5.10.11

**Comment by aeifn** [comment]
Остаются еще критические обновления, которые ломают приложение
log4js@6.3.0
mongoose@5.10.11

**Comment by aeifn** [comment]
После обновления на Mongo 4.4.1, несмотря на то, что в целом все работает, в логах app_ru появилась такая ошибка:
[ERROR] session - archiveExpiredSessions error:  { inspect: [Function: inspect] }

<img width="1544" alt="image" src="https://user-images.githubusercontent.com/13631515/98781078-d9f44480-2406-11eb-9bb5-bbb031b84109.png">

Поэтому в коммите https://github.com/PastVu/pastvu/commit/0c27011177ad4cc1d097ec199c45f3c812250ce6#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R6 версия Монги была возвращена на 3.2.22

**Comment by aeifn** [comment]
Запущена полная копия базы из бэкапов на Mongo версии 4.4.1

https://pastvu.bhyve.cloud

- почта уходит в заглушку
- вольюм с картинками смонтирован RO через sshfs

**Comment by aeifn** [comment]
Еще одна ошибка на Монге 4.4.1 в этом месте: https://github.com/PastVu/pastvu/blob/05d7036f3a5dcbb53aacb9e82d30437ac7f70a74/public/js/socket.js#L222

socket.run "region.giveListFull" returned error Object

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13631515/98782235-b0d4b380-2408-11eb-8ad3-ebb87d21b550.png">

**Comment by kabalin** [comment]
> Еще одна ошибка на Монге 4.4.1 в этом месте:

Но это клиенту вернулась ошибка с сервера - нужно посмотреть что на момент ошибки сервер в лог записал. Напишите по возможности как ее воспроизвести.

**Comment by aeifn** [comment]
> Напишите, по возможности, как ее воспроизвести.

Достаточно вот здесь https://github.com/PastVu/pastvu/blob/f171fb06fdc9bbd315e8ebdffa5102a1da6e71d4/docker-compose.yml#L6 изменить на `image: mongo`, удалить старые контейнеры и вольюм с базой (`docker-compose down && docker volume rm pastvu_mongo`), затем заново импортировать базу и запустить приложение: https://github.com/PastVu/pastvu#run-with-docker. После запуска перейти по адресу http://localhost:3000/admin/region

Вот, кстати, backtrace ошибки:

```
app_1          | [2020-11-11 11:32:48.503] [ERROR] webapi-region - [RID-pl5t6x21kl S-27C0oM1v9RKT U-admin] Error calling method "region.giveListFull" with params: {}
app_1          |  MongoError: The 'cursor' option is required, except for aggregate with the explain argument
app_1          |     at Function.MongoError.create (/code/node_modules/mongodb-core/lib/error.js:31:11)
app_1          |     at /code/node_modules/mongodb-core/lib/connection/pool.js:489:72
app_1          |     at authenticateStragglers (/code/node_modules/mongodb-core/lib/connection/pool.js:435:16)
app_1          |     at Connection.messageHandler (/code/node_modules/mongodb-core/lib/connection/pool.js:469:5)
app_1          |     at Socket.<anonymous> (/code/node_modules/mongodb-core/lib/connection/connection.js:321:22)
app_1          |     at Socket.emit (events.js:314:20)
app_1          |     at addChunk (_stream_readable.js:307:12)
app_1          |     at readableAddChunk (_stream_readable.js:282:9)
app_1          |     at Socket.Readable.push (_stream_readable.js:221:10)
app_1          |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
app_1          | [2020-11-11 11:32:48.503] [ERROR] webapi-region - [RID-pl5t6x21kl S-27C0oM1v9RKT U-admin] Error calling method "region.giveListFull" with params: {}
app_1          |  MongoError: The 'cursor' option is required, except for aggregate with the explain argument
app_1          |     at Function.MongoError.create (/code/node_modules/mongodb-core/lib/error.js:31:11)
app_1          |     at /code/node_modules/mongodb-core/lib/connection/pool.js:489:72
app_1          |     at authenticateStragglers (/code/node_modules/mongodb-core/lib/connection/pool.js:435:16)
app_1          |     at Connection.messageHandler (/code/node_modules/mongodb-core/lib/connection/pool.js:469:5)
app_1          |     at Socket.<anonymous> (/code/node_modules/mongodb-core/lib/connection/connection.js:321:22)
app_1          |     at Socket.emit (events.js:314:20)
app_1          |     at addChunk (_stream_readable.js:307:12)
app_1          |     at readableAddChunk (_stream_readable.js:282:9)
app_1          |     at Socket.Readable.push (_stream_readable.js:221:10)
app_1          |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

```

**Comment by aeifn** [comment]
Запущена полная копия базы из бэкапов на Mongo версии 4.4.1
https://staging.pastvu.com/

 * почта уходит в заглушку
 * вольюм с картинками смонтирован readonly по sshfs

**Comment by paul-k-pastvu** [comment]
> Запущена полная копия базы из бэкапов на Mongo версии 4.4.1:

На макете сново не переключается язык.

**Comment by aeifn** [comment]
> На макете снова не переключается язык.

Проблема, специфичная для mongo 4.4.1: не сохраняются куки, соответственно, не переключается язык. На 3.2.22 работает. 
Предположительно, связано с https://github.com/PastVu/pastvu/issues/191#issuecomment-725252742

**Comment by kabalin** [comment]
>изменить на image: mongo, удалить старые контейнеры и вольюм с базой (docker-compose down && docker volume rm pastvu_mongo), затем заново импортировать базу и запустить приложение: https://github.com/PastVu/pastvu#run-with-docker. После запуска залогиниться (admin/admin) и перейти по адресу http://localhost:3000/admin/region.

Вольюм я просто переименовал после того как опустил контейнеры, чтобы потом переключится обратно на 3.2 без потери тестовой базы. Ошибку воспроизвел, спасибо!

> Проблема, специфичная для mongo 4.4.1: не сохраняются куки, соответственно, не переключается язык.

У меня куки сохраняет. Проверьте, в [`client.hostname`](https://github.com/PastVu/pastvu/blob/master/config/local.config.js.example#L6) у вас точно стоит `staging.pastvu.com`?

**Comment by aeifn** [comment]
> Вольюм я просто переименовал после того как опустил контейнеры

Магия! В docker volume такой команды нет.

> У меня куки сохраняет. Проверьте, в [`client.hostname`] у вас точно стоит `staging.pastvu.com`?

Да, в `client.hostname` стоит `process.env.DOMAIN`, а в окружении `export DOMAIN=staging.pastvu.com`.

Перезапустил стек, проверил: куки сохраняются, язык переключается.

Но возникла новая ошибка: не открываются изображения по адресу `/_pr/`:

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/13631515/98877272-21271780-2491-11eb-8d27-5be2a259895b.png">

**Comment by kabalin** [comment]
> Магия! В docker volume такой команды нет.

```
diff --git a/docker-compose.yml b/docker-compose.yml
index d8e21a67..8b5a809b 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -3,9 +3,9 @@ version: '3.8'
 services:
 
   mongo:
-    image: pastvu/mongo:3.2.22
+    image: mongo:4.4
     volumes:
-      - mongo:/data/db
+      - mongo4:/data/db
     expose:
       - "27017"
     ports:
@@ -73,4 +73,4 @@ services:
 volumes:
   store:
   sitemap:
-  mongo:
+  mongo4:
```

**Comment by kabalin** [comment]
И еще - куда патчи присылать - может отдельный бранч пока заведем для mongo 4?

**Comment by aeifn** [comment]
> И еще - куда патчи присылать - может отдельный бранч пока заведем для mongo 4?

https://github.com/PastVu/pastvu/tree/mongo4

**Comment by kabalin** [comment]
> А что нужно сделать чтобы воспроизвести? 😃 Cерьезно, cудя по коду это protected, но неопубликованные у меня отдаются самому себе как `/_p/`, хотя если я подменяю на `/_pr/` то тоже отдаются без ошибок.

^ @aeifn (я наверное редактировал когда вы уже прочитали первую часть моего коммента)

**Comment by aeifn** [comment]
> А что нужно сделать чтобы воспроизвести? 😃 Cерьезно, cудя по коду это protected, но неопубликованные у меня отдаются самому себе как `/_p/`, хотя если я подменяю на `/_pr/` то тоже отдаются без ошибок.

Я сделал вас (/u/nowhereman) на стейдже администратором, сейчас при логине должна вот такая картина быть:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13631515/98961032-2bd7c000-2516-11eb-8ce5-8fb2f2ffebab.png">

**Comment by aeifn** [comment]
Хотя, возможно, проблема в правах на файлы при монтировании? Я уточню этот момент.

**Comment by aeifn** [comment]
> > А что нужно сделать чтобы воспроизвести? 😃 Cерьезно, cудя по коду это protected, но неопубликованные у меня отдаются самому себе как `/_p/`, хотя если я подменяю на `/_pr/` то тоже отдаются без ошибок.

Кажется, разобрался! Это не баг! Эти фотографии были опубликованы и перемещены в хранилище из /private в /public, а база не обновилась!

**Comment by aeifn** [comment]
Накатил свежий дамп на Mongo 4.4.1: https://staging.pastvu.com

**Comment by aeifn** [comment]
С обновлениями то же самое, что и с https://github.com/PastVu/pastvu/issues/245#issuecomment-727680107. Тема вынесена в отдельный проект https://github.com/PastVu/pastvu/projects/4, в котором можно будет отрабатывать бампы depend-бота в том числе.

**Comment by aeifn** [comment]
Как временное решение, на staging.pastvu.com установлен пароль staging/staging для того, чтобы пользователи случайно не перепутали сайты и чтобы он не начал индексироваться поисковиками.

**Comment by aeifn** [comment]
Получается, затык только в этом: https://github.com/PastVu/pastvu/issues/191#issuecomment-725373542

**Comment by kabalin** [comment]
@aeifn не только. Проблема бага из https://github.com/PastVu/pastvu/issues/191#issuecomment-725373542 описана здесь https://docs.mongodb.com/manual/reference/command/aggregate/:
> MongoDB 3.6 removes the use of aggregate command without the cursor option unless the command includes the explain option. Unless you include the explain option, you must specify the cursor option.

Но этого недостаточно, там похоже есть еще какая то несогласованность с `mongoose` (появляется новая ошибка). Надо сначала `mongoose` привести в соответствие с версией Монго (https://mongoosejs.com/docs/compatibility.html), прежде чем смотреть дальше. Простой апгрейд mongoose до `5.7.0` делает невозможным запустить сервис, надо разбираться.

**Comment by aeifn** [comment]
> там похоже есть еще какая то несогласованность с `mongoose` (появляется новая ошибка).

Известно, в каком месте?

**Comment by kabalin** [comment]
Да в той же aggregate, ругается что нет такого оператора внутри условий, хотя по докам текущей версии монги ошибок там нет. Короче надо сначала версию mongosejs привести в порядок, соблюсти условия заявленной совместимости.

Везде где используется aggregate вылетает ошибка (к счастью не так много мест).

**Comment by kabalin** [comment]
Отдельно хотел узнать какой будет план апгрейда? Может индексы геоданных заменить с `2d` на `[2dsphere](https://docs.mongodb.com/manual/core/2dsphere/)` по восстановлении дампа на текущую версию монги?

**Comment by aeifn** [comment]
> Отдельно хотел узнать какой будет план апгрейда?

План такой:

1. полная остановка приложения в период наименьшего количества запросов (обычно 6-7 утра)
2. создание дампа базы
3. замена версии mongo
4. импорт дампа
5. запуск заранее подготовленных и оттестированных на стейдже скриптов обновления схем и данных
6. запуск приложения на новой версии базы

> Может индексы геоданных заменить с `2d` на [`2dsphere`](https://docs.mongodb.com/manual/core/2dsphere/) по восстановлении дампа на текущую версию монги?

Я поддерживаю, нужно тогда подготовить скрипт обновления индексов

**Comment by aeifn** [comment]
> Отдельно хотел узнать какой будет план апгрейда? Может индексы геоданных заменить с `2d` на [`2dsphere`](https://docs.mongodb.com/manual/core/2dsphere/) по восстановлении дампа на текущую версию монги (чтобы можно было использовать [операторы работы с геоданными](https://docs.mongodb.com/manual/geospatial-queries/#id1) в полной мере)?

Вот, кстати, прежние скрипты миграции: https://github.com/PastVu/pastvu/tree/e2b504970304b31ecaad1e8e52c897aa453ea2e4/basepatch

**Comment by kabalin** [comment]
Удалось запустить (mongoose 5.10.15, mongodb 4.4.1), теперь надо отловить все ошибки (их много). Пришлю завтра PR c тем что удалость достигнуть.

![mongoose](https://user-images.githubusercontent.com/329780/99742786-1e997300-2acc-11eb-9712-b94ac332d602.png)

**Comment by aeifn** [comment]
> Удалось запустить (mongoose 5.10.15, mongodb 4.4.1), теперь надо отловить все ошибки (их много). Пришлю завтра PR c тем что удалость достигнуть.
> 
> ![mongoose](https://user-images.githubusercontent.com/329780/99742786-1e997300-2acc-11eb-9712-b94ac332d602.png)

Awesome!  ;)

**Comment by klimashkin** [comment]
Странный подход сначала делать апдэйт, а потом разбираться с ошибками.
Надо же сначала пройтись по ченджолам мажорных версий и понять что изменилось.

**Comment by kabalin** [comment]
Да я [майгрейшн гайд](https://mongoosejs.com/docs/migrating_to_5.html) просматриваю. Я не на столько знаком с кодом проекта (как впрочем и с mongoose я прежде не сталкивался), чтобы сходу понять что и где нужно исправить. Мне проще трейсить изменения от ошибки - когда я встречаю ошибку, тогда я смотрю док чтобы понять что изменилось и ищу все упоминания функции в коде, попутно разбираюсь как вы реализовали тот или иной функционал. Это когда я постоянно с чем-то работаешь, там да, можно по ченжлогу сразу прикинуть где что может "отъехать" после апгрейда.

**Comment by kabalin** [comment]
Добавил инструкцию по отладке #298

PR по обновлению mongoose будет позже, не стал публиковать промежуточный результат, там как оказалось при детальном рассмотрении не так много изменений, выложу законченную рабочую версию.

**Comment by kabalin** [comment]
@aeifn можно попросить вас сделать ребейс ветки mongo4 (привести ее в соответсвие с мастером) или пересоздать, мы туда еще ничего не мержили.

**Comment by kabalin** [comment]
>там как оказалось при детальном рассмотрении не так много изменений

Это было преждевременное оптимистичное заявление человека не знакомого с кодом в достаточной мере 😏

**Comment by aeifn** [comment]
> @aeifn можно попросить вас сделать ребейс ветки mongo4 (привести ее в соответсвие с мастером) или пересоздать, мы туда еще ничего не мержили.

Сделано.

**Comment by kabalin** [comment]
> <img alt="image" width="1544" src="https://user-images.githubusercontent.com/13631515/98781078-d9f44480-2406-11eb-9bb5-bbb031b84109.png">
> 

@aeifn, вы не знаете почему в докер логе все сообщения дублируются?

**Comment by aeifn** [comment]
> @aeifn, вы не знаете почему в докер логе все сообщения дублируются?

"Благодаря" моему хардфиксу a45f22c312873446b40b38778de01742d5836ad5, который я сделал для того, чтобы в `production` логи шли в докер, а не только в файловую систему контейнеров.

Потом я предлагал вообще всегда писать в stdout, что решало проблему дублирования: https://github.com/PastVu/pastvu/pull/300 но PR не был слит.

**Comment by kabalin** [comment]
> Потом я предлагал вообще всегда писать в stdout, что решало проблему дублирования: #300 но PR не был слит.

Давайте сделаем, отлаживать неудобно.

**Comment by aeifn** [comment]
> Давайте сделаем, отлаживать неудобно.

Исправил в 2da576f28cf20089124d668e218d90deea6f2523.
Лог в файлы пока не стал убирать, т. к. им могут пользоваться некоторые администраторы сайта, по крайней мере, пока не включена репликация.

**Comment by mkgrgis** [comment]
Ув. Руслан, @kabalin, не могли бы Вы подсказать на какой стадии миграции мы находимся? https://github.com/PastVu/pastvu/pull/346 завершилось благополучно, но списка оставшихся проблем там нет. `dbEval` удалось потеснить, но не вижу получилось ли выдавить _совсем_? Упоминались миграционные патчи на БД, но их реализация не обсуждалась.

**Comment by kabalin** [comment]
Что осталось я упоминал в https://github.com/PastVu/pastvu/pull/346#issue-564322107, по сути механизм миграции базы сделать (еще не готово). Серьезных проблем уже нет, можно ветку `mongo4` ставить на стейж и начинать тестировать. `dbEval` больше не используется.

**Comment by mkgrgis** [comment]
Спасибо! Так и предполагал, что осталось задать правила переноса коллекций и гарантировать сохранение смысловых связей данных. Есть ли у Вас какие-то рекомендации к тестированию? Будем пробовать стандартный набор функций: зарегистрироваться, залить фото, отмодерировать, прокомментировать или что-то более хитрое?

**Comment by kabalin** [comment]
Все стандартные сценарии поведения пользователей, кроме этого сценарии связанные с dbEval:

- converter.convertPhotosAll - запуск конвеера конвертации для большого числа фото (url path /admin/photo) - все переконвертировать не стоит, попробовать запустить для региона с небольшим количеством фото.
- cluster.clusterPhotosAll - пересчет размера кластера (url path /admin/map)
- region.calcRegionStats - пересчет статистики регионов (url path /admin/region) - выбрать один регион, запустить перерасчет, убедиться что данные по статистике не изменились.
- session.calcUserStats - пересчет статистики пользователя (запускается автоматически раз в сутки) - можно исказить статистику для конкретного пользователя путем прямого изменения его записи в базе и проверить после очередного запуска пересчета что данные восстановились.
