### ISSUE TITLE
retromap.ru tilelayers first integration: get images from PastVu / объединение карт с историческими слоями retromap.ru, выдача точек изображений

### ISSUE THREAD

**Issue by mkgrgis** [PastVu/pastvu#197]
Авторы сайта retromap.ru имеют выбор слоя исторчиеской карты из списка. Список зависит от местности и датировки. Возможность была реализована в 2018 г. после письма об интеграции с pastvu.com.
Со стороны авторов сайта retromap.ru  сособенно инетресен API получения метаданных снимков с pastvu.com в данной области.

Резюме 16 ноября 2020 г.
**Реализовано**: показ изображений PastVu на RetroMap.
**Доработать**: отдачу всех изображений для местности (до некоторого масштаба) на RetroMap.
**Доработать**: ссылка на RetroMap под картой с сохраненеим датировки, масштаба и центра.
**Рассмотреть и макетировать**: отображение произвольных карт с RetroMap
_Отдельно_: наложение разных карт.

Since year 2018 there is f(lat0, lon0, lat1, lon1, date0, data1) function returning L.tileLayers[] (array) on http://retromap.ru 
see example http://retromap.ru/061942_0420092_55.666645,37.670745 

For the retromap.ru authors will be useful API function from https://github.com/PastVu/pastvu/wiki/API like 
`https://pastvu.com/api2?method=photo.getByBounds&params={"z":11,"bounds":[37.401553,-122.91727],[37.96561,-121.758556]}`

**Comment by aeifn** [comment]
Пока непонятен метод взаимодействия. 
Как получить список доступных карт с retromap.ru?

Когда карты получены, из нужно накладывать вторым слоем поверх штатных карт, нужно этот момент тоже продумать в плане реализации и UI.

**Comment by hutun** [comment]
1. Что мы хотим на retromap.ru: сделать возможность отображать фото pastvu на нашем сайте подобно тому, как мы отображаем фото Википедии:
http://retromap.ru/051952_55.755785,37.617616&w=ru0 
При работе с Википедией мы используем API, сходный с предложенным вами.
2. Сейчас у нас на сайте около 3500 карт. Все они явно не требуются для пользователей pastvu. Более того, некоторые карты находятся не на наших серверах - здесь есть вопросы. Первым элементом нашего API должна быть процедура выбора карт с учетом желаний пользователя или еще чего-то
3. Второй элемент нашего API - передача информации о выбранной карте или картах (название, preview, центр, bounds, что-то еще)
3. Третий элемент нашего API - функция доступа к тайлам выбранной карты

**Comment by paul-k-pastvu** [comment]
Related with the #166

**Comment by paul-k-pastvu** [comment]
> Пока непонятен метод взаимодействия.
> Как получить список доступных карт с retromap.ru?
> 
> Когда карты получены, из нужно накладывать вторым слоем поверх штатных карт, нужно этот момент тоже продумать в плане реализации и UI.

Мы пока даже имеющиеся карты не умеем накладывать друг на друга. Про наложение нужен отдельный тикет.
Пока можно обсуждать только подключение исторических карт в общий селектор. Например так:

- В селектор добавляется новая секция "RetroMap"
- В ней отображаются карты, доступные для данной точки (или для данного региона); возможно, имеет смысл составить предварительный список, и потом уже добавлять туда отдельные карты по запросу.
- Должен быть доступен диапазон датировок, так как иногда важно попасть в 10-летний прромежуток, а иногда и +/- 50 лет не играют роли.
- В качестве идентификатора карты нужен год + краткое обозначение и/или указание масштаба

Вся эта красота не влезет в стандартный селектор вместе с тем, что там уже сейчас есть - нужно его перерабатывать (тоже отдельный тикет).

**Comment by mkgrgis** [comment]
В рамках существующего селектора можно выделить массив массивов для слоёв, из которого динамические формировать набор доступных карт
1. На входе центр и датировка.
`var layersArr  = f (φ₀, λ₀, t₀, t₁);`
2. Добавить интернационализацию названий и лицензионных строк (частично сделано)
3. Запрос на retromap для списка доступных карт
`var retromapLayers  = f (φ₀, λ₀, t₀, t₁);`
4. При выборе конкретной исторической карты - получение функции доступа, то есть L.tileLayer от retromap.

При смене датировки или позиции снова
`var retromapLayers  = f (φ₀, λ₀, t₀, t₁);`

**Comment by hutun** [comment]
А как получить Идентификатор приложения (app) для retromap.ru для работы с API Pastvu? Насколько я понял, это обязательный параметр

**Comment by paul-k-pastvu** [comment]
> А как получить Идентификатор приложения (app) для retromap.ru для работы с API Pastvu? Насколько я понял, это обязательный параметр

Напишите, пожалуйста, запрос на support@pastvu.com - в ответ придет ключ ;)

**Comment by hutun** [comment]
Ключ пришел, но запрос блокируется:
Запрос из постороннего источника заблокирован: Политика одного источника запрещает чтение удаленного ресурса на https://pastvu.com/api2?app=h9rJOQW9zatJmMIZeVQdBSQEes3YZQHE&rid=retromap&stamp=1603746230357&method=photo.giveNearestPhotos&params={%22geo%22:[55.758031,37.617187],%22limit%22:12}. (Причина: отсутствует заголовок CORS «Access-Control-Allow-Origin»).

**Comment by aeifn** [comment]
В response https://pastvu.com/api2 добавлен заголовок
Access-Control-Allow-Origin: *
 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/13631515/97435436-757ab500-1931-11eb-8fa8-16d807ec9fe4.png">

**Comment by paul-k-pastvu** [comment]
> При смене датировки или позиции снова
> `var retromapLayers = getRetromapLayers (φ₀, λ₀, t₀, t₁);`

При такой динамической выборке нам придется дать пользователю какой-то островок стабильности. Нужно, чтобы ранее выбранная карта как-то сохранялась, пока не выбрана новая. То есть нужен блок типа "последние использованные" (Recent maps). Я напишу отдельный тикет на эту тему.

**Comment by aeifn** [comment]
@hutun проблема с CORS решилась после добавления хедера?

**Comment by hutun** [comment]
@aeifn Всё с этим ОК, спасибо. Посмотрите, что получилось. На тестовом примере нужно кликнуть "Что там" в верхнем меню
retromap.ru/start1.php?0619371_55.770158,37.582962
Если кликать картинки, то отображается маркер. Примерно такое могут использовать те посетители pastvu, которые хотят проверить привязку картинке на ЛЮБОЙ карте retromap.
Пожелание: а давайте добавим в ответ photo.giveNearestPhotos координаты geo и dir - тогда без больших хлопот можно будет отображать маркеры ближайших к центру фоток.
Можно сделать отображение на картах кластеров - но не уверен, что это будет соответствовать основной цели retromap

**Comment by aeifn** [comment]
> Пожелание: а давайте добавим в ответ на запрос photo.giveNearestPhotos координаты geo и dir - тогда без больших хлопот можно будет отображать маркеры ближайших к центру фоток.

Добавлено коммитом https://github.com/PastVu/pastvu/commit/e0da2af94313c503e518644c8df670c6ce721bb2

**Comment by hutun** [comment]
Спасибо, получили geo и dir в запросе photo.giveNearestPhotos. Только, по-моему, здесь изменен порядок Lat Lng по сравнению с ответом на запрос photo.giveForPage

**Comment by paul-k-pastvu** [comment]
> @aeifn Всё с этим ОК, спасибо. Посмотрите, что получилось. На тестовом примере нужно кликнуть "Что там" в верхнем меню
> http://retromap.ru/start1.php?0619371_55.770158,37.582962
> Если кликать картинки, то отображается маркер. Примерно такое могут использовать те посетители pastvu, которые хотят проверить привязку картинки на ЛЮБОЙ карте retromap.

По-моему, замечательно!
Может быть, в таком варианте это действительно снимет остроту вопроса сполучением карт RetroMap на PastVu. Однако отработать взаимодействие в эту сторону всё равно будет полезно.
 
Я так понимаю, что это, конечно, пока макет, и он будет допиливаться. Тем не менее, несколько замечаний:
1) Сравниваем, как выглядит описание фото
RetroMap
![image](https://user-images.githubusercontent.com/60163100/97768733-4719f700-1b36-11eb-94ec-143c99e04298.png)

PastVu
![image](https://user-images.githubusercontent.com/60163100/97768756-77619580-1b36-11eb-91ab-a3387c8533e6.png)

Я выделил пропавшие фрагменты. Информацию об авторстве терять нехорошо (если это мы её не отдаем - напишите, будем пилить). Заголовки полей "Автор:" и "Источник:" лучше бы отображать, чтобы было однозначно понятно, что именно означают эти строки.

2) Крайне желательно, чтобы где-то в описании фото появилась активная ссылка обратно на PastVu. Она однозначно генерируется на основе значения "cid"

Может быть, региональная строка "Россия ,Москва ,ЦАО ,Пресня" вам вообще не особо нужна (на PastVu она генерируется по точке и там каждый элемент является активной ссылкой на галерею соответствующего региона).

Вообще, стоит подумать, нужно ли тащить с PastVu описания источников (которые у нас совершенно не формализованы и не типизованы). Ведь для RetroMap источником является сайт PastVu. Может быть как раз заменить эту строку на что-то вроде "Источник: https://pastvu.com/p/1088527", отделив как-то визуально от остального описания фото?

**Comment by hutun** [comment]
1. Представленная выше ссылка http://retromap.ru/start1.php?0619371_55.770158,37.582962 --> Что там -  это макет, на котором можно определить подмножество подходящих для работы в pastvu карт, Среди них есть несколько карт, общих для всех регионов. Помимо того, для каждого региона можно определить подходящие по датировке и разрешению карты. Как я и предполагал, выбор карт, подходящих для работы с картинками - это самое тёмное место.
2. На подписи к картинкам и интерфейс макета можно пока не обращать внимания - это простая часть работы. Сcылки на pastvu, естественно, будут.
3. Напоминание: в ответе на запрос photo.giveNearestPhotos в передаваемых координатах фотки geo изменен порядок Lat Lng по сравнению с ответом на запрос photo.giveForPage - полагаю, что это ошибка

**Comment by paul-k-pastvu** [comment]
Сейчас галка "Только подробные" для Москвы всё равно возвращает слишком много карт. Например, схематический план Москвы 1961 года  http://retromap.ru/start1.php?0519611_55.771938,37.608947 "подробным" я бы не считал.

Нет ли способа как-то ещё автоматически сузить эту выборку? Если нет, то придется отбирать полезные карты вручную и где-то держать список карт, из которого уже выбирать пригодные для показа пользователю в конкретной точке.

**Comment by aeifn** [comment]
> * Напоминание: в ответе на запрос photo.giveNearestPhotos в передаваемых координатах фотки geo изменен порядок Lat Lng по сравнению с ответом на запрос photo.giveForPage - полагаю, что это ошибка

Исправлено коммитом: f4cf8f5

**Comment by hutun** [comment]
Мне кажется, автоматический выбор карт для показа на pastvu сделать сложно. Проще выбрать по 5 карт для Москвы, Подмосковья и Питера, и 2-3 для каждого большого города или популярного места. Добавить несколько больших карт типа тех, которые перечислены как "Популярные" под картой на http://retromap.ru.

Для автоматического отбора "Подробных" карт у нас используются несколько параметров:
- maxZoom - выше него тайлов нет, идёт цифровое увеличение
- scale - масштаб исходной карты, есть не у всех карт
- rating - задается вручную при вводе карты - просто степень привлекательности карты
- bounds - область, покрываемая картой

Понятно, что для Кремля, Южного Бутово и тундры критерии "Подробная карта" различны. Согласен, что для Москвы стоит сократить число "Подробных" карт.

**Comment by hutun** [comment]
Доработали макет просмотра привязки картинок pastvu со старых карт retromap
http://retromap.ru/start2.php?1419445_z15_59.719109,30.405092&w=pv0
Картинки кликабельны. Можно использовать для выбора карт.

**Comment by mkgrgis** [comment]
Спасибо, @hutun ! Со стороны PastVu остаётся выдача не ближайших точек, а полного набора для относительно небольшой территории.

Со стороны retromap нужна формальная система кодирования карт, чтобы стабильный индекс мог включаться в пользовательские настройки pastvu. Нужна точка забора массива описаний карт в json для местности (центра + масштаба) и датировки. Заведомо выбрасываем источники после 2000 г.
Остальная фильтрация по моему мнению должна быть со стороны pastvu. Именно эту фильтрацию есть смысл обсуждать дальше.

**Comment by paul-k-pastvu** [comment]
> Доработали макет просмотра привязки картинок pastvu со старых карт retromap
> http://retromap.ru/start2.php?1419445_z15_59.719109,30.405092&w=pv0
> Картинки кликабельны. Можно использовать для выбора карт.

Макет прекрасен, мне всё нравится. В принципе, для пользователей RetroMap это уже и в нынешнем виде полезный и интересный функционал, так что можно было бы сделать совместную новость и дальнейшее развитие (больше точек и т.д.) делать уже в рабочем порядке. Главное, @hutun, когда решите это выкатывать в рабочую версию, предупредите, чтобы мы и у себя тоже проанонсировали.

Что касается текущих ожиданий со стороны PastVu, то дополню то, что обозначил @mkgrgis выше.
Нам наверняка будет удобным дать пользователю возможность прейти на RetroMap по ссылке вида http://retromap.ru/start2.php?1419445_z15_59.720472,30.405950&w=pv125631 . Для этого нужно как-то синхронизировать кодировку уже используемых в PastVu карт, чтобы пользователь попадал на ту же карту в том же масштабе (и далее уже сам выбирал из богатого списка). 

В принципе, это может быть вообще минимальный функционал "первой очереди" - раз из RetroMap будет прямая ссылка на PastVu, то и мы должны как минимум "ответить взаимностью".

**Comment by hutun** [comment]
Перенесли просмотр картинок PastVu в рабочую версию  - пока без анонса
http://retromap.ru/1419443_59.568397,30.096402&w=pv
http://retromap.ru/131943_55.815847,37.710978&w=pv104822
Если нет принципиальных замечаний, можно делать анонсы

**Comment by paul-k-pastvu** [comment]
> Перенесли просмотр картинок PastVu в рабочую версию - пока без анонса

Справа от датировок можно ставить запятую, справа от названия - точку.

![image](https://user-images.githubusercontent.com/60163100/98453196-86180000-2167-11eb-84ea-6451256f8c22.png)

А так я готовлю новость.

**Comment by paul-k-pastvu** [comment]
Ещё однео мелкое замечание, по второй ссылке - у вас там окошко

**Comment by hutun** [comment]
Запятую после даты поставим. Точку в конце заголовка ставить не нужно - у вас тоже точек нет

**Comment by hutun** [comment]
На всякий случай - о параметрах при обращении к картам и картинкам. Не думаю, что все детали нужно знать обычным посетителям

1.	Структура параметров при обращении в блок просмотра карт:

[MAPCODELEFT][_MAPCODERIGHT][_zZOOM][_LAT,LNG]  - при просмотре карт 

MAPCODELEFT, MAPCODERIGHT – коды карт, отображаемых в левой и правой панелях. При отсутствии одного из кодов во всю ширину экрана отображается одна указанная карта
LAT,LNG – координаты центра карты. При отсутствии параметра карта устанавливается в точку, заданную в описании карты.
ZOOM – значение зума при просмотре. При отсутствии параметра устанавливается зум, на единицу меньший максимального зума просматриваемой карты

Пример:
http://retromap.ru/061942_0519641_z14_55.787915,37.531013

Параметры могут быть заданы в произвольном порядке.

2.	Параметры при просмотре фотографий PastVu:

[MAPCODE][_zZOOM][_LAT,LNG][&w=pv]] – при просмотре 24 фотографий PastVu, ближайших к точке с координатами [LAT,LNG]
[MAPCODE][_zZOOM][_LAT,LNG][&w=pvCID]] – при просмотре фотографии с индексом CID, заданным на PastVu

MAPCODE – код отображаемой карты.  По умолчанию отображается слева.
CID – параметр cid фотографии на сайте PastVu


Примеры:
http://retromap.ru/0619371_z18_55.770140,37.582468&w=pv
http://retromap.ru/071903_55.770164,37.582458&w=pv85992

3.	Структура кодов карт

Каждая карта имеет код вида TTYYYY[NN]. Код карты – основной её идентификатор при обращении к базе данных.
TT – тип карты, две цифры.
YYYY – четырехзначный год «издания» карты. Во некоторых случаях год задается условно и датировка уточняется в описании карты
NN – одно- или двузначное целое число – порядковый номер для различия нескольких карт одного типа и года 

Кодировка типов карт (наследие прошлого):

00 - [qt("Google карты%Google maps"),
         01 - qt("Яндекс карты%Yandex maps "),
         03 - qt("Bing карты%Bing maps"),
         04 - qt("Прочие on-line карты%Other on-line maps"),
         05 - qt("Карты Москвы 1945-2000х годов%Moscow maps 1945-2000s"),
         06 - qt("Карты Москвы 1920-1940х годов%Moscow maps 1920-1940"),
         07 - qt("Дореволюционные - XX век%Moscow maps 1900-1917"),
         08 - qt("Карты Москвы XIX века%Moscow maps - XIX century"),
         09 - qt("Карты Москвы XVIII века%Moscow maps - XVIII century"),
         10 - qt("Планы Москвы в древности%Ancient Moscow maps"),
         11 - qt("Карты Генплана 2025 года%Moscow development plan 2025"),
         12 - qt("Тематические карты%Thematic maps"),
         13 -  qt("Карты районов городов%Cities subregions"),
         14 - qt("Карты регионов России%Maps of Russian regions"),
         15 - qt("Карты заграничных территорий%Maps of non-Russian territories"),
         16 - qt("Карты мира и частей света%World maps")];
         24 - qt("Прочие карты%Other maps");

**Comment by paul-k-pastvu** [comment]
@hutun - см. новость https://pastvu.com/news/152

**Comment by hutun** [comment]
> @hutun - см. новость https://pastvu.com/news/152
Хорошо написано, спасибо!

**Comment by hutun** [comment]
> @hutun - см. новость https://pastvu.com/news/152
А можно сделать рабочую ссылку в первой фразе анонса:

С радостью сообщаем о первых результатах сотрудничества с командой известного сайта исторических карт **retromap.ru**.

**Comment by aeifn** [comment]
> > А можно сделать рабочую ссылку в первой фразе анонса:

Она не работает по технической причине: https://github.com/PastVu/pastvu/issues/243#issue-738541189
Надеюсь, скоро будет исправлено.

**Comment by hutun** [comment]
Может просто http добавить - ниже то работает

**Comment by hutun** [comment]
Здесь нужно http, а не https

**Comment by aeifn** [comment]
> Может просто http добавить - ниже то работает

Изменил ссылки на http://retromap.ru/select.html. Удивительным образом ссылки вида http://domain.com/ не работают, а ссылки вида http://domain.com/path работают. Надеюсь, проблема https://github.com/PastVu/pastvu/issues/243 будет решена.

**Comment by hutun** [comment]
Так тоже неплохо, хотя в конце концов нужно сослаться на home page.

**Comment by paul-k-pastvu** [comment]
> Так тоже неплохо, хотя в конце концов нужно сослаться на home page.

Разумеется. Прошу прощения, совершенно забыл про этот баг.

**Comment by mkgrgis** [comment]
Ув. @hutun , не могли бы вы добавить к себе на веб-ресурс такой инструмент как _координатная пипетка_. Суть в том, чтобы дать возможность пользователю навести курсор на некоторую точку на карте и получить её координаты для копирования на pastvu в такой элемент интерфейса
![изображение](https://user-images.githubusercontent.com/41448637/98581407-7e289f00-22d2-11eb-9306-8e4a9702ec1f.png)
Возможно, будет уместно где-нибудь рядом размещать предупреждение о точности привязки карты, если такие данные в явном виде где-нибудь на Вашем ресурсе доступны.

**Comment by hutun** [comment]
> 
> 
> Ув. @hutun , не могли бы вы добавить к себе на веб-ресурс такой инструмент как _координатная пипетка_. Суть в том, чтобы дать возможность пользователю навести курсор на некоторую точку на карте и получить её координаты для копирования на pastvu в такой элемент интерфейса
> ![изображение](https://user-images.githubusercontent.com/41448637/98581407-7e289f00-22d2-11eb-9306-8e4a9702ec1f.png)
> Возможно, будет уместно где-нибудь рядом размещать предупреждение о точности привязки карты, если такие данные в явном виде где-нибудь на Вашем ресурсе доступны.

1. А если просто сдвинуть карту и установить центр в нужную точку - координаты в адресной строке не подойдут? Помимо того, текущие координаты центра отображаются справа от логотипа вверху, а также в окне при клике в верхнем меню  "Поделиться". 
2. Насчёт точности карт - это одна из проблем. Даже ранние спутниковые снимки имеют погрешности - их делали под большим углом и они имеют заметные искажения. На практике довольно точны только топографические карты 20 века, сделанные по аэрофотосъемке и спутникам. Можно указывать, когда карта имеет большие погрешности.

**Comment by mkgrgis** [comment]
> А если просто сдвинуть карту и установить центр в нужную точку - координаты в адресной строке не подойдут? 

На pastvu скоро будут две точки. Одна исходная, которую удобно установить в центр и скопировать координаты. А другая точка будет относится к объекту на центральной гоизонтали фото, которую на retromap удобнее ловить курсором имея ввиду поставленную в центр точку съёмки.

> На практике довольно точны только топографические карты 20 века, сделанные по аэрофотосъемке и спутникам. Можно указывать, когда карта имеет большие погрешности.

Попробуйте выводить знак **⚠** рядом с координатами и по подсказке сообщать, например, "карта может иметь погрешность более ... метров, т.к. создана не по аэро или спутниковой съёмке". На координатах неплохо будет сделать подсказки: _широта_, **φ**, lat   и _долгота_, **λ**, lon, чтобы сразу можно было вспомнить что где в словесной, геодезической и GIS записи. Сижу в картах много лет, но до сих пор не всегда вспоминаю где что, когда присылают какое-нибуь сдвоенное число.

**Comment by hutun** [comment]
1. Не очень понял: подходит установка карты ретромап в центр с последующим чтением координат или нет.
2. Насчёт Lat Lng - сейчас, как правило, просто передается и отображается пара вещественных
https://www.google.ru/maps/@55.78752,37.3739571,13z
https://www.openstreetmap.org/#map=6/56.493/42.528
https://yandex.ru/maps/?from=tabbar&ll=37.821925%2C55.810098
3. Погрешность очень сложно оценить. Карта привязывается по точкам - иногда хватает 4 точки, а в спутниковых снимках доходит до 100. И всё равно, например, на краях остается погрешность. Улицы на картах часто шире реальных - нужно место для названий. Поэтому погрешность часто плавающая. Есть карты с заведомо большой погрешностью - их можно обозначать.

**Comment by mkgrgis** [comment]
>     Не очень понял: подходит установка карты ретромап в центр с последующим чтением координат или нет.

Полностью подходит для существующей схемы разметки изображений, но не будет подходить для двухточечной, когда центр карты будет наводить на точку съёмки, а нужно булет подобрать и скопировать координаты объекта по оси изображения.

>     Насчёт Lat Lng - сейчас, как правило, просто передается и отображается пара вещественных <...>
      Можно сделать bubble с текстами Широта, Долгота при наведении курсора на значения.

Да, речь как раз о том, чтобы высплывали подсказски со всеми тремя нотациями _широта_, **φ**, lat и _долгота_, **λ**, lon. 

> Погрешность очень сложно оценить.

Я не прошу оценивать погрешность, а просто обозначить условно _большую_ погрешность. Можно попробовать эвристику. Меньше 14 уровня и более подробные карты, но созданные до массовой аэрофотосъёмки помечать ⚠ рядом с координатами и по подсказке сообщать, например, "карта может иметь существенную погрешность более десятков метров".

> Есть карты с заведомо большой погрешностью - их можно обозначать.

Да, именно такова суть моего предложения, остальное детали вычисления заведомо большой погрешности.

**Comment by hutun** [comment]
> > Не очень понял: подходит установка карты ретромап в центр с последующим чтением координат или нет.
> 
> Полностью подходит для существующей схемы разметки изображений, но не будет подходить для двухточечной, когда центр карты будут наводить на точку съёмки, а нужно будет подобрать и скопировать координаты объекта по оси изображения.

Попробуйте просто кликнуть карту на макете
retromap.ru/start2.php?071903_55.758116,37.599892

Сделано просто для оценки концепта - примерно об этом идёт речь? Задержку можно отрегулировать или держать bubble открытым, пока курсор не ушел с него

**Comment by mkgrgis** [comment]
> Попробуйте просто кликнуть карту на макете
> http://retromap.ru/start2.php?071903_55.758116,37.599892

Отлично! Просто, элегантно и задача закрыта! Задержку бы давать не менее 4-5 секунд, т. к. PastVu пользуются в том числе пожилые люди с небольшой скоростью работы с мышью. Теперь дело за подсказками.

**Comment by hutun** [comment]
Добавил кнопку записи координат в буфер - теперь не надо суетиться, выделять текст координат и делать Copy
http://retromap.ru/start2.php?071903_55.758116,37.599892

**Comment by aeifn** [comment]
> Так тоже неплохо, хотя в конце концов нужно сослаться на home page.

Баг исправлен пулреквестом https://github.com/PastVu/pastvu/pull/246.

**Comment by mkgrgis** [comment]
@hutun 
> теперь не надо суетиться, выделять текст координат и делать Copy

Спасибо, Сергей. Остаётся только рисовать красную линию от точки щелчка до границы всплывшей панельки (bubble), чтобы во время движения к кнопке "Коипровать" можно было продолжать размышления о точке, которую выбрал. Или как-нибудь ещё обозначить место щелчка. Время жизни bubble я бы увеличил в 2-2,5 раза.

**Comment by hutun** [comment]
> Спасибо, Сергей. Остаётся только рисовать красную линию от точки щелчка до границы всплывшей панельки (bubble), чтобы во время движения к кнопке "Коипровать" можно было продолжать размышления о точке, которую выбрал. Или как-нибудь ещё обозначить место щелчка. Время жизни bubble я бы увеличил в 2-2,5 раза.

Добавили. Маркер кликабельный
http://retromap.ru/start2.php?071903_55.758116,37.599892

**Comment by mkgrgis** [comment]
>  Добавили. Маркер кликабельный

Спасибо, задача решена. Теперь можно пробовать привязать на retromap.ru как точку фотографа, так и объект по центру фото.
Из пожеланий остались только подсказки к главной панели координат.

**Comment by paul-k-pastvu** [comment]
> Добавили. Маркер кликабельный
> http://retromap.ru/start2.php?071903_55.758116,37.599892

Если быстро менять точку, то получается задумчиво:
![image](https://user-images.githubusercontent.com/60163100/98998571-6efe5700-2547-11eb-8812-c38f301d948e.png)

**Comment by paul-k-pastvu** [comment]
> Добавили. Маркер кликабельный

А про мобильных пользователей думали?

**Comment by mkgrgis** [comment]
> Если быстро менять точку, то получается задумчиво

Странный сценарий. Если выставить центр карты в точку фотографа или художника, то зачем быстро менять точку по центру изображения? Задумался, поставил, скопировал координаты.

> А про мобильных пользователей думали?

Картография такого уровня на смартфоне всегда так себе.

**Comment by hutun** [comment]
> Если быстро менять точку, то получается задумчиво:
Задумчивость легко убмрается удалением ранее созданных bubble
http://retromap.ru/start2.php?071903_55.758116,37.599892

**Comment by hutun** [comment]
А про мобильных пользователей думали?

> А про мобильных пользователей думали?
Ранее в мобильной версии реакция на клик по карте была заблокирована. Сейчас убрали блокировку.
Не очень понимаю, зачем это нужно - в мобильной версии мы вообще сознательно убираем все прибамбасы, даже координаты центра не отображаются.

Вопрос: а как эти манипуляции с координатами будут использоваться на PastVu? Сейчас мы делаем вслепую - вроде как несложно, но не очень понятно, зачем

**Comment by mkgrgis** [comment]
> Вопрос: а как эти манипуляции с координатами будут использоваться на PastVu? Сейчас мы делаем вслепую - вроде как несложно, но не очень понятно, зачем

На PastVu есть поле ввода координат. Сейчас вводят только точку фотографа, но скоро можно будет вводить две координаты одна за другой. Вторая координата - задающий ракурс объект на центральной геометрической вертикальной оси. По второй координате возможна косвенная оценка максимальной глубины вида.

**Comment by hutun** [comment]
> На PastVu есть поле ввода координат. Сейчас вводят только точку фотографа, но скоро можно будет вводить две координаты одна за другой. Вторая координата - задающий ракурс объект на центральной геометрической вертикальной оси. По второй координате возможна косвенная оценка максимальной глубины вида.

Спасибо - наконец то прояснилось. Уверен, что на мобильнике мало кто будет это делать

**Comment by hutun** [comment]
Загрузили работу с координатной пипеткой в рабочую версию
http://retromap.ru/1419661

**Comment by paul-k-pastvu** [comment]
> Загрузили работу с координатной пипеткой в рабочую версию
> http://retromap.ru/1419661

Обновил новость (отдельную писать не стал).

**Comment by paul-k-pastvu** [comment]
> Спасибо - наконец то прояснилось. Уверен, что на мобильнике мало кто будет это делать

Есть ещё планшеты с Андроидом, скажем. И у нас есть участники, которые с планшета что-то делают.

**Comment by hutun** [comment]
> > Загрузили работу с координатной пипеткой в рабочую версию
> > http://retromap.ru/1419661
> 
> Обновил новость (отдельную писать не стал).

На мой взгляд, там нужно добавить, что для появления курсора нужно просто кликнуть в нужном месте на карте

**Comment by hutun** [comment]
> Есть ещё планшеты с Андроидом, скажем. И у нас есть участники, которые с планшета что-то делают. Мы же не массовый сайт, нам каждый важен и дорог.

По умолчанию на планшетах запускается полная версия - там пипетка работает

**Comment by paul-k-pastvu** [comment]
Подытожу текущий статус. Исходно в этой задаче было две темы:
1) отдавать точки и картинки с описаниями в RetroMap
2) показывать у себя исторические карты RetroMap

Реализован только п.1

По п.2. многое непонятно - как отбирать карты, как хранить пользовательские предпочтения и т.д. 
Полагаю, в рамках этой задачи нужно отработать только протокол взаимодействия - то есть взять любую карту RetroMap и на макете реализовать ее отображение в PastVu.

После этого нужно сделать перерыв на доработку нашего селектора карт (с прицелом на возможность отражения динамически подгружаемого списка карт с RetroMap или откуда-то ещё, от других возможных провайдеров).

Затем вернуться сюда или открыть новую задачу.

**Comment by paul-k-pastvu** [comment]
@mkgrgis - если согласен с итогом, обнови свой исходный коммент этим статусом (ну или своими словами).

**Comment by hutun** [comment]
1. Про наложение карт. На ретромап есть такой сервис. С моей точки зрения довольно бесполезный. Можно долго играться прозрачность слоёв, но пользы от этого немного.  Сравнение синхронизированных карт намного удобнее..
2. Выберите какую-либо карту для макета, например Хотевский план http://retromap.ru/081852. Больших проблем с доступом к тайлам размещенных на наших серверах карт не вижу.
3. Еще раз напомню, что некоторые карты, представленные на ретромап, размещены не на наших серверах по договоренности с другими проектами. Иногда от них поступают жалобы на большое число обращений.
4. Будет трудно двигаться вперед, пока вы не определитесь с процедурой выбора карт.
5. На некоторых сайтах наши карты используются через фреймы. Пример (карта внизу):
http://hram-tver.ru/index.php/monastyri-i-podvorya/utrachennye-monastyri/2204-moskovskaya-obl-lotoshinskij-rajon-mikulino-tverskaya-gub-staritskij-uezd-mikhailo-arkhangelskij-mikulinskij-muzhskoj-monastyr
Знаю про нелюбовь многих к фреймам, но это  очень простое решение.

**Comment by paul-k-pastvu** [comment]
> 1. Про наложение карт. На ретромап есть такой сервис. С моей точки зрения довольно бесполезный. Можно долго играться с прозрачностью слоёв, но пользы от этого немного.  Сравнение синхронизированных карт намного удобнее..

Отнюдь. Мой пльзовательский опыт говорит об обратном. Опять же, важно понимать специфику работы участников PastVu - нам нужно не просто понять в уме, где что было, а выставитть на карте сразу множество точек и взаимно их увязать. Так что нам важна не просто синхронизация карт в целом, а точная синхронизация в конкретном месте.

Возьмем простой пример: http://retromap.ru/081852_0420092_55.761339,37.606222
Как видим, угол, на котором стоит маркер на OSM, сильно "уехал" относительно исторической карты (на целое здание). Если при этом городской ландшафт в этом месте сильно поменялся, то выставить точки по историческим трассам и контурам зданий становится проблематичным (а само совмещение, делаемое зачастую по не очень качественным картам, вызывает споры).

К слову, на сайте etomesto.ru есть очень полезный в этом отношении функционал - он предлагает для повышения точности совмещения в точке самому пользователю чуть-чуть поменять масштаб или сдвинуть фрагмент исторической карты. Это не сохраняется на сайте, но позволяет сделать нужный скриншот.

> 3. Еще раз напомню, что некоторые карты, представленные на ретромап, размещены не на наших серверах по договоренности с другими проектами. Иногда от них поступают жалобы на большое число обращений.

А это для меня новость. Наверное, нужно будет это спеиально обсуждать.

**Comment by hutun** [comment]
> К слову, на сайте etomesto.ru есть очень полезный в этом отношении функционал - он предлагает для повышения точности совмещения в точке самому пользователю чуть-чуть поменять масштаб или сдвинуть фрагмент исторической карты. Это не сохраняется на сайте, но позволяет сделать нужный скриншот.
ать.
Если речь идёт о скриншоте смещенных карт, то на ретромап можно отключить синхронизацию карт и сместить одну из карт. Для отключения синхронизации нужно кликнуть в верхнем меню хнак "=" между Левая карта = Правая карта.
Можно было бы заморозить смещение, но это утяжеляет программу

**Comment by kabalin** [comment]
Там опечатка - удвоенное `т` в слове координаты.

**Comment by hutun** [comment]
> Там опечатка - удвоенное `т` в слове координаты.

Спасибо за бдительность - поправили

**Comment by mkgrgis** [comment]
Резюме в первом комментарии добавлено. Если нет возражений можно закрывать общую тему и переходить в ветки конкретных проблем.

**Comment by paul-k-pastvu** [comment]
> > Это не сохраняется на сайте, но позволяет сделать нужный скриншот.
> 
> Если речь идёт о скриншоте смещенных карт, то на ретромап можно отключить синхронизацию карт и сместить одну из карт. Для отключения синхронизации нужно кликнуть в верхнем меню хнак "=" между Левая карта = Правая карта.
> Можно было бы заморозить смещение, но это утяжеляет программу

Да, об этом. Эх, RetroMap неисчерпаем как атом ;)
Замораживать смещение конечно не нужно. Но сохранять сведения в базу (какая карта, и какие фрагменты куда смещали), если ими частотно пользуются, было бы очень любопытно - можно было бы приделать к ним потом аналитику, чтобы узнавать, где какие карты совмещены неидеально, и м.б. "подтягивать" что-то для приближения к идеалу. Но это так, к слову, из серии абстрактных пожеланий.
