### ISSUE TITLE
News editor plugin: bug with the hyperlink button

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#198]
В редакторе новостей, при создании новости **первый** вызов кнопки для вставки гиперссылки очищает форму редактирования текста:

![image](https://user-images.githubusercontent.com/60163100/97062229-a611c600-15a2-11eb-9abc-14c64beb821f.png)

Повторный вызов отрабатывает корректно.

В поле "краткой версии" ошибка не возникает.

При редактировании ранее сохраненных новостей ошибка не возникает

**Comment by aeifn** [comment]
Скорее всего, проблема в плагине редактора  https://github.com/PastVu/pastvu/blob/cf30f6215f9d7ddcd0833362e0706a404ae14208/public/js/lib/jquery/plugins/redactor/redactor.min.js

**Comment by aeifn** [comment]
Решится при обновлении #289
