### ISSUE TITLE
Map attribution info overlaps reset coordinates button in editing mode | Информация о карте перекрывает кнопку обнулить координаты

### ISSUE THREAD

**Issue by kabalin** [PastVu/pastvu#205]
Reported at https://pastvu.com/news/151?hl=comment-2224048 This is in fact the issue with some other map types that have a long attribution text.

![Screenshot](https://user-images.githubusercontent.com/329780/97449920-14031800-192a-11eb-9379-06cf70a30d90.png)

**Comment by mkgrgis** [comment]
div с кнопкой обнуления и рамкой координат нужно приделать снизу от карты, а не в тот div, где карта. Видимость по событию должна понижать высоту карты. Ограничение по высоте должно быть в общем блоке карты, кнопки и поля. Может быть, проблема решится только через css.

**Comment by paul-k-pastvu** [comment]
Вроде бы починили, ошибка больше не воспроизводится. Можно закрывать.

**Comment by kabalin** [comment]
Красота! Это, если я не ошибаюсь, карта закрепилась на `z-index: 0` в 743b6e98b и все элементы интерфейса теперь всегда поверх.
