### ISSUE TITLE
When date range slider under map is setted in 2000, "nearest images" is shown without filtering / Когда слайдер дат установлен в "2000", блок "Ближайшие фото" отображается без фильтрации

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#223]
En: When date range slider under map is setted in 2000, "nearest images" is shown without filtering
Ru: Когда слайдер дат установлен в "2000", блок "Ближайшие изображения" отображается без фильтрации

![image](https://user-images.githubusercontent.com/60163100/97810232-7a1dd100-1c83-11eb-860c-16064c1a1fc9.png)

**Comment by kabalin** [comment]
Тоже самое когда оба слайдера установлены в 1826. Профиксил в #229 .
