### ISSUE TITLE
API keys storage / Хранилище ключей API

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#225]
Раз уж начался процесс генерации и выдачи ключей API для разичных сервисов, то, к.м.к., нужно:
1. Реализовать хранилище ключей API (в той же БД или отдельно)
2. Хранить ключи вместе с информацией - кто, когда и для кого сгенерировал ключ
3. Интерфейс для просмотра списка ключей и кнопка для вызова метода генерации нового ключа (с обновлением записи в логе)

----
Отдельный вопрос - сбор и хранение статистики по использованию ключей (они вообще используются? Как активно? Не слишком ли активно? Не нужно ли ввести лимиты?).

**Comment by mkgrgis** [comment]
> Сбор и хранение статистики по использованию ключей

В каком разрешении? Можно в одной из веток завести миллионы int UnixTime узлов для каждого вызова API с данным ключём. Или ежеминутно кидать количество или каждые 10 минут и т.д.

**Comment by paul-k-pastvu** [comment]
Это вопрос - как вообще принято хранить статистику обращений к сайту? Не в основной базе же, неверное?

С моей стороны это просто общий запрос администрирования - вот мы выдаем ключи, и нам интересно знать, они вообще используются? Как активно? Не слишком ли активно? Не нужно ли ввести лимиты?

**Comment by mkgrgis** [comment]
Статистику обращений в известных мне проектах накапливают для каждого обращения как очередь JSON в памяти. Другой поток раскладывает JSON в реляционную таблицу PostgreSQL единственным запросом SQL INSERT. На таблицу цепляют классическую аналитику по количеству на время/ip адрес, язык браузера и т. д.

**Comment by klimashkin** [comment]
Да, в основной базе логе не принято хранить.
Современные логгеры для ноды могут писать стрим куда угодно, у нас мы логи просто в файлы по старинке кладем, но обычно это идет куда-нибудь в elk, graylog, splunk и тому подобное.
У нас давно были планы поставить graylog в отдельном контейнере, сейчас можно еще смотреть на других.

Еще стоит отметить что мы присваиваем уникальный id каждому запросу на входе и потом логируем все методы с этим id насквозь, для трейсинга. Но сейчас спустя столько лет можно уже смотреть на Jaeger и Prometheus

**Comment by aeifn** [comment]
> Современные логгеры для ноды могут писать стрим куда угодно, у нас мы логи просто в файлы по старинке кладем, но обычно это идет куда-нибудь в elk, graylog, splunk и тому подобное.

Можно выводить логи попросту на stdout/stderr, тогда они будут доступны через docker logs.

**Comment by paul-k-pastvu** [comment]
Меня больше интересует вопрос хранения/генерации/перегенераци ключей, а также логирования этого процесса. 
Насколько он актуальный? Насколько понятна трудоемкость и вообще суть задачи?

**Comment by paul-k-pastvu** [comment]
> Да, в основной базе логи не принято хранить.
> Современные логгеры для ноды могут писать стрим куда угодно, у нас мы логи просто в файлы по старинке кладем, но обычно это идет куда-нибудь в elk, graylog, splunk и тому подобное.
> У нас давно были планы поставить graylog в отдельном контейнере, сейчас можно еще смотреть на других.
> 
> Еще стоит отметить что мы присваиваем уникальный id каждому запросу на входе и потом логируем все методы с этим id насквозь, для трейсинга. Но сейчас спустя столько лет можно уже смотреть на Jaeger и Prometheus

Наверное, в таком разрезе, вопрос сбора, хранения и показа статистики сайта в принципе - нужно выделять в общую отдельную задачу?

**Comment by kabalin** [comment]
Так как API ключей мы сейчас не выдаем (и полностью ушли от старой версии API), то задачу можно закрыть. Статистику использования API можно смотреть в Cloudflare. Логи докера конечно лучше централизовать, но это уже отдельной задачей (возможно с переходом на кубер связать).
