### ISSUE TITLE
Google map usability issue / Целесообразность использования Google карт

### ISSUE THREAD

**Issue by kabalin** [PastVu/pastvu#227]
At the moment any Google maps are rendered in development mode with notification that can't be even closed (it sits behind dimmed layer by the look of it):
![Screenshot](https://user-images.githubusercontent.com/329780/98126887-fbf14280-1ead-11eb-92e2-2d2be121396e.png)

I undertand it requires API key, which for the volume of map queries we expect will likely incure cost. But keeping unusable map not ideal either. We can hide it (using config setting) or remove it completely from the code.

**Comment by kabalin** [comment]
Related #131

**Comment by paul-k-pastvu** [comment]
В них бывает польза даже в таком режиме. Можем спросить сообщество.

**Comment by anvaruk** [comment]
ok, lets try and see if we can fit within $200 limit per month https://cloud.google.com/maps-platform/pricing
which one do we need?
![image](https://user-images.githubusercontent.com/2795267/98291068-73080300-1fa2-11eb-940c-e80d945ce052.png)

**Comment by kabalin** [comment]
We need "Maps JavaScript API" for this as far as I understand.

This will require changes in Google maps layer library to substitute the API key. Key ideally needs to be stored in the config file variable, so passing it via websocket will be needed (presumably using `takeInitData` call, this will require relevant changes `controllers/settings.js` also).

**Comment by mkgrgis** [comment]
≈28000 free gMap initialization per month and [different global changes](https://github.com/PastVu/pastvu/issues/227#issuecomment-722682811)? How popular is all of Google Maps from pastVu? Is anywhere any statistics, @klimashkin ?

**Comment by anvaruk** [comment]
if someone prepares the code , I will supply API key
gcloud console will show us how popular it is, and if $200 won't be enough we will setup non-profit account to increase this limit

the only problem is that if we go over the limit it will start charging my card)

**Comment by kabalin** [comment]
> the only problem is that if we go over the limit it will start charging my card)

Usage capping seems possible: https://developers.google.com/maps/faq#usage_cap

**Comment by paul-k-pastvu** [comment]
Google maps (mostly satellite images) is very useful in these regions, where OSM, Yandex maps, and Yandex satellite photos is provided low resolution and low detalisation.

**Comment by kabalin** [comment]
Хотя у них модель подсчета может отличаться от яндекса: `User interactions with the map, such as panning, zooming, or switching map layers, do not generate additional map loads.` (https://cloud.google.com/maps-platform/pricing/#request), может стоит попробовать с дневным лимитом $6.45 (чтобы не превысить $200 в мес) и посмотреть статистику запросов.
