### ISSUE TITLE
История действий с фотографией

### ISSUE THREAD

**Issue by klimashkin** [PastVu/pastvu#23]
Иметь возможность по каждой фотографии посмотреть список действий. Например.
01.01.2001 Загрузил Duche
01.01.2001 Отредактировал Duche
02.01.2001 Отредактировал Ilya
02.01.2001 Одобрил Ilya
и т.д.

**Comment by paul-k-pastvu** [comment]
IMHO, this is really closed?

**Comment by klimashkin** [comment]
Right, resolved in the beginning of 2014
