### ISSUE TITLE
Navigating to any site URL while being on Yandex or Google map results in error / Переход по любой ссылке внутри сайта при нахождении на карте Яндекс или Гугл ведет к ошибке.

### ISSUE THREAD

**Issue by kabalin** [PastVu/pastvu#231]
Per issue discussed on the forum, e.g. https://pastvu.com/news/149?hl=comment-2229725

```
Uncaught TypeError: Cannot read property 'bottomright' of undefined
    at i.onRemove (L.Yandex.js?__=__:57)
    at i.removeLayer (leaflet.js?__=__:5)
    at i.removeFrom (leaflet.js?__=__:5)
    at i.remove (leaflet.js?__=__:5)
    at i.remove (leaflet.js?__=__:5)
    at NewClass.localDestroy (map.js?__=__:545)
    at apply (lodash.js?__=__:495)
    at NewClass.wrapper [as destroy] (lodash.js?__=__:5383)
    at _moduleCliche.js?__=__:64
    at lodash.js?__=__:4970
```

Regression caused by #226 

Exception is thown on either of these lines (depending which Leaflet extension is in use):
https://github.com/PastVu/pastvu/blob/master/public/js/lib/leaflet/extends/L.Google.js#L64
https://github.com/PastVu/pastvu/blob/master/public/js/lib/leaflet/extends/L.Yandex.js#L57

**Comment by kabalin** [comment]
Patch will be ready soon.

**Comment by aeifn** [comment]
То же свойство, но с другим значением, продолжает использоваться тут https://github.com/PastVu/pastvu/blob/8ad60d7bc6327209aba67ea7d59bfadbea6a30c0/public/js/lib/leaflet/extends/L.Yandex.js#L43

**Comment by kabalin** [comment]
А там оно ошибки не вызывает (свойство присутствует). Честно сказать, вникать было некогда, может как раз в этом причина что копирайт исчезает при переключении обратно. Посмотрю на выходных.
