### ISSUE TITLE
External links does not work / Внешние ссылки не работают

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#243]
Где обнаружено: в разделе новостей
 ![photo_2020-11-08 22 52 30](https://user-images.githubusercontent.com/13631515/98482848-3132c300-2215-11eb-9ef4-c0fdb9835379.jpeg)

**Comment by aeifn** [comment]
Ссылки вида http://example.com/ не работают, а ссылки вида http://example.com/path работают.

**Comment by paul-k-pastvu** [comment]
Временно работает обходной маневр http://example.com/index.html (но, естественно, не везде).
