### ISSUE TITLE
Versioning | Система версионирования

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#245]
Хорошо бы вернуться к системе релизов и версионирования: https://github.com/pastvu/pastvu/releases

Тогда сборка в продакшн и обновления станут оптимальными и надежными, будет возможность быстрого отката к предыдущей версии.

Кстати, какая сейчас версия?

**Comment by kabalin** [comment]
+100500

**Comment by kabalin** [comment]
> Кстати, какая сейчас версия?

https://github.com/PastVu/pastvu/blob/master/package.json#L3

**Comment by aeifn** [comment]
По поводу continuous integration:
- надо написать тесты, если их нет, или найти и подключить, если они где-то существуют
По поводу сборки и деплоя:
- нужен автоматизатор сборки (если будут введены версии, то возможностей hub.docker.com будет не хватать (например, нужно билдить pastvu/nginx:tagversion на базе образа pastvu/pastvu:tagversion. 
Пока что среди кандидатов jenkins или собственная система автоматизации гитхаба.

**Comment by paul-k-pastvu** [comment]
Несколько вопросов:
1) Каков жизненный цикл кода? Я правильно понимаю, что для отдельных задач делаются бранчи, потом они кем-то мерджатся с мастером? Или просто отдельные коммиты в Мастер. Потом однажды из Мастера делается новая версия, которая уже деплоимтся на сайт. Так примерно?
2) В какой момент происходит накатывание кода на макет, где его можно тестировать? Сейчас - вручную, так?
3) Как понять на самом сайте, под какой версией он сейчас работает?
4) Есть ли каое-то событие, по которому можно понять, что версия попала на сайт? Или этот процесс пока что от ГитХаба отвязан?

**Comment by paul-k-pastvu** [comment]
Ещё вопросы по планированию работ:
1. На ГитХабе есть раздел Projects. Как я понимаю, там Канбан-доска. Насколько это нужно и удобно?
2. Задачам можно назначать Milestone. Нужно ли этим заморачиваться и как-то увязывать эти майлстоуны с номерами версий? Чтобы понимать, что в какую версию в итоге попало (Release Note там писать, ещё что-то)?

**Comment by mkgrgis** [comment]
В проектах нашего типа канбан нужен для тех задач, которые взяты в работу или имеют сверхвысокий приоритет. В нашем случае нет смысла полностью дублировать со статусами продвижения сводку проблем (issues).

**Comment by aeifn** [comment]
> Я правильно понимаю, что для отдельных задач делаются бранчи, потом они кем-то мерджатся с мастером? Или просто отдельные коммиты в Мастер. Потом однажды из Мастера делается новая версия, которая уже деплоится на сайт. Так примерно?

Да, именно. Бранчи используются, когда реализация требует ревью, а просто коммиты в мастер делаются, когда изменения очевидны.

> 2. В какой момент происходит накатывание кода на макет, где его можно тестировать? Сейчас - вручную, так?

Сборка происходит автоматически на hub.docker.com при каждом коммите в мастер. Обновление происходит вручную командой `docker service update --image pastvu/pastvu:latest pastvu_app_ru` для каждого сервиса из стека.

> 3. Как понять на самом сайте, под какой версией он сейчас работает?

Никак. Надо сделать вывод в шаблоне.

> 4. Есть ли каое-то событие, по которому можно понять, что версия попала на сайт? Или этот процесс пока что от ГитХаба отвязан?

Собственно, когда будет отлажено версионирование, по изменению номера версии.
Сейчас пока никак, накатывается вручную образ pastvu/pastvu:latest.

**Comment by aeifn** [comment]
Описание системы версионирования https://semver.org

**Comment by kabalin** [comment]
> надо написать тесты, если их нет, или найти и подключить, если они где-то существуют

Тестов нет (по крайней мере в этом репозитарии). Нужно выбрать фреймворк, и написать какой-то минимальный набор тестов (самое критическое), чтоб было от чего отталкиваться и дальше постепенно развивать (скажем вводить рекомендацию - “по возможности сопровождать каждый PR тестом”). JS я прежде не тестировал, но как я понимаю тут выбор невелик - чаще всего можно встретить [Jasmine](https://jasmine.github.io/), [Mocha](https://mochajs.org/) (зачастую используется с [Chai](https://www.chaijs.com/)), [QUnit](https://qunitjs.com/).

> Пока что среди кандидатов jenkins или собственная система автоматизации гитхаба.

GitHub Actions [бесплатная](https://github.com/features/actions#pricing-details) для Open Source и удобная в плане встраивания в проект. Jenkins тоже можно рассмотреть на перспективу: если много ресурсоемких тестов, как правило связанных с интерфейсом (Selenium webdriver, etc.), Jenkins может делать ночные сборки и деливери, а в GitHub Actions оставить небольшой набор тестов для проверки кода в PR. Ну или как посчитаете более приемлемым.

Начать можно с малого. Давайте запускать линтинг JS в каждом PR (и можно настроить условие что код нельзя мержить пока тест не пройдет без ошибок). Для этого нужно добавить workflow для node.js (https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs) и сделать в нем два шага: 
```
   - run: npm install
   - run: npm test
```
Для последнего вот вам PR в помощь: https://github.com/PastVu/pastvu/pull/253

**Comment by aeifn** [comment]
> В проектах нашего типа канбан нужен для тех задач, которые взяты в работу или имеют сверхвысокий приоритет. В нашем случае нет смысла полностью дублировать со статусами продвижения сводку проблем (issues).

Сделал канбан-проект https://github.com/PastVu/pastvu/projects/3

**Comment by aeifn** [comment]
> Jenkins тоже можно рассмотреть на перспективу: если много ресурсоемких тестов, как правило связанных с интерфейсом (Selenium webdriver, etc.), Jenkins может делать ночные сборки и деливери

Я установил Jenkins: https://jenkins.pastvu.com/
Могу выслать доступ по запросу.

**Comment by klimashkin** [comment]
GitHub Actions было бы вполне достаточно пока

**Comment by kabalin** [comment]
> > 1. Как понять на самом сайте, под какой версией он сейчас работает?
> 
> Никак. Надо сделать вывод в шаблоне https://github.com/PastVu/pastvu/blob/4522e2e4a418458f29e5d463eaa5f850efcc5b20/views/module/common/foot.pug

![Screenshot](https://user-images.githubusercontent.com/329780/98919825-3454da00-24c7-11eb-805b-cb074868f4f4.png)

В консоли можно увидеть еще. Только на продакшене аглифаинг искажает эту строку, надо как-то добавить исключение.

**Comment by aeifn** [comment]
У меня готов скрипт деплоя в продакшн, который принимает `TAG` — версию контейнера:

```
#!/bin/bash
set -x

export NODE_ID=$(docker info -f '{{.Swarm.NodeID}}')

export DOMAIN=pastvu.com

export TAG=latest
export EN_TAG=en

export CONFIG=./config/prod.js
export CONFIG_TAG=$(shasum $CONFIG -a 512 | cut -c1-16)

docker node update --label-add pastvu.pastvu-data=true $NODE_ID
docker stack deploy \
	-c pastvu.yml \
	-c prod.yml \
	-c traefik.yml \
	pastvu
```

Осталось сделать при помощи GitHub Actions, чтобы при выставлении в репозитории тега `vX.Y.Z` собирались образы `pastvu/pastvu:vX.Y.Z`, `pastvu/pastvu:en-vX.Y.Z` и `pastvu/nginx:vX.Y.Z`. А затем запускалась доставка.

**Comment by kabalin** [comment]
Это очень хорошая практика по тэгу пересобирать продакшн. Еще можно стейжинг пересобирать при любом изменении в мастере (после мержинга как правило), чтобы он всегда отражал текущий статус проекта.

**Comment by aeifn** [comment]
Тема CI/CD объемная и долгосрочная, поэтому вынесена в проект: https://github.com/PastVu/pastvu/projects/3

**Comment by aeifn** [comment]
Когда в мастер добавляется тег `v*.*.*`, он указывает на мастер ветку, и проходит мимо ветки en.
Нужно версионировать `en` ветку: слияние `master` в `en` сразу после коммита с тэгом `vA.B.C` называть `vA.B.C-en`.
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13631515/99345296-04c91780-28a3-11eb-91a1-b309e5558eb0.png">

Тегировать можно с помощью расширенной версии `automerge`: https://github.com/PastVu/pastvu/blob/master/.github/workflows/en-automerge.yml. При пуше в мастер скрипт будет проверять, стоит ли тег на текущем коммите, и если стоит, то мерж-коммит будет тегирован соответствующей версией с суффиксом '-en'.

Ожидаемый результат:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13631515/99346744-6dfe5a00-28a6-11eb-8047-f9845122b1ca.png">

**Comment by aeifn** [comment]
> ![Screenshot](https://user-images.githubusercontent.com/329780/98919825-3454da00-24c7-11eb-805b-cb074868f4f4.png)
> 
> В консоли можно увидеть еще. Только на продакшене аглифаинг искажает эту строку, надо как-то добавить исключение.

Выключается тут: https://github.com/PastVu/pastvu/blob/341236c985459914861befaa207fff31341aed5f/build.js#L65

Related to https://github.com/PastVu/pastvu/issues/275

**Comment by kabalin** [comment]
> Тегировать можно с помощью расширенной версии `automerge`: https://github.com/PastVu/pastvu/blob/master/.github/workflows/en-automerge.yml. При пуше в мастер скрипт будет проверять, стоит ли тег на текущем коммите, и если стоит, то мерж-коммит будет тегирован соответствующей версией с суффиксом '-en'.

Если только по тэгу надо запускать, то можно ограничить условие `on`:
```
on:
  push:
    branches:
      - master
    tags:
      - v*
```
Еще можно только по событию релиз что-нибудь запускать (продакшн билд к примеру?): 
```
on:
  release:
...
```

**Comment by aeifn** [comment]
> Если только по тэгу надо запускать, то можно ограничить условие `on`:

Удобнее в продакшн запускать по тегу, а не по релизу, потому что к релизу нужно писать аннотацию, а это занимает время. Главное, что обеспечивают теги — возможность быстрого предсказуемого отката.

Сегодня перевел продакшн на теги, соответствующие версиям:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/13631515/99408616-79cb3a00-2901-11eb-99a3-79f630d50d4c.png">

Сборка осуществлялась sh-скриптом https://github.com/PastVu/pastvu/blob/master/build.sh

**Comment by aeifn** [comment]
> Еще можно стейжинг пересобирать (в будущем) при любом изменении в мастере (после мержинга как правило), чтобы он всегда отражал текущий статус проекта.

Это как раз оказалось реализовано в первую очередь: https://github.com/PastVu/pastvu/blob/master/.github/workflows/docker-image.yml. (на сервере стоит autoredeploy)
