### ISSUE TITLE
Db sample link unvalid / Ссылка на сэмпл бд невалидна

### ISSUE THREAD

**Issue by leshchevds** [PastVu/pastvu#248]
Link to [db sample](https://varlamov.me/pastvu/github/pastvu.tar.gz) in [README.md](https://github.com/PastVu/pastvu/blob/master/README.md) returns 404

**Comment by aeifn** [comment]
Ссылка была обновлена в коммите https://github.com/PastVu/pastvu/commit/d39cb24c0fe7d22850719611cfe5b894367993ad
