### ISSUE TITLE
Yandex map errors (API-key required) / Ошибки карт Яндекса (требуется ключ API)

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#251]
Вчера
![image](https://user-images.githubusercontent.com/60163100/98824782-bf40c080-2444-11eb-94b7-d1fd1df44481.png)

Сегодня
![image](https://user-images.githubusercontent.com/60163100/98825121-2cecec80-2445-11eb-9f2c-40df1f92ebc4.png)

и 

![image](https://user-images.githubusercontent.com/60163100/98825171-3c6c3580-2445-11eb-8834-032d3553f5c0.png)

**Comment by aeifn** [comment]
Хорошо бы определить действие, которое вызывает красные ошибки.

**Comment by paul-k-pastvu** [comment]
Вот прямо сейчас: Яндекс просто не отдал тайл

https://core-sat.maps.yandex.net/tiles?l=sat&v=3.741.0&x=65536&y=65536&z=17&lang=ru_RU
![image](https://user-images.githubusercontent.com/60163100/98829780-aa672b80-244a-11eb-9f0d-c1313803180f.png)

**Comment by paul-k-pastvu** [comment]
А unchecked runtime ругается на всё подряд:
![image](https://user-images.githubusercontent.com/60163100/98830018-f5813e80-244a-11eb-9063-caea1a4aa68e.png)

**Comment by paul-k-pastvu** [comment]
При выборе любой другой карты кроме Яндекса, никаких ошибок не возникает

**Comment by paul-k-pastvu** [comment]
в русской и английской версиях ошибки отличаются. В русской так:
![image](https://user-images.githubusercontent.com/60163100/98830411-6fb1c300-244b-11eb-94f8-cc925941e1be.png)

**Comment by aeifn** [comment]
Ключ получен. Его нужно подставить в этот запрос https://github.com/PastVu/pastvu/blob/fa30cc453c06c7a9b466d36b5d636f264a825e5b/public/js/lib/leaflet/extends/L.Yandex.js#L5
следующим образом:
`https://api-maps.yandex.ru/2.1/?apikey=ваш API-ключ&lang=ru_RU`
(https://yandex.ru/dev/maps/jsapi/doc/2.1/dg/concepts/load.html/)

**Comment by kabalin** [comment]
Схожая задача #227. Возьмусь сделать обе (ключ надо будет указывать через конфиг, хардкодить в модуль его не стоит).

> Вчера
> ![image](https://user-images.githubusercontent.com/60163100/98824782-bf40c080-2444-11eb-94b7-d1fd1df44481.png)

А что такое sovetnik.min.js - это у вас расширение браузера для Яндекса? Оно не может быть причиной ошибки `unchecked runtime`?

**Comment by paul-k-pastvu** [comment]
> Схожая задача #227. Возьмусь сделать обе (ключ надо будет указывать через конфиг, хардкодить в модуль его не стоит).
> 
> > Вчера
> > ![image](https://user-images.githubusercontent.com/60163100/98824782-bf40c080-2444-11eb-94b7-d1fd1df44481.png)
> 
> А что такое sovetnik.min.js - это у вас расширение браузера для Яндекса? Оно не может быть причиной ошибки `unchecked runtime`? Попробуйте его убрать (или запретить) и посмотреть останется ли ошибка.

Это https://sovetnik.market.yandex.ru/app/settings/
Отключил, ошибка осталась. Яндекс-браузер.

**Comment by kabalin** [comment]
@aeifn интересно узнать, какая статистика запросов карт (из интерфейса яндекса где ключ). Там кажется 25тыс запросов в день ограничение еще, если не ошибаюсь, для бесплатного использования - не превышаем?

**Comment by aeifn** [comment]
> @aeifn интересно узнать, какая статистика запросов карт (из интерфейса яндекса где ключ). Там кажется 25тыс запросов в день ограничение еще, если не ошибаюсь, для бесплатного использования - не превышаем?

Это вопрос к @anvaruk

**Comment by anvaruk** [comment]
> @aeifn интересно узнать, какая статистика запросов карт (из интерфейса яндекса где ключ). Там кажется 25тыс запросов в день ограничение еще, если не ошибаюсь, для бесплатного использования - не превышаем?

![image](https://user-images.githubusercontent.com/2795267/100109704-0165fb00-2e64-11eb-9981-39b5fe883b7a.png)
