### ISSUE TITLE
Source field placeholder text update | Обновление текста-заполнителя для поля "Источник"

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#252]
EN: Proposed change of the Source field placeholder text ():

- old text: "`If you know the photo source (link, a book, etc.), necessary to specify it here`"
- new text: 
  - for type ="photo": "`Be sure to indicate the photo source (link, a book, scanned photo from your personal archive, etc.)`"
  - for type ="painting": "`Be sure to indicate the image source (link, a book, scanned photo from your personal archive, etc.)`"
![image](https://user-images.githubusercontent.com/60163100/98827012-6cb4d380-2447-11eb-9adb-f66b65316bfc.png)

----
RU: Предлагается поменять текст-заполнитель для поля "Источник":
- вместо "`Если вам известен источник фотографии (ссылка, книга и т.д.) обязательно укажите его здесь`" 
- написать 
  - для типа ="фото": "`Обязательно укажите источник фотографии (ссылка, книга, скан фото из личного архива и т.д.)`"
  - для типа ="картина": "`Обязательно укажите источник изображения (ссылка, книга, скан фото из личного архива и т.д.)`"
(https://pastvu.com/news/141?hl=comment-2229933)

![image](https://user-images.githubusercontent.com/60163100/98826100-5b1efc00-2446-11eb-9eec-0582298c73c6.png)

**Comment by paul-k-pastvu** [comment]
Консенсус модераторов имеется.

**Comment by kabalin** [comment]
Не уверен насчет `"Be sure to indicate the photo source (link, a book, scanned photo from your personal archive, etc.)"` 

Альтернативы:
* `"You must specify the photo source (link, a book, scanned photo from your personal archive, etc.)"`
* `"Make sure you specified the photo source (link, a book, scanned photo from your personal archive, etc.)"`

**Comment by paul-k-pastvu** [comment]
"You must" наверное только в полиции могут сказать, и то не всегда. В остальном доверюсь тем, кто понимает язык лучше.
Мне тут говорят, что "Be sure" - правильнее всего.
