### ISSUE TITLE
Error message about "Mixed Content" for MTB map

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#266]
Error message about "Mixed Content" for MTB map:

![image](https://user-images.githubusercontent.com/60163100/99291228-83e13000-2850-11eb-97d3-88f9de387d72.png)

**Comment by aeifn** [comment]
@mkgrgis, у них есть где-то https-сервер? Если нет, то снова поднимаем прокси :)

**Comment by mkgrgis** [comment]
Увы, нет. Нужен прокси.
