### ISSUE TITLE
Show site version in production

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#275]
Выводить в консоль версию **собранного** приложения, как здесь: https://github.com/PastVu/pastvu/issues/245#issuecomment-725949475

![](https://user-images.githubusercontent.com/329780/98919825-3454da00-24c7-11eb-805b-cb074868f4f4.png)

Нужно отображать раздельно версию как фронтенда, так и бэкенда, так как фронтенд обслуживается отдельным контейнером.

**Comment by kabalin** [comment]
В данном случае показывает back-end ([тут](https://github.com/PastVu/pastvu/blob/master/public/js/module/appMain.js#L179) из массива `settings` который сервер отдает при инициализации. Для версии фронтэнда билд может добавлять файл `public/js/version.json` который в свою очередь (при его наличии) appMain.js может использовать для показа версии фронтэнда в консольном логе.

**Comment by aeifn** [comment]
На самом деле, эта фича нужна для модераторов/администраторов сайта, чтобы они могли отслеживать, какие фичи уже в продакшене, а какие еще нет. Сисадмин и так видит, какие точно контейнеры запущены, а скрипт сборки образа сверяет версии.
Можно, действительно, выводить версию в шаблон https://github.com/PastVu/pastvu/blob/master/views/module/common/foot.pug и только из P.settings.

**Comment by paul-k-pastvu** [comment]
Меня устроит, если я просто на страничке https://staging.pastvu.com/admin смогу это увидеть
