### ISSUE TITLE
regionCheck frontend error / ошибка на фронтенде в regionCheck

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#285]
Возникает при нажатии на карту, воспроизводится в версии 1.3.2 и в мастере.

Локация: https://github.com/PastVu/pastvu/blob/a3e79baafad1424af04cbed20cebd332e841295a/public/js/module/admin/regionCheck.js#L260
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13631515/99534158-0c2e1500-29b8-11eb-818b-0f1979612a61.png">

**Comment by kabalin** [comment]
Вообще-то это когда запрос к nominatim вернул fail - я не могу воспроизвести, но могу добавить проверку наличия свойства responseJSON.

**Comment by kabalin** [comment]
Что там в табе "Network" при нажатии на карту? Как ответ от nominatim выглядит, покажите если не трудно?

**Comment by kabalin** [comment]
Если просто в браузере открыть https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=52.5487429714954&lon=-1.81602098644987 ошибок нет?

**Comment by aeifn** [comment]
> Что там в табе "Network" при нажатии на карту? Как ответ от nominatim выглядит, покажите если не трудно?

Это ошибка, специфичная для Safari (при отключении `Prevent cross-site tracking` сохраняется). В google-chrome все работает. 
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13631515/99544308-333f1380-29c5-11eb-8d42-d97ab150b4d8.png">

> Если просто в браузере открыть https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=52.5487429714954&lon=-1.81602098644987 ошибок нет?

Отдельно запрос успешно возвращает нужный json.

**Comment by kabalin** [comment]
Можете попробовать добавить параметр `async: true` в ajax запрос?
https://github.com/PastVu/pastvu/blob/a3e79baafad1424af04cbed20cebd332e841295a/public/js/module/admin/regionCheck.js#L254

**Comment by aeifn** [comment]
> Можете попробовать добавить параметр `async: true` в ajax запрос?
> 
> https://github.com/PastVu/pastvu/blob/a3e79baafad1424af04cbed20cebd332e841295a/public/js/module/admin/regionCheck.js#L254

Это не меняет ситуацию. Вот лог объекта jqXHR:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/13631515/99556445-94211880-29d2-11eb-9c49-8b754f6d7f77.png">

**Comment by aeifn** [comment]
> Можете попробовать добавить параметр `async: true` в ajax запрос?
> 
> https://github.com/PastVu/pastvu/blob/a3e79baafad1424af04cbed20cebd332e841295a/public/js/module/admin/regionCheck.js#L254

А вот указание `async: false` решает проблему для safari.

**Comment by paul-k-pastvu** [comment]
Не только Сафари. Вот Яндекс-браузер, причем только в английском интерфейсе:

![image](https://user-images.githubusercontent.com/60163100/99586173-66e76100-29f8-11eb-9e46-479a345e763c.png)

**Comment by kabalin** [comment]
Воспроизвел проблему:
<img width="883" alt="Screenshot 2020-11-18 at 23 12 24" src="https://user-images.githubusercontent.com/329780/99599719-dad33a80-29f3-11eb-8660-30281c125ef1.png">

Чтобы найти причину...
Leaflet/Leaflet#7255

Там патч уже есть к Leaflet, давайте дождемся релиза наверно.

**Comment by kabalin** [comment]
Хотя нет, сейчас будет простой патч :)

**Comment by kabalin** [comment]
> Не только Сафари. Вот Яндекс-браузер, причем только в английском интерфейсе:

Проверьте потом после того как патч в продакшн уйдет, останется проблема или нет.

**Comment by aeifn** [comment]
@kabalin, спасибо, ушло в прод с тегом 1.3.4: https://github.com/PastVu/pastvu/releases/tag/v1.3.4
