### ISSUE TITLE
Add link to commit, from which docker-image was built / Добавить ссылку на коммит, по которому был собран докер-образ

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#286]
<img width="1552" alt="Screenshot 2020-11-18 at 16 31 32" src="https://user-images.githubusercontent.com/13631515/99536641-b0658b00-29bb-11eb-8547-0d034e474085.png">

Щелкаем на версию сайта и попадаем на соответствующий текущей версии коммит в репозитории.
Хеш коммита брать из окружения, он будет подставляться в докерфайле при сборке, или записываться в файл /version

**Comment by kabalin** [comment]
Брать из переменной окружения хорошая идея.

**Comment by aeifn** [comment]
Это, пожалуй, лишняя задача.
