### ISSUE TITLE
Update editor mode / Обновить модуль редактора

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#289]
Не обновлялся с 2014 года, нужен для реализации #288 

https://github.com/PastVu/pastvu/blob/master/public/js/lib/jquery/plugins/redactor/redactor.min.js

**Comment by kabalin** [comment]
https://github.com/PastVu/pastvu/issues/288 реализовывать не будем, но обновить редактор все равно не помешает.

**Comment by kabalin** [comment]
Redaktor needs to be replaced with open source alternative (https://imperavi.com/redactor/license/)

**Comment by kabalin** [comment]
Looks like [Trumbowyg](https://github.com/Alex-D/Trumbowyg) is a nice alternative with similar minimalistic approach and functionality.

Redactor:
![image](https://user-images.githubusercontent.com/329780/210549992-d4a24959-31ba-4534-8858-b7e748812e23.png)

Trumbowyg: 
![image](https://user-images.githubusercontent.com/329780/210550504-c9fdb124-9be4-4297-8064-fd77844d1a7e.png)

**Comment by paul-k-pastvu** [comment]
Сходу не вижу там только кнопки для вставки табличек.

**Comment by kabalin** [comment]
> Сходу не вижу там только кнопки для вставки табличек.

Да, для таблицы нужен плагин https://alex-d.github.io/Trumbowyg/demos/#plugins-table

**Comment by kabalin** [comment]
Есть еще такой https://summernote.org/ (https://github.com/summernote/summernote) может немного функциональнее, из интересных фич: "Saves images directly in the content of the field using base64 encoding, so you don't need to implement image handling at all"

**Comment by paul-k-pastvu** [comment]
> Saves images directly in the content of the field using base64 encoding

Не уверен, что это плюс.

**Comment by paul-k-pastvu** [comment]
> для таблицы нужен плагин

Это, собственно, не так часто нужно. Но хорошо, что плагин есть.

**Comment by kabalin** [comment]
![image](https://user-images.githubusercontent.com/329780/210771295-fd1ccc53-05f6-4306-b0af-a89b0482a68d.png)

С плагинами:
- Colours (цвет текста)
- Cleanpaste (очистка при вставке от нежелательных тэгов)
- Resizeimg (изменение размера картинки путем перетаскивания за угол)
- Table (таблица)
- Fontsize (размер шрифта)
- Indent (отступ)
- Noember (переделывает ссылку для embed через сервис noembed, скажем youtube ссылку заменяет на видео)

Что-то еще может пригодится?
