### ISSUE TITLE
Unchecked runtime.lastError: the message port closed before a response was received

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#295]
В галереях и на странице описаний по-прежнему вылезает ошибка:
![image](https://user-images.githubusercontent.com/60163100/99880421-3e43af00-2c24-11eb-8d63-b3a4c4074e39.png)

Видимо, из-за этого страницы загружаются не с первого раза.

Яндекс-браузер. Расширение "Советник" на самом деле отключено.

_Originally posted by @paul-k-pastvu in https://github.com/PastVu/pastvu/issues/291#issuecomment-731591488_

**Comment by aeifn** [comment]
@paul-k-pastvu, а если ради чистоты эксперимента советника временно _удалить_, ошибка будет воспроизводиться?

Возникает ли ошибка на макете?

**Comment by paul-k-pastvu** [comment]
> Возникает ли ошибка на макете?

Да.

**Comment by paul-k-pastvu** [comment]
> @paul-k-pastvu, а если ради чистоты эксперимента советника временно _удалить_, ошибка будет воспроизводиться?
> 
> Возникает ли ошибка на макете?

Нашел как отключить, эта ошибка ушла, но основная ошибка остается:

![image](https://user-images.githubusercontent.com/60163100/99888901-5ab20c80-2c61-11eb-8926-327052b5b7dd.png)

Причем только на картах Яндекса, что характерно.

**Comment by paul-k-pastvu** [comment]
В Edge, который теперь тоже на Хромиуме, ошибки выглядят иначе:

![image](https://user-images.githubusercontent.com/60163100/99889001-4c182500-2c62-11eb-9742-d96d6a6a1a79.png)

**Comment by paul-k-pastvu** [comment]
В рассылке модераторов пишут, что антивирус начал ругаться на открытые Яндекс-карты (на самих Я-картах, отдельно, ничего плохого не происходит):

![image](https://user-images.githubusercontent.com/60163100/99889275-7f5bb380-2c64-11eb-8492-222d8c4b40d3.png)

**Comment by paul-k-pastvu** [comment]
Вот так ругается вообще в галерее:

![image](https://user-images.githubusercontent.com/60163100/99890509-1890c700-2c71-11eb-8880-a395ec8a6554.png)


Ссылка на дебаггер дает строку:

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create','UA-42731294-1','auto');ga('require','displayfeatures');

**Comment by kabalin** [comment]
Пишут что в большинстве случаев причина в установленных расширениях: https://stackoverflow.com/questions/54126343/how-to-fix-unchecked-runtime-lasterror-the-message-port-closed-before-a-respon

> (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create','UA-42731294-1','auto');ga('require','displayfeatures');

Это скрипт аналитики рекомедуют обновить: #299

**Comment by kabalin** [comment]
> В Edge, который теперь тоже на Хромиуме, ошибки выглядят иначе:
> 
> ![image](https://user-images.githubusercontent.com/60163100/99889001-4c182500-2c62-11eb-9742-d96d6a6a1a79.png)

Это другая история, это Edge запретил данным ресурсам использовать [storage](https://developer.mozilla.org/en-US/docs/Web/API/Storage) для хранения данных (защита от трекинга).

**Comment by kabalin** [comment]
@paul-k-pastvu Ошибка все еще есть?

**Comment by paul-k-pastvu** [comment]
В Edge выглядит так: 
![image](https://user-images.githubusercontent.com/60163100/194098944-8c54e9e1-5df4-4faa-8595-1746a5b1cce4.png)

**Comment by kabalin** [comment]
Сообщения защита от трекинга наблюдаемые в консоли не имеют отношения к приложению. Думаю можно закрыть тикет.
