### ISSUE TITLE
Move periodic mail sending to a separate module / Вынести периодическую отправку почты в отдельный модуль

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#296]
Сейчас при репликации приложения (запуске более одного контейнера за лоадбалансером), каждый контейнер «по крону» рассылает почтовые уведомления, что приводит к дублирующимся сообщениям.

Нужно вынести периодическую отправку почты в отдельный нереплицируемый инстанс, который будет работать глобально.

**Comment by aeifn** [comment]
В идеале вынести notifier в отдельный модуль и запускать его:
`node bin/run --script notifier.js`

Но ./controllers/subscr.js импортируется (и, значит, запускается конвейер отправки) из нескольких других файлов, а не только из app.js.

**Comment by paul-k-pastvu** [comment]
А, так вот в чем причина дублирующихся уведомлений в почте!
