### ISSUE TITLE
Migrate to Google Analytics 4

### ISSUE THREAD

**Issue by kabalin** [PastVu/pastvu#299]
Current implementation of Google analytics is regarded as outdated, upgrade to gtag.js is required:
https://developers.google.com/analytics/devguides/collection/upgrade

https://github.com/PastVu/pastvu/blob/cf30f6215f9d7ddcd0833362e0706a404ae14208/views/app.pug#L14

While working on this task it might be a good idea to supply analytics ID from configuration variable, rather having it hardcoded.

**Comment by anvaruk** [comment]
can we implement Google Tag manager instead? so we can inject any other analytics e.g Yandex Metrica
last time we tried something did not work correctly, so we reverted

**Comment by kabalin** [comment]
Universal Analytics will [stop working on 01/07/23](https://support.google.com/analytics/answer/11583528), so we have to migrate to Google Analytics 4 before this date.
