### ISSUE TITLE
Migrations on every start of app?

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#303]
Нужна ли здесь эта строчка?

https://github.com/PastVu/pastvu/blob/87d2eef8fbb3b00c503e53efe60313064044a482/app.js#L27

**Comment by paul-k-pastvu** [comment]
> Нужна ли здесь эта строчка?
> https://github.com/PastVu/pastvu/blob/87d2eef8fbb3b00c503e53efe60313064044a482/app.js#L27

это к @klimashkin вопрос?

**Comment by kabalin** [comment]
Cross ref https://github.com/PastVu/pastvu/pull/307#issuecomment-733322386
