### ISSUE TITLE
Error with language indicator and structures of image and gallery

### ISSUE THREAD

**Issue by mkgrgis** [PastVu/pastvu#311]
Firefox, Ubuntu.

![изображение](https://user-images.githubusercontent.com/41448637/100579133-b1b88100-32f4-11eb-85d4-4729e1d8a13d.png)

Similar message https://pastvu.com/news/148?hl=comment-2247387

Update isn't helpful for https://pastvu.com/p/1221060.

In gallery https://pastvu.com/ps/feed there is no string of region with no error in console
![изображение](https://user-images.githubusercontent.com/41448637/100579445-53d86900-32f5-11eb-9bbf-d91d379097d9.png)

**Comment by aeifn** [comment]
Ув. Михаил, пришлите, пожалуйста, данные экрана "Storage" на панели отладки, кроме сессии:
<img width="1440" alt="Screenshot 2020-11-30 at 10 25 39" src="https://user-images.githubusercontent.com/13631515/100580188-90589480-32f6-11eb-8ca5-fc6e296f8017.png">

**Comment by aeifn** [comment]
Также: оказывает ли эффект включение галочки "Выключить кэш" на экране Сеть?
<img width="1440" alt="Screenshot 2020-11-30 at 11 09 45" src="https://user-images.githubusercontent.com/13631515/100584168-c731a900-32fc-11eb-919f-f57d507e2389.png">

**Comment by mkgrgis** [comment]
"Выключить кэш" было проставлено. Когда пусто тоже самое. 
В хранилищах вот так
![изображение](https://user-images.githubusercontent.com/41448637/100584995-e7ae3300-32fd-11eb-81e3-970fe7f6e3aa.png)

**Comment by aeifn** [comment]
@mkgrgis спасибо! Исправлено коммитами:
https://github.com/PastVu/nginx/commit/4f3c77a68c45cd5017997d49fa7469c1f4f5b144
https://github.com/PastVu/nginx/commit/6a7cf41075215f498550b949a21eb9be2b10129f

Сейчас все должно работать, проверьте, пожалуйста.

**Comment by mkgrgis** [comment]
Проблем из первого сообщения не выявлено.

**Comment by aeifn** [comment]
> Проблем из первого сообщения не выявлено.

Спасибо! Если еще что-то [в релизе](https://github.com/PastVu/pastvu/releases/tag/v1.3.5) обнаружится, пишите!
