### ISSUE TITLE
English site version login stats info contains extra words / Лишние слова в описании статистики в английской версии сайта

### ISSUE THREAD

**Issue by kabalin** [PastVu/pastvu#317]
![Screenshot](https://user-images.githubusercontent.com/329780/101002772-014ab700-3558-11eb-9582-25bddb1ed94b.png)

Must be a problem with plural form handling.

**Comment by aeifn** [comment]
Text is generated here:

https://github.com/PastVu/pastvu/blob/cad651c176722bc6ba44c7802f3d0702b3209853/public/js/module/main/bottomPanel.js#L270-L287

**Comment by kabalin** [comment]
> Text is generated here:

That looks different to this:
https://github.com/PastVu/pastvu/blob/master/public/js/module/main/bottomPanel.js#L278

Also spotted typo here: https://github.com/PastVu/pastvu/blob/cad651c176722bc6ba44c7802f3d0702b3209853/public/js/module/main/bottomPanel.js#L26

**Comment by kabalin** [comment]
Issue like this demonstrates a good reason for #257 (i.e. plural form ending generation code could be delegated to lang tool).
