### ISSUE TITLE
Region attribution issue in different lingual interfaces after adding of a new region

### ISSUE THREAD

**Issue by mkgrgis** [PastVu/pastvu#319]
If it was adding of new region, RU interface don't show new region during a long time (hours). For ex. Firefox, Linux Fedora (not smartphone configuration).
Sample situation with https://pastvu.com/p/267920 and https://pastvu.com/ps?f=r!7396
EN
![изображение](https://user-images.githubusercontent.com/41448637/101183253-5376ff80-3660-11eb-9e4f-7ac6f7a1eee9.png)
RU
![изображение](https://user-images.githubusercontent.com/41448637/101183290-6093ee80-3660-11eb-8a77-ea1155af342f.png)

**Comment by paul-k-pastvu** [comment]
1) Нужно проверить на других регионах (старых и новых) и в других браузерах.  А также для фото с координатами.
Лично я (Win10, Chrome) такой проблемы не наблюдаю.
2) Судя про запятой после "Останкино", новый регион есть, но почему-то не отображается (либо уходит под нижележащий элемент). Посмотрите html-код в режиме разработчика.

**Comment by paul-k-pastvu** [comment]
@aeifn - может ли это быть связано с куками и репликацией?

**Comment by mkgrgis** [comment]
> Судя про запятой после "Останкино", новый регион есть, но почему-то не отображается (либо уходит под нижележащий элемент).

На RU ссылка https://pastvu.com/ps?f=r!7396 вела вникуда за указанное время, выводя на всемирный список фото.

**Comment by aeifn** [comment]
> If it was adding of new region, RU interface don't show new region during a long time (hours). For ex. Firefox, Linux Fedora (not smartphone configuration).

Ув. @mkgrgis, пожалуйста, опишите по шагам, как воспроизвести проблему.

Воспроизводится ли проблема в тестовом окружении (https://pastvu.bhyve.cloud admin/admin)?

**Comment by paul-k-pastvu** [comment]
Боюсь, что @mkgrgis сам не сможет воспроизвести проблему. 
Было так: я по его заявке создал новый регион. И я этот регион у себя нормально везде вижу. А @mkgrgis - нет (но только в русском языке). 

И более того - этот регион у него не отображался ни в дереве регионов, ни под фото. И даже прямая ссылка на галерею не сработала.

**Comment by paul-k-pastvu** [comment]
@mkgrgis, сейчас всё нормально, или нет? Была ли попытка очистить кеш сайта или перелогиниться, и если да, то помогла ли?

**Comment by aeifn** [comment]
Обнаружены следующие важные различия в ru и en версиях, которые, видимо, и служат причиной задержки в реплицированной русской версии:

<img width="1552" alt="Screenshot 2020-12-06 at 00 53 03" src="https://user-images.githubusercontent.com/13631515/101266178-98cd2700-375d-11eb-91e9-ba7ea9d1c1e0.png">
<img width="1552" alt="Screenshot 2020-12-06 at 00 53 21" src="https://user-images.githubusercontent.com/13631515/101266179-9a96ea80-375d-11eb-9038-5bcf8d6919ec.png">
<img width="1552" alt="Screenshot 2020-12-06 at 00 52 47" src="https://user-images.githubusercontent.com/13631515/101266180-9b2f8100-375d-11eb-9cf2-40b19ae5149a.png">

**Comment by mkgrgis** [comment]
> Была ли попытка очистить кеш сайта или перелогиниться, и если да, то помогла ли?

Попытка была, результата не было.
