### ISSUE TITLE
Add "More" button into "last comments" pane / Кнопка "Еще" в панели последних комментариев на заглавной стр.

### ISSUE THREAD

**Issue by Duche3d** [PastVu/pastvu#34]
В списке последних последних комментариев справа сделать кнопку "Еще...", которая будет открывать окно с пейджинатором отображающее все комментарии в обратном хронологическом порядке.

**Comment by paul-k-pastvu** [comment]
Не "открывать окно с пейджинатором", а перенаправлять на страницу с глобальной лентой комментариев

**Comment by paul-k-pastvu** [comment]
Думаю, что эта задача и #59 могут быть объединены в одну, "Глобальная лента комментариев (с фильтрацией и группировкой)"

**Comment by paul-k-pastvu** [comment]
Replaced by https://github.com/PastVu/pastvu/issues/268
