### ISSUE TITLE
Incorrect redirection for user profile / Некорректные перенаправления для профилей участников

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#349]
Фото https://pastvu.com/p/782445 загрузил участник https://pastvu.com/u/Dmitriy.S (имя с точкой)
Однако по клику на профиль попадаешь на https://pastvu.com/u/Dmitriy-S (имя с дефисом)

А это два разных аккаунта (у второго нет ни фото, ни комментариев).

Если точки в именах аккаунтов не разрешены, то не нужно позволять их использовать. А если разрешены -значит, нужно корректно обрабатывать в url, ни на что не заменяя.

Для текущей ситуации нужно также какое-то частное решение.

**Comment by kabalin** [comment]
Похоже Dmitriy.S (имя с точкой) деактивирован?

![nouser](https://user-images.githubusercontent.com/329780/108883371-433a4500-75fd-11eb-9934-3f3574eff737.jpeg)
Перенаправление на пользователя Dmitriy-S не совсем корректно, причина этого здесь:
https://github.com/PastVu/pastvu/blob/master/controllers/profile.js#L66

**Comment by paul-k-pastvu** [comment]
> Похоже Dmitriy.S (имя с точкой) деактивирован?

А у нас нет такого понятия как "участник деактивирован". Раз тут https://pastvu.com/p/782445  мы его видим, значит он есть.
