### ISSUE TITLE
Счётчик загрузок работает неправильно

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#355]
![image](https://user-images.githubusercontent.com/13631515/110905263-45014980-831b-11eb-844f-d328c5b87a8c.png)

https://pastvu.com/news/153?hl=comment-2260284

![90012](https://user-images.githubusercontent.com/13631515/111061118-bcb5ac80-84b2-11eb-81ad-12fc890ee1dd.png)

**Comment by kabalin** [comment]
Ну это же #342.
