### ISSUE TITLE
"There is not a single image" > "No images found"

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#373]
"Если при просмотре профиля пользователя фильтр отображает 0 изображений (или попросту у пользователя нет загруженных фото), то пишется There is not a single image (т.е. "Это - не единое изображение"). Я бы ожидал увидеть что-то типа "No images found". Можно и более развёрнуто, но это сообщение уже стандарт на сайтах)" // https://pastvu.com/news/153?hl=comment-2422073

**Comment by aeifn** [comment]
https://context.reverso.net/translation/english-russian/there+is+not+a+single
