### ISSUE TITLE
Kosmosnimki tiles site change / Поменялся сайт тайлов для Космоснимков

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#378]
Поменялся сайт тайлов для Космоснимков. В результате этот вариант карт не работает.

Сам сайт, который мы использовали -  osmcluster.kosmosnimki.ru - сейчас перенаправляет на fires.ru
А если посмотреть, где лежат тайтлы на сайте самих Космоснимков - то на tilessputnik.ru

Пример:
https://osmcluster.kosmosnimki.ru/kosmo/17/76614/39431.png - не грузится
https://tilessputnik.ru/17/76614/39431.png - грузится

**Comment by aeifn** [comment]
https://tilessputnik.ru/17/76614/39431.png - не грузится (просрочен сертификат)

**Comment by darkblaze69** [comment]
Всё также не работает дефолтный OSM Kosmosnimki. Юзабельность для новичков сразу же неочевидна, т.к. не грузится дефолтная карта.

**Comment by aeifn** [comment]
> Всё также не работает дефолтный OSM Kosmosnimki. Юзабельность для новичков сразу же неочевидна, т.к. не грузится дефолтная карта.

А известно ли, где нынче доступны Космоснимки? Вообще, причина, почему мы так за них держимся, мне совершенно не понятна.

**Comment by kabalin** [comment]
Оф. сайт отсюда грузит теперь: https://btilecart.kosmosnimki.ru/kosmo/15/19724/11027.png (префикс [a-d])

Давайте mapnik дефолтным сделаем учитывая нестабильность космоснимков?

**Comment by aeifn** [comment]
> Оф. сайт отсюда грузит теперь: https://btilecart.kosmosnimki.ru/kosmo/15/19724/11027.png (префикс [a-d]tilecart)

перестроил прокси
