### ISSUE TITLE
mongo4: Сценарии тестирования

### ISSUE THREAD

**Issue by kabalin** [PastVu/pastvu#408]
**Стандартные сценарии поведения пользователей**

- [x] Registration
- [x] confirmation
- [x] login
- [x] logout
- [x] Navigation
  - [x] view map
  - [x] change map by image types (paintings/photos)
  - [x] different zoom levels
  - [x] moves
  - [x] view gallery
  - [x] filters by year
  - [x] by region
  - [x] by status
- [x] Comments
  - [x] replies to comments
- [x] Own user profile view
  - [x] various tabs
  - [x] settings
- [x] Other user profile
  - [x] view
  - [x] photos
  - [x] comments
- [x] Other user profile as admin
  - [x] changing various user permissions, etc.
- [x] Upload photo
  - [x] move through all statuses
  - [x] delete
- [x] User upload photo
  - [x] Edit photo
  - [x] send for publication
- [x] Moderator approves photo
  - [x] Edit photo
  - [x] Deactivate photo
  - [x] Reactivate photo

**Comment by kabalin** [comment]
Добавляйте еще сценарии. На все обнаруженные проблемы, пожалуйста создавайте отдельный тикет.

**Comment by mkgrgis** [comment]
Циклический проход по API для всех изображений. Можно посмотреть нагрузочно.

**Comment by kabalin** [comment]
> Циклический проход по API для всех изображений. Можно посмотреть нагрузочно.

В данном случае важнее уникальные действия пользователя, чтобы выявить баги связанные измениями обращений к базе.

**Comment by mkgrgis** [comment]
Change map by type, change map by image type (photo/painting)

**Comment by mkgrgis** [comment]
Image lifecycle: changing attributes including type, adding and voiding coordinates.

**Comment by kabalin** [comment]
Tests for v2.0.0-pre2 (not ready for testing yet)

User settings tab:
- As authenticated user
  - [ ] Change home region
  - [ ] Change list of regions
  - [ ] Logout, login again - check regions values are the same
  - [ ] Set "Filter by default" to "List" and define one or more regions.
  - [ ] Logout, login again - check filter and region values are the same.
- As admin
  - [ ] Set moderation region for a user
  - [ ] Login as moderator, check that moderation region is matching defined earlier

**Comment by kabalin** [comment]
**Сценарии связанные с dbEval** (на реальных данных)

- [ ] converter.convertPhotosAll - запуск конвеера конвертации для большого числа фото (путь /admin/photo) - все переконвертировать не стоит, попробовать запустить для региона с небольшим количеством фото.
- [ ]  cluster.clusterPhotosAll - пересчет размера кластера (путь /admin/map)
- [ ]  region.calcRegionStats - пересчет статистики регионов (путь /admin/region) - выбрать один регион, запустить перерасчет, убедиться что данные по статистике не изменились.
- [ ] session.calcUserStats - пересчет статистики пользователя (запускается автоматически раз в сутки) - можно исказить статистику для конкретного пользователя путем прямого изменения его записи в базе и проверить после очередного запуска пересчета что данные восстановились.

**Comment by kabalin** [comment]
Для тестирования `session.calcUserStats` я изменил значения аттрибутов для двух пользователей в базе на некорректные значения: `db.users.update({login: 'nowhereman'}, { $set: {pcount: 500, pfcount: 50, pdcount: 10, ccount: 500}})`

В полночь на инстансе worker автоматически была запущена регулярная задача `calcUserStats`:
```
[2021-12-02T00:10:44.852] [INFO] queue - ESC[39mQueue 'session' job 'calcUserStats' is completed in 644.846s.
[2021-12-02T00:10:44.853] [INFO] queue - ESC[39mQueue 'session' job 'calcUserStats' reported: User statistics for 122411 users was calculated
```
После запуска регулярной задачи значения были восстановлены на те, что были до изменений:
```
> db.users.findOne({login: 'nowhereman'}, {pcount: 1, pfcount: 1, pdcount: 1, ccount: 1})
{
        "_id" : ObjectId("51ed592be3dd80d67f0001b2"),
        "ccount" : 541,
        "pcount" : 590,
        "pfcount" : 6,
        "pdcount" : 22
}
```
Будем надеяться, что проблема #342 решена.
