### ISSUE TITLE
API problem: JSON with 0x0000

### ISSUE THREAD

**Issue by mkgrgis** [PastVu/pastvu#409]
JSON from API by images
[667788](https://pastvu.com/api2?method=photo.giveForPage&params={"cid":667788}) and 
[667791](https://pastvu.com/api2?method=photo.giveForPage&params={"cid":667791}) is incorrect because includes 0x0000 in some strings. 0x0000 inside of some JSON string isn't correct symbol for most of JSON parsers including bash, C#, Scala, PostgreSQL json types etc. I think we need filtration against 0x0000 input-time or replacing 0x0000 output-time.

JSON из API некоторых изображений содержат символ 0x0000, что недопустимо для многих парсеров.

**Comment by kabalin** [comment]
`jsonlint` ошибок не находит (проверил первую ссылку).

**Comment by mkgrgis** [comment]
Не знаю методику отправки на jsonlint, вдруг там режется что-то по пути.
Вижу в PostgreSQL
![изображение](https://user-images.githubusercontent.com/41448637/140715272-f9677634-7bdc-4414-924b-ceab03602c00.png)
и в C#
![изображение](https://user-images.githubusercontent.com/41448637/140715343-15fc60e0-140f-462a-ae6e-d54582e3d07e.png)

**Comment by kabalin** [comment]
> Оба кода дают ошибку в двух средствах обработки. Подозреваю result.photo.desc.
да, это содержимое поля desc, JSON структура ошибок не имеет.

Вот здесь как c этим работать на стороне postgres:
https://stackoverflow.com/questions/31671634/handling-unicode-sequences-in-postgresql

**Comment by mkgrgis** [comment]
Спасибо. Слона починил. Что делать с C# не знаю пока. Вставлю замену в том же духе наверное.

**Comment by mkgrgis** [comment]
В конце https://stackoverflow.com/questions/54272131/javascript-json-strings-with-nul-0 пишут, что выдача с 0x0000 в принципе неверная, но ссылок на документы нет, хотя указаны тонкие проблемы в JavaScript. Открываем проблему заново?
P.S. API программы починились, там нет проблем.

**Comment by mkgrgis** [comment]
@anvaruk, спасибо, но у меня нет телеграм. Посмотрел что это такое - слишком много нового для одного человека в добавок к попыткам разворачивания. Пока тут docker осваиваю и пытаюсь осмыслить дерево NPM, подтягиваемое для PastVu. По моим репозиториям можно понять, что в связи с PastVu приходится осваивать совсем непривычные, но интересные области.
