### ISSUE TITLE
Ошибка при разлогине

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#411]
![photo_2021-11-08 23 05 45](https://user-images.githubusercontent.com/13631515/140810456-db16874c-964b-4893-b910-4841f05f65bc.jpeg)

![photo_2021-11-08 23 05 50](https://user-images.githubusercontent.com/13631515/140810471-6b3b56e0-aa69-479d-9c3f-22c4260fc381.jpeg)

**Comment by kabalin** [comment]
Это происходит, когда открыто несколько табов в браузере.
