### ISSUE TITLE
Аватарка не отображается после загузки

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#412]
![photo_2021-11-08 23 08 33](https://user-images.githubusercontent.com/13631515/140810760-1e7504e2-0f97-4196-8e3f-68b17b885470.jpeg)

При этом в файловую систему попадает, а внешне показывает 404 

Ex. https://pastvu.tk/_a/h/9/9/9908mfgv34.jpeg

**Comment by kabalin** [comment]
Локально работает как надо - может быть проблема с traffic или где там статические файлы роутятся?

**Comment by aeifn** [comment]
Странно, что же поменялось? Ведь мы тот же самый образ fileserver используем. Посмотрю

**Comment by aeifn** [comment]
Причина была в том, что nginx ссылался на несуществующую на стейдже директорию `_a`:
```
root@56179df715fc:/store/public/avatars# ln -s ../avatars/ _a
root@56179df715fc:/store/public/avatars# ls -l
total 8
lrwxrwxrwx 1 root root   11 Nov 17 03:50 _a -> ../avatars/
drwxr-xr-x 9 root root 4096 Nov  8 05:06 d
drwxr-xr-x 9 root root 4096 Nov  8 05:06 h
```

Исправление в конфиге nginx: https://github.com/PastVu/fileserver/commit/80af359dbd450a4c066a9797a13bdaa289941285
