### ISSUE TITLE
Некорректный номер версии у 2.0.0-pre1

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#413]
<img width="786" alt="image" src="https://user-images.githubusercontent.com/13631515/140811478-e08bc77c-5378-4733-965d-790042d0a6a3.png">

**Comment by kabalin** [comment]
Добавил бамп https://github.com/PastVu/pastvu/commits/mongo4 Можно и тэг поправить, но стейж не обновлять. на следующем пререлизе обновить.

**Comment by kabalin** [comment]
Добавлен релиз отдельным коммитом https://github.com/PastVu/pastvu/commit/7f82a3465f5612d592e99eb40df1e234adbbefe4, тэг исправлен.
