### ISSUE TITLE
Ошибка в консоли браузера при нажатии на точку на главной карте

### ISSUE THREAD

**Issue by aeifn** [PastVu/pastvu#414]
Safari Version 15.1 (17612.2.9.1.20)

<img width="1454" alt="image" src="https://user-images.githubusercontent.com/13631515/140812396-cf3fbb90-0e9d-4a02-8152-2ca8c8dd7779.png">

**Comment by kabalin** [comment]
@aeifn, а что нужно сделать, чтобы воспроизвести?

**Comment by aeifn** [comment]
> @aeifn, а что нужно сделать, чтобы воспроизвести?

видимо, safari, в chrome такого не вылезает :)

**Comment by kabalin** [comment]
Заодно бэкграунд в консоле надо починить (или убрать иконку)

**Comment by kabalin** [comment]
Причина та-же что и у #285, а именно двойной клик из-за бага в Leaflet https://github.com/Leaflet/Leaflet/issues/7255 В продакшене тоже есть эта ошибка.
