### ISSUE TITLE
Discussion about last rejected photos / Обсуждение отклоненных фотографий

### ISSUE THREAD

**Issue by Duche3d** [PastVu/pastvu#44]
Должна быть страница с отклоненными фотографиями, где пользователи могли бы их обсуждать и убеждать модераторов в необходимости их публикации. Фотографии могут жить на этой странице ограниченное время по прошествии которого, если они так и не будит опубликованы одним из модераторов, они окончательно удаляются. Дабы туда не попадало всякое порно - администраторы должны иметь возможность чистить этот раздел по своему усмотрению;
Приоритет этой задачи - низкий

**Comment by paul-k-pastvu** [comment]
Тут нужно как-то переформулировать задачу с учетом текущих реалий.
