### ISSUE TITLE
Empty API response

### ISSUE THREAD

**Issue by svatrous** [PastVu/pastvu#444]
Since API changed (bounds -> GeoJSON), server send empty response if zoom >= 17

Request:
photo.getByBounds
Params:
["params": "{\"z\":17,\"geometry\":{\"type\":\"Polygon\", \"coordinates\":[[[37.63517983546083, 55.87896591303331], [37.63153549961629, 55.87896591303331], [37.63153549961629, 55.874951244030285], [37.63517983546083, 55.874951244030285], [37.63517983546083, 55.87896591303331]]]},\"year\":1826,\"year2\":2000}", "method": "photo.getByBounds"]
Response:
Optional({
    result =     {
        clusters =         (
        );
        photos =         (
        );
        z = 17;
    };
    rid = mqjnf4bam8;
})

**Comment by kabalin** [comment]
Hi @svatrous, you need to supply extra param `localWork: true` for zoom 17 and above, i.e.
```
https://pastvu.com/api2?method=photo.getByBounds&params={"z":17,"localWork": true,"geometry":{"type":"Polygon", "coordinates":[[[37.63517983546083, 55.87896591303331], [37.63153549961629, 55.87896591303331], [37.63153549961629, 55.874951244030285], [37.63517983546083, 55.874951244030285], [37.63517983546083, 55.87896591303331]]]},"year":1826,"year2":2000}
```

We actually going to bring back `bounds` param functionality #443, so you might want to wait till it lands and use it if that is more convenient.
