### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by kabalin** [PastVu/pastvu#448]
While Pastvu code is open source and anyone is welcome to contribute, open source license in still missing in the project.

We have several entities subject to licensing that comes to my mind (feel free to add more):

1. The code in this repository
2. The graphic content in this repository (logo, icons, etc.)
3. Test database used in dev environment (discussed in #402)
4. Data returned in public API (discussed in #402)
5. Other repos in this organisation

**Comment by paul-k-pastvu** [comment]
Касаемо лицензии на код - тут первое слово за @klimashkin .
Всё зависит от того, хотим ли мы позволить делать на основе этого кода проекты с закрытым кодом,или нет.
Лично я за то, чтобы нет, и тогда разумный выбор - GNU General Public License v3.0  / [gpl-3.0](https://choosealicense.com/licenses/gpl-3.0/)

Если же да, то я бы хотел увидеть эти соображения (ну и для такого случая сайт https://choosealicense.com/ рекомендует [MIT License](https://choosealicense.com/licenses/mit/)).

**Comment by paul-k-pastvu** [comment]
Про лого, иконки и т.п. я ничего не знаю, пусть тоже выскажется @klimashkin.
Ну и формально нужно будет это всё утвердить у Ильи.

**Comment by paul-k-pastvu** [comment]
Pages мы пока толком не запустили, но я бы смотрел в сторону Creative Commons Attribution 4.0 / [cc-by-4.0
](https://creativecommons.org/licenses/by/4.0/deed.ru)

**Comment by kabalin** [comment]
> Касаемо лицензии на код - тут первое слово за @klimashkin . Всё зависит от того, хотим ли мы позволить делать на основе этого кода проекты с закрытым кодом,или нет. Лично я за то, чтобы нет, и тогда разумный выбор - GNU General Public License v3.0 / [gpl-3.0](https://choosealicense.com/licenses/gpl-3.0/)

Мне кажется в нашем случае более подходящий вариант [AGPL 3.0](https://www.gnu.org/licenses/agpl-3.0.en.html). Если взять код, изменить и запустить сервис на его основе, при этом не публикуя код, то GPL лицензия нарушена не будет. AGPL решает эту проблему. Из текста лицензии:

>  The GNU General Public License permits making a modified version and letting the public access it on a server without ever releasing its source code to the public.
>The GNU Affero General Public License is designed specifically to ensure that, in such cases, the modified source code becomes available to the community.

**Comment by kabalin** [comment]
> Про лого, иконки и т.п. я ничего не знаю, пусть тоже выскажется @klimashkin.

Для открытого проекта приемлема лицензия Attribution-ShareAlike 4.0 ([CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)), которая обязывает публиковать все изменения:
> If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

и ее модификация Attribution-NonCommercial-ShareAlike 4.0 - тоже самое, но c запретом коммерческого использования.

Ждем мнение Павла!

**Comment by paul-k-pastvu** [comment]
> Pages

Для Pages - я за CC-BY безусловно.

**Comment by klimashkin** [comment]
@kabalin Поддержваю AGPL и Attribution-ShareAlike 4.0!

**Comment by paul-k-pastvu** [comment]
> Поддержваю AGPL и Attribution-ShareAlike 4.0!

@kabalin предлагал CC-BY (и я поддержал), ты пишешь про CC-BY-SA.  А смысл? Это ж доки, не энциклопедия. Зачем нам нужно, чтобы сохраняли лицензию? Пусть берут, и делают что угодно...

**Comment by klimashkin** [comment]
Ок, я за

**Comment by kabalin** [comment]
> > Поддержваю AGPL и Attribution-ShareAlike 4.0!
> 
> @kabalin предлагал CC-BY (и я поддержал), ты пишешь про CC-BY-SA. А смысл? Это ж доки, не энциклопедия. Зачем нам нужно, чтобы сохраняли лицензию? Пусть берут, и делают что угодно...

CC-BY действительно выглядит как лучший вариант для проекта документации (https://github.com/PastVu/docs/issues/2)

Для этого репозитария (web приложение), будем использовать:
* Для кода - AGPL
* Для графического контента (лого, иконки и т.п.) - CC-BY-SA или (CC-BY?)

Если мы для графического контента выбираем CC-BY-SA, то ее тогда придется частично распространить и на документацию (там логотип используется).

**Comment by kabalin** [comment]
Еще вариант - графический контент в этом репозитарии в отдельную лицензию не выделять, а использовать AGPL для всего репозитария.

**Comment by paul-k-pastvu** [comment]
Модификатор -NC использовать нельзя никогда и нигде, если только вы серьезно не настроены преследовать нарушителей и судиться по каждому поводу.
В остальном, нам не нужно, чтобы иконки и лого кто-то утаскивал в несвободный проект. Поэтому пусть будет  AGPL, как для кода.
