### ISSUE TITLE
Описание требований к разворачиванию / Add description of prerequisites for debug

### ISSUE THREAD

**Issue by mkgrgis** [PastVu/pastvu#467]
Неоднократно пробовал docker, но получал ошибки по версии https://github.com/PastVu/pastvu/blob/master/docker-compose.yml.
Нужно указание на версии docker в документации и явная ссылка на образ, где можно увидеть команды для попытки повторения конфигурации в классическом виде.

Add in documentation:
Docker's rpm/deb version info for docker-compose.yml.
Link to in-docker commands for services of the project if anyone want reproduce environment like classic way.

**Comment by kabalin** [comment]
@mkgrgis c текущей должно работать. Вы ставите ее по инструкции https://docs.docker.com/get-docker/? Те что идут с дистрибутивом по умолчанию обычно не самые свежие.

**Comment by mkgrgis** [comment]
> Вы ставите ее по инструкции https://docs.docker.com/get-docker/? Те что в пакетном менеджере дистрибутива обычно не самые свежие.

Обновил до предела по инструкции. Сообщений о высокой версии [docker-compose.yml](https://github.com/PastVu/pastvu/blob/master/docker-compose.yml) больше нет.
```
containerd.io/,now 1.4.12-1 amd64 [установлен]
docker-ce-cli/,now 5:20.10.12~3-0 amd64 [установлен]
docker-ce/,now 5:20.10.12~3-0 amd64 [установлен]
```
```
:~$cd pastvu;
:~/pastvu$ docker --version
Docker version 20.10.12, build e91ed57
```
Тем не менее 
```
:~/pastvu$ docker compose up -d mongo
unknown shorthand flag: 'd' in -d
See 'docker --help'.
```
ЧЯДНТ?

**Comment by aeifn** [comment]
> Тем не менее
> 
> ```
> :~/pastvu$ docker compose up -d mongo
> unknown shorthand flag: 'd' in -d
> See 'docker --help'.
> ```
> 
> ЧЯДНТ?

Видимо, нужно еще установить compose по этой инструкции:
https://docs.docker.com/compose/cli-command/

**Comment by mkgrgis** [comment]
> Видимо, нужно еще установить compose по этой инструкции:

Спасибо, @aeifn! Верное предположение. Жаль только что всего этого нет в инструкции, иначе я бы уже полгода назад равзернул копию для отладки.

Добавочно может понадобиться сделать сокет докера публичным.

`sudo chmod 666 /var/run/docker.sock`

**Comment by kabalin** [comment]
> Добавочно может понадобиться сделать сокет докера публичным.

Делать сокет публичным не самая лучшая идея, если пытаетесь сделать доступ для текущего пользователя, его нужно добавить в группу `docker` (`sudo usermod -aG docker $USER`), это вообще-то есть в [инструкции](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user). Права на сокет должны быть 660.

**Comment by mkgrgis** [comment]
`sudo usermod -aG docker $USER`
Спасибо, @kabalin ! До этого места не дочитал. А что может быть не так с ./config/local.config.js ? Забыли команду в скрипте разворачивания конетейнера?

**Comment by kabalin** [comment]
> А что может быть не так с ./config/local.config.js ?

Прав не хватает тут https://github.com/PastVu/pastvu/blob/master/docker/dev-entrypoint.sh#L6

Скопируйте его вручную:

> On a very first run Docker entrypoint script copies config/local.config.js.docker-example into config/local.config.js.

**Comment by mkgrgis** [comment]
1.
```
:~$ cd pastvu/
:~/pastvu$ docker compose run --rm app npm install
[+] Running 2/0
 ⠿ Container pastvu-mongo-1  Created                                       0.0s
 ⠿ Container pastvu-redis-1  Created                                       0.0s
[+] Running 2/2
 ⠿ Container pastvu-redis-1  Started                                       7.7s
 ⠿ Container pastvu-mongo-1  Started                                       7.8s
cp: failed to access './config/local.config.js': Permission denied

```
2.
```:~/pastvu$ docker compose up
[+] Running 9/0
 ⠿ Container pastvu-mongo-1        Running                                 0.0s
 ⠿ Container pastvu-mailcatcher-1  Cre...                                  0.0s
 ⠿ Container pastvu-redis-1        Running                                 0.0s
 ⠿ Container pastvu-app-1          Created                                 0.0s
 ⠿ Container pastvu-downloader-1   Crea...                                 0.0s
 ⠿ Container pastvu-worker-1       Created                                 0.0s
 ⠿ Container pastvu-sitemap-1      Created                                 0.0s
 ⠿ Container pastvu-uploader-1     Create...                               0.0s
 ⠿ Container pastvu-notifier-1     Create...                               0.0s
Attaching to pastvu-app-1, pastvu-downloader-1, pastvu-mailcatcher-1, pastvu-mongo-1, pastvu-notifier-1, pastvu-redis-1, pastvu-sitemap-1, pastvu-uploader-1, pastvu-worker-1
pastvu-app-1          | cp: failed to access './config/local.config.js': Permission denied
pastvu-app-1 exited with code 1
pastvu-notifier-1     | cp: failed to access './config/local.config.js': Permission denied
pastvu-worker-1       | cp: failed to access './config/local.config.js': Permission denied
pastvu-sitemap-1      | cp: failed to access './config/local.config.js': Permission denied
pastvu-uploader-1     | cp: failed to access './config/local.config.js': Permission denied
pastvu-downloader-1   | cp: failed to access './config/local.config.js': Permission denied
pastvu-notifier-1 exited with code 1
pastvu-mailcatcher-1  | Starting MailCatcher v0.8.1
pastvu-downloader-1 exited with code 1
pastvu-worker-1 exited with code 1
pastvu-uploader-1 exited with code 1
pastvu-sitemap-1 exited with code 1
pastvu-mailcatcher-1  | ==> smtp://0.0.0.0:1025
pastvu-mailcatcher-1  | ==> http://0.0.0.0:1080
pastvu-mongo-1        | {"t":{"$date":"2022-03-14"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1647255352:827000][1:0x7f83fe15a700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 3, snapshot max: 3 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 10563"}}
```

Не помогает `chmod 777 -v './config/local.config.js';` даже если обернуть в ` while true; do ...  done;`
Прошу совета.
Команда `cat './config/local.config.js'` результативна, проблем нет.

**Comment by kabalin** [comment]
Я сейчас прошел все шаги по [инструкции](https://github.com/PastVu/pastvu/blob/master/CONTRIBUTING.md#create-development-environment) на свежем клоне репозитария. Ошибок ни на одном этапе не возникло. Попробуйте удалить директорию и начать все сначала.

**Comment by mkgrgis** [comment]
Увы, вопсроизводится в точности. Мой пользователь в группе docker если что.

**Comment by mkgrgis** [comment]
Копируемому файлу `'./config/local.config.js' ` выставляется странная принадлежность. Если исправить на принадлежность идентичную соседним файлам, то проблем нет.

**Comment by kabalin** [comment]
Что-то у вас где-то нарушено с правами. Этот каталог создается внутри volume, т.е. не может быть чтобы докер не имел на это прав.

**Comment by aeifn** [comment]
> [ERROR] app - Error: EACCES: permission denied, mkdir '/store/incoming'

Проблема воспроизводится на docker desktop под macos и заключается в следующем:
```
➜  pastvu git:(master) ✗ docker compose run --no-deps --rm app bash
node@66abeff366a3:/code$ ls -ld /store/
drwxr-xr-x 2 root root 4096 Mar 17 23:29 /store/
node@66abeff366a3:/code$ whoami
node
```

**Comment by aeifn** [comment]
> [ERROR] app - Error: EACCES: permission denied, mkdir '/store/incoming'

Исправлено коммитом https://github.com/PastVu/pastvu/commit/85f90b1c50f7b9e30acc62bbd36e99c71c7b1762

**Comment by mkgrgis** [comment]
@aeifn, не помогло. Направление поиска верное. При разворачивании подразумеваются какие-то умолчания о системе прав, которые не имеют смысла или должны быть уточнены в контейнерах.

**Comment by aeifn** [comment]
@mkgrgis попробуйте сделать свежий клон репозитория и поднять по инструкции, теперь должно работать

**Comment by kabalin** [comment]
@mkgrgis еще `docker compose pull` запустите чтобы локальный образ обновился.

**Comment by mkgrgis** [comment]
@aeifn попытка №4 накатить после полного сноса всего каталога закономерно привела к результату, который ничем не отличается от предыдущего... docker uid!=1000 до сих пор проваливается на `'./config/local.config.js'`, а docker uid==1000 проваливается на   `mkdir '/store/incoming'`.

**Помогло** `docker compose pull` от ув. @kabalin, спасибо! docker от uid!=1000 также хорошо работает. Нужно как-то доработать инструкцию, не очень понимаю что происходит с правами доступа при `docker compose pull`.

**Comment by kabalin** [comment]
> не очень понимаю что происходит с правами доступа при docker compose pull

Егор починил проблему в докер образе node.js, команда `docker compose pull` обновляет локальный образ (т.е. заменяет его на последний доступный в репозитарии). Инструкцию менять не надо, при новой установке, когда прежде образ nodejs не был локально скачан, этой проблемы не будет.

**Comment by mkgrgis** [comment]
Спасибо, Руслан! Понял что исправление Егора разворачивается через docker, а не через скачивание репозитория. Если что буду знать куда смотреть.
Приступил к изучению схемы данных в нашей MongoDB.

**Comment by kabalin** [comment]
Но я на самом деле вас дезинформировал (непреднамеренно) - забыл, что образ для приложения собирается локально и больше не хранится в репозитарии. Т.е. `docker compose pull` по идее не должен был исправить (но как то исправил), а вот `docker compose build` мог бы помочь, собрав локальный образ повторно.

**Comment by mkgrgis** [comment]
А я как раз внутри `docker compose pull` попробовал `docker compose build` для pastvu-app, где некогда проваливался  `mkdir '/store/incoming'`. Тогда в инструкцию всё-таки нужно добавить `docker compose build` со списком приложений?

**Comment by kabalin** [comment]
Михаил, там нет "внутри", `docker compose pull` загружает образы из репозитария и завершается. `docker compose build` собирает образ локально, если есть соответствующая инструкция в compose файле (в нашем случае есть), и тоже завершается. В инструкцию добавлять не нужно, при новой установке все будет работать как надо.

**Comment by mkgrgis** [comment]
> В инструкцию добавлять не нужно, при новой установке все будет работать как надо.

Увы, при разворачивании с нуля
```
$ docker compose run --rm app npm install
[+] Running 2/0
 ⠿ Container pastvu-mongo-1  Running                                      0.0s
 ⠿ Container pastvu-redis-1  Running                                      0.0s
cp: failed to access './config/local.config.js': Permission denied

```

**Comment by mkgrgis** [comment]
` failed to access './config/local.config.js'` лечится `chmod -v -R g+w .; chmod -v -R o+w .;` Однако это гнилой костыль.

**Comment by kabalin** [comment]
> Увы, при разворачивании с нуля, uid != 1000

перед разворачиванием сделайте `git pull` и запустите `docker compose build`.

**Comment by mkgrgis** [comment]
Увы, костыль работает, а `docker compose build` после `git pull` права не правит.
```
docker compose build
Sending build context to Docker daemon  1.451kB
Step 1/9 : ARG NODE_TAG=16.10.0
Step 2/9 : FROM node:${NODE_TAG}
 ---> 9c23a8242f8b
Step 3/9 : RUN apt-get update && apt-get install -y     graphicsmagick     webp && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 662b913f8f38
Step 4/9 : COPY ./imagick-policy.xml /etc/ImageMagick-6/policy.xml
 ---> Using cache
 ---> f4bea0b2ee77
Step 5/9 : WORKDIR /code
 ---> Using cache
 ---> 76451256eeac
Step 6/9 : COPY ./dev-entrypoint.sh /usr/local/bin/
 ---> Using cache
 ---> 4a66673cbdfb
Step 7/9 : RUN mkdir -p /store && chown -R node:node /store
 ---> Using cache
 ---> fa1d8ee3d4ff
Step 8/9 : USER node
 ---> Using cache
 ---> b727d35446ad
Step 9/9 : ENTRYPOINT ["dev-entrypoint.sh"]
 ---> Using cache
 ---> bd5fa4c15ccd
Successfully built bd5fa4c15ccd
Successfully tagged pastvu_node:latest

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
user@host:/opt/pastvu$ docker compose run --rm app npm install
[+] Running 2/0
 ⠿ Container pastvu-mongo-1  Running                                                                                                                     0.0s
 ⠿ Container pastvu-redis-1  Created                                                                                                                     0.0s
[+] Running 1/1
 ⠿ Container pastvu-redis-1  Started                                                                                                                     3.5s
cp: failed to access './config/local.config.js': Permission denied
```
