### ISSUE TITLE
Image upload: Only part of button "Remove" is visible with long filenames.

### ISSUE THREAD

**Issue by darkblaze69** [PastVu/pastvu#478]
Image upload: Only part of the "Remove" button is visible for long filenames w/o spaces.

![upload](https://user-images.githubusercontent.com/6976920/172911752-0b217817-cc91-45e1-b15d-a5dfbe6655c9.png)

**Comment by kabalin** [comment]
We should probably shorten the filename or make text wrap to the next line without affecting button position.
