### ISSUE TITLE
Disallowing punctuation chars as last symbol in the username

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#489]
RU: Хорошо бы не допускать при регистрации использование знаков в качестве последнего символа

**Comment by paul-k-pastvu** [comment]
Нужно будет решить, что делать с аккаунтами, в которых это уже так. Как минимум, найти их все запросом.

**Comment by kabalin** [comment]
Их в принципе можно исправить через апдейт, убрав некорректный символ. Но нужно как-то уведомить пользователей после изменения. Надеюсь их не много.

**Comment by kabalin** [comment]
> Надеюсь их не много.

303 пользователя на данный момент, достаточно много. В таком случае предлагаю решение из двух частей:
1. Запретить использование знаков в качестве последнего символа.
2. Исправить отображение профиля по ссылке для существующих логинов заканчивающихся на символ.

**Comment by GKosheev** [comment]
@kabalin привет, планирую сделать PR, есть пара вопросов касаемо задания: 

1. Символы, на которые нельзя чтобы заканчивался логин при регистрации это только "." и "-"?
2. Существуют ли пользователи, у которых несколько символов на конце логина? К примеру "login2.-" или "login1--"
3. Исправить отображения профиля по ссылке через изменение ```getUserByLogin()```? 
Планирую в этой строке: 
```javascript
    return { usObjOnline, user };
```
Отфильтровать user.login, убрав символы (если имеются) и вернуть изменённого ```user```

**Comment by kabalin** [comment]
Привет @GKosheev, спасибо за интерес к проекту! Я плохо донес мысль в моем последнем комментарии :) Я думаю, учитывая что пользователей таких довольно много, не изменять логины существующих вообще. Т.е. задача такова:
1. При новых регистрациях логин должен заканчиваться на букву (проверять и выдавать ошибку).
2. Починить отображение профиля с символами в конце по ссылке (т.е. чтобы ссылка как эта https://pastvu.com/u/dmitrieva.olga. работала корректно).

Насчет переименований логинов последнее слово за @paul-k-pastvu, но я бы оставил их как есть (слишком много их уже и нет механизма централизованного уведомления).

**Comment by GKosheev** [comment]
Окей, первый пункт понял. 

>Исправить отображение ссылки профиля с символами в конце при их отображении в тексте (т.е. чтобы ссылка https://pastvu.com/u/dmitrieva.olga. содержала точку и работала корректно).

Второй пункт не особо понял. Это если в комментариях кто то оставляет ссылку на свой профиль с точкой на конце (если такова имеется в логине) и она должна отображаться как ссылка? Просто у меня вроде нормально работает ссылка ```https://pastvu.com/u/dmitrieva.olga.```

**Comment by kabalin** [comment]
> Второй пункт не особо понял. Это если в комментариях кто то оставляет ссылку на свой профиль с точкой на конце (если такова имеется в логине) и она должна отображаться как ссылка? Просто у меня вроде нормально работает ссылка https://pastvu.com/u/dmitrieva.olga.

Да, если ссылка на профиль публикуется в комментарии и содержит точку, то она отображается без точки. Но сейчас думаю это не стоит исправлять. Эти ссылки уже сохранены в комментариях без точек, т.е. нет возможности исправить существующие ссылки, которые отображаются неверно. Как предложил @paul-k-pastvu, лучше будет впоследствии добавить функционал для переименования (#308) по возможности с уведомлением, и переименовать существующие профили содержащие знаки в конце (можно будет сценарием). Короче говоря, второй пункт пока снимаем.
