### ISSUE TITLE
Ошибка при показе в галереях (регион без дочерних)

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#498]
Странная ошибка: https://pastvu.com/ps?f=r!1013_rs!0_s!all
Я выбираю показ без изображений, привязанных к дочерним регионам:

![image](https://user-images.githubusercontent.com/60163100/191765144-b671278e-65a0-4b4b-858e-8b549655d9d3.png)

Однако из 4х фото, которые я вижу, 3 **привязаны** к дочернему региону: 

![image](https://user-images.githubusercontent.com/60163100/191765592-b1d93a28-50c8-41ca-bae0-40ac5734f36c.png)

**Comment by paul-k-pastvu** [comment]
Пока писал, дошло: я сам ошибся в привязке дочернего региона, он должен был быть на уровень выше. исправил.

**Comment by mkgrgis** [comment]
@paul-k-pastvu с опустивешим https://pastvu.com/ps?f=r!6458 тот же бардак?

**Comment by kabalin** [comment]
Не понял, так есть баг или нет (если нет, то тикет нужно закрыть).

**Comment by paul-k-pastvu** [comment]
> @paul-k-pastvu с опустивешим https://pastvu.com/ps?f=r!6458 тот же бардак?

Нет, там проще. Родительский регион правили, и он "украл" все фото из дочерних. Передернул геометрию, и всё вернулось.
