### ISSUE TITLE
Mixing Russian and English interface messages

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#514]
Some different cases, for Russian interface, but some messages (occasionally) is shown in English:

1) https://pastvu.com/news/148?hl=comment-2699561

2) Today, Subscriptions (Yandex/Chromium, PastVu App v2.0.8):

![image](https://user-images.githubusercontent.com/60163100/201086306-79c29ce6-b366-445a-9e35-49057036e125.png)

**Comment by kabalin** [comment]
Похоже что только содержимое табов "Подписки" и "Настройки" показываются на Английском, с остальными страницами такой проблемы нет. Куки `past.lang` при этом не стирается, т.е. причин загружать английский интерфейс для этих страниц нет.

**Comment by kabalin** [comment]
https://pastvu.com/news/141?hl=comment-2725035

@aeifn может быть что кука игнорируется прокси и запрос приходит на английский фронт? Еще вариант, может ли CDN как то влиять на это?

**Comment by anvaruk** [comment]
может на стороне cloudflare что-то подправить можно

**Comment by kabalin** [comment]
Вероятно проблема была связана с кэшированием на стороне CDN, т.е. подставлялся скрипт из кэша без учета языка. Аналогичная проблема была описана на форуме https://community.cloudflare.com/t/any-chance-to-make-cache-key-feature-available-for-pro-plans/332760 Сейчас кэширование для js отключено, скорее всего эта проблема исчезнет.
