### ISSUE TITLE
Button to copy coordinates from an existing photo / Кнопка для копирования координат с существующего фото

### ISSUE THREAD

**Issue by yuriy-zhilovets2** [PastVu/pastvu#517]
Нередко куда проще взять готовые координаты, чем долго искать их на карте

**Comment by kabalin** [comment]
Эта задача уже есть https://github.com/PastVu/pastvu/issues/118

**Comment by kabalin** [comment]
Хотя эту задачу можно отделить от #118 (см https://github.com/PastVu/pastvu/issues/118#issuecomment-1201637552), оставлю тикет открытым.

**Comment by kabalin** [comment]
Подниму приоритет, так как функция востребована (см. https://pastvu.com/news/141?hl=comment-2729154 https://pastvu.com/news/141?hl=comment-2726141). В данный момент пользователи получают функционал используя расширение для браузера https://github.com/vgiv/easypastvu, написанным уважаемым @vgiv до перевода кода проекта в открытый доступ.

**Comment by kabalin** [comment]
А что если координаты вывести (только при просмотре) таким образом?
![image](https://user-images.githubusercontent.com/329780/213035821-a42d8147-cfcb-423e-81f6-2b459e9fc41b.png)

**Comment by paul-k-pastvu** [comment]
Да, оба варианта вполне приемлемы. 
Наверное, раз координаты в режиме редактирования у нас сейчас на карте, лучше их там и оставить - просто отображать этот элемент всегда, но в разных режимах.

![image](https://user-images.githubusercontent.com/60163100/213074597-aa57ceee-fb46-4149-84eb-ced358283338.png)

С другой стороны, поле с координатами на карте воспринимается скорее как поле для _позиционирования_ центра карты (о желательности чего тоже писали). В частном случае, когда мы кликаем по маркеру фото, эти координаты будут совпадать с координатами фото, - но не обязаны.

**Comment by yuriy-zhilovets2** [comment]
Как по мне, _видеть_ координаты все время не нужно, человеку они не несут особой информации, а лишь захламляют интерфейс. Достаточно кнопки "скопировать". Если нужно еще копировать текущие координаты карты, нужна вторая кнопка, и тогда их лучше разнести по разным углам, чтобы не путались.

**Comment by yuriy-zhilovets2** [comment]
Есть еще вариант сделать копирование координат с превью, например с тех, что рисуются внизу карты. Для переноса координат "по образцу" этого будет достаточно. Вопрос только, где там можно разместить эту кнопку.

**Comment by yuriy-zhilovets2** [comment]
Вообще говоря, с других фотографий иногда требуется переносить и координаты, и авторов, и источники. Может быть, сделать, чтобы в режиме редактирования работало контекстное меню, которое сразу перенесет нужную информацию в редактирующуюся фотографию?

**Comment by kabalin** [comment]
> Таким образом напрашивается комплексное улучшение:
> 
> 1. перенести работу с координатами _точки_ текущего фото в область описания, сделав их видимыми во всех режимах и снабдив двумя кнопками:
>    
>    * копировать координаты в буфер (доступна всегда, если есть данные)
>    * очистка поля - "обнулить координаты" (доступна в режиме редактирования)
> 2. поле с координатами на карте
>    
>    * сделать доступным для ввода/редактирования координат во всех режимах
>    * снабдить кнопкой "позиционировать", нажатие которой установит центр карты в заданную точку

Да вот у меня есть сомнения. Не хотелось бы существующему полю ввода координат под картой менять функцию, будут трудности у тех кто привык что там расположены координаты снимка. 

Ввод координат в области описания тоже имеет минусы, поле отдалено от карты, т.е. вводишь там, а результат получаешь в другой логической части интерфеса (да еще и карта частично скрывается когда скроллишь к полям редактирования). Для копирования текущих координат может это и нормально, а для ввода как-то усложняет процесс. Наверное все же ввод координат нужно оставить в контейнере с картой.

**Comment by yuriy-zhilovets2** [comment]
Теоретически еще их можно передать кому-то, допустим, в мессенджере или ввести во внешнюю карту. То есть, могут потребоваться и без переноса на снимок.

**Comment by paul-k-pastvu** [comment]
Хорошо, тогда ничего радикально не меняем. Я **за** предложение Руслана - вывести координаты при просмотре и добавить к ним кнопку для облегчения копирования. Иконку я бы сделал типа [такой](https://www.onlinewebfonts.com/icon/149461), но это не принципиально.

**Comment by paul-k-pastvu** [comment]
Все остальные задачи нужно обсуждать в отдельных тикетах.

**Comment by kabalin** [comment]
> Хорошо, тогда ничего радикально не меняем. Я **за** предложение Руслана - вывести координаты при просмотре и добавить к ним кнопку для облегчения копирования. Иконку я бы сделал типа [такой](https://www.onlinewebfonts.com/icon/149461), но это не принципиально.

В итоге все связанное с координатами оставил в пределах карты (см #563 ).
