### ISSUE TITLE
Arrows to ease a choise for direction / Стрелки для облегчения выбора направления

### ISSUE THREAD

**Issue by yuriy-zhilovets2** [PastVu/pastvu#519]
![arrows](https://user-images.githubusercontent.com/26519565/201464762-ba1733aa-019a-4270-8143-f1390d66e2fb.png)

Кроме того, выбор направления более удобен рядом с полем ввода координат

**Comment by mkgrgis** [comment]
Давно готов макет точного определения направления на основе угловой меры, см. [обсуждение](https://github.com/PastVu/pastvu/issues/200) и [реализацию](https://mkgrgis.github.io/pastvu_direction/).

**Comment by kabalin** [comment]
Отличная идея со стрелками. Если пришлете PR - добавим. Переносить поле на карту не стоит, это более трудоемко и поле скорее всего уйдет как будет сделано #200.

**Comment by yuriy-zhilovets2** [comment]
А где находится английский перевод интерфейса? В дереве гита его не нашел.

**Comment by aeifn** [comment]
> А где находится английский перевод интерфейса? В дереве гита его не нашел.

А вот он находится в ветке `en`.

**Comment by yuriy-zhilovets2** [comment]
Я послал pull request, правда не уверен, что сделал это правильно.

**Comment by kabalin** [comment]
> Я послал pull request, правда не уверен, что сделал это правильно.

Скорее всего нет. Вот здесь инструкция https://docs.github.com/en/get-started/quickstart/contributing-to-projects. Если кратко - нужно создать клон у себя в репозитарии (fork), затем создать ветку с внесенными изменениями, после чего создать pull request к master ветке в этом репозитарии.
