### ISSUE TITLE
Group editing of photo data / Групповое редактирование данных фото

### ISSUE THREAD

**Issue by yuriy-zhilovets2** [PastVu/pastvu#528]
групповое внесение/изменение данных сразу для нескол’ких добавляемых фотографий, когда скажем для пары десятков кадров необходимо поставить одинаковое описание/автора/источник;

https://pastvu.com/p/1291850?hl=comment-2733603

**Comment by kabalin** [comment]
Closing as duplicate of https://github.com/PastVu/pastvu/issues/133
