### ISSUE TITLE
Sliders under map is "stick together" / "Слипание" ползунков слайдера годов под картой

### ISSUE THREAD

**Issue by paul-k-pastvu** [PastVu/pastvu#532]
EN: When you shift the "sliders of years" under map to an interval of any one year, i.e. close to each other, then you can move them apart later only starting with what you moved last, otherwise they "stick together".

RU: Когда сдвигаешь "ползунки лет" под картой до интервала в любой один год, т.е. вплотную друг к другу, то раздвинуть их можно потом только начиная с того, что придвинул последним, иначе они "слипаются".

Report: https://pastvu.com/news/141?hl=comment-2733885

**Comment by kabalin** [comment]
Так же в этом случае перестает работать перемещение по клику на области слева от обоих слайдеров если последний слайдер был правый (и наоборот). 

![image](https://user-images.githubusercontent.com/329780/206464761-cac0154e-b4bf-44e9-a368-64b4209a3135.png)
