### ISSUE TITLE
Arrows to ease a choice of direction not shown on MacOS / Стрелки для облегчения выбора направления не отображаются на MacOS

### ISSUE THREAD

**Issue by kabalin** [PastVu/pastvu#540]
На некоторых платформах/браузерах стрелки добавленные в #519 не отображаются корректно (фото из комментария https://pastvu.com/news/141?hl=comment-2746400):

<img width="300" src="https://user-images.githubusercontent.com/329780/209236491-b369b388-b2de-49b4-a884-19ea56fe7bf2.png" />

Подтвержденная проблема есть на macOS 13.1 с Chrome 108.

Для корректного отображения предлагается использовать псевдоэлементы CSS и векторное изображение стрелок (svg).

**Comment by aeifn** [comment]
На маке стрелки в самом выпадающем списке все еще отображаются вопросами:

<img width="1082" alt="Screenshot 2023-01-02 at 07 08 20" src="https://user-images.githubusercontent.com/13631515/210203186-b2b8bfe5-2ff3-422a-bb2a-707d03f9136d.png">

А после выбора направления уже правильно:
<img width="1169" alt="Screenshot 2023-01-02 at 09 18 48" src="https://user-images.githubusercontent.com/13631515/210203313-7310e433-fc86-4b2d-8673-c1cfe6c3a038.png">

**Comment by kabalin** [comment]
Похоже что непосредственно для низпадающего списка стандартного элемента select на MacOS стайлинг пока не достижим. FontAwesome имеет ту же проблему на Mac: https://github.com/FortAwesome/Font-Awesome/issues/996#issuecomment-163194336 которая пока не решена. Предлагаю пока оставить как есть, тем более что после выбора стрелка отображается корректно. Возможно замена элемента select на кастомный (типа https://select2.org/dropdown) может решить проблему.

**Comment by yuriy-zhilovets2** [comment]
Не советую связываться с select2. Это все равно что изгонять бесов силою князя бесовского.

**Comment by yuriy-zhilovets2** [comment]
Тот же FF 120 / Linux 6.5 - проблем нет

**Comment by kabalin** [comment]
Mac issue is fully addressed at #638
