### ISSUE TITLE
Choice of regions does not work with cyryllic letters / Выбор региона не работает с кириллическими буквами

### ISSUE THREAD

**Issue by yuriy-zhilovets2** [PastVu/pastvu#543]
![Снимок экрана_2022-12-26_15-41-13](https://user-images.githubusercontent.com/26519565/209550738-afba88e4-50dd-4278-bf64-9611870ace98.png)
![Снимок экрана_2022-12-26_15-41-29](https://user-images.githubusercontent.com/26519565/209550741-e8d1593b-8421-4c2c-bb9e-0493fc5814e6.png)

**Comment by paul-k-pastvu** [comment]
Это следствие всё той же ошибки #514

**Comment by kabalin** [comment]
Проблема решена в #551
