### ISSUE TITLE
More flexible coordinates parsing / Более гибкий разбор координат в поле ввода

### ISSUE THREAD

**Issue by yuriy-zhilovets2** [PastVu/pastvu#554]
Сейчас поле ввода координат принимает только ввод по шаблону типа 45.99, 33.99, то есть градусы и их доли, разделенные запятой.
Но в других источниках координаты могут храниться и в других форматах
- быть разделены пробелом или другим символом
- градусы, минуты, секунды, с возможным указанием вида широты и долготы
- градусы, минуты и десятичные доли минут.

Примеры:
Википедия: 45°11′45″ с. ш. 33°22′38″ в. д.
shukach.com: N 47° 4.077' E 32° 11.673'

Разбор и конвертация таких координат не представляет особого труда, но облегчил бы жизнь пользователей.

**Comment by mkgrgis** [comment]
Секунды и минуты могут заменять апострофом и американскими кавычками, может быть два апострофа как секунды. Названия сторон света разные в разных локалях, на PasVu попадались fr, de, uk, it источники с кооринатами.
Разбор сидит где-то тут https://github.com/PastVu/pastvu/blob/963294db278410c3da3a87515c3bb2bbca42d0e6/public/js/module/map/map.js#L78

**Comment by kabalin** [comment]
Regex для поля координат https://gist.github.com/pjobson/8f44ea79d1852900457bc257a4c9fcd5

**Comment by yuriy-zhilovets2** [comment]
https://www.npmjs.com/package/geo-coordinates-parser
Предлагаю не изобретать велосипед,  а воспользоваться готовой библиотекой , которая включает в себя не только упомянутые выше Русланом регулярные выражения, но и еще кучу вариантов, до которых и додуматься-то невозможно.
Если мейнтейнеры дадут добро на использование дополнительной библиотеки, я попробую прикрутить.

**Comment by kabalin** [comment]
Отлично, добавляйте конечно.

**Comment by mkgrgis** [comment]
> https://www.npmjs.com/package/geo-coordinates-parser

Там отличный [базовый набор](https://github.com/ianengelbrecht/geo-coordinates-parser/blob/master/formatsOnly.json), но библиотека сугубо не международная. Не увидел `с.ш.` `сш` `в.д` `вд` не говоря об `oc.lon.` `or.lon.` или `Ost` `West`.

**Comment by mkgrgis** [comment]
Расширил шаблоны сторон света и угловых мер https://github.com/mkgrgis/geo-coordinates-parser.

**Comment by yuriy-zhilovets2** [comment]
Я бы все-таки оставил библиотеку, как есть, но перед проверкой заменял бы выражения типа с.ш. на N
Список выражений держал бы в файле локализации. Тогда можно было бы пользоваться на всех поддерживаемых языках.

**Comment by kabalin** [comment]
> но перед проверкой заменял бы выражения типа с.ш. на N
Да можно пока и не заменять.

**Comment by mkgrgis** [comment]
@yuriy-zhilovets2 , спасибо! Неплохая реализация. Попозже поднакидаю шаблонов сокращений сторон света и др., если примут https://github.com/PastVu/pastvu/pull/558

**Comment by mkgrgis** [comment]
Так и не увидел есть ли безразличие к регистру слов. Странно смотрятся верхние регистры ключевых слогов из оригинального кода и  `с. ш.` строго в нижнем регистре. Проверялось ли это?

**Comment by mkgrgis** [comment]
> да, там флаг `i`

Спасибо, почему-то упустил этот момент при осмотре.
