### ISSUE TITLE
Отображение текущего региона 

### ISSUE THREAD

**Issue by Duche3d** [PastVu/pastvu#61]
Название текущего региона отображается в спецмальном окошке на главной странице.

**Comment by paul-k-pastvu** [comment]
О чем тут речь? "Текущего" - это какого? И зачем эта задача? Это баг или желаемая фича?

**Comment by paul-k-pastvu** [comment]
@klimashkin - ты помнишь, что это было? Можно это закрыть?

**Comment by klimashkin** [comment]
Возможно что-то про отображение названия домашнего региона. Я думаю модно закрыть
