### ISSUE TITLE
Switch to use Retromap tiles for Aerophoto WWII / Перейти на использование тейлов Ретромап для Аэрофото ВОВ

### ISSUE THREAD

**Issue by kabalin** [PastVu/pastvu#617]
Слой Warfly перестал работать более года назад (`https://17200.selcdn.ru/AerialWWII/...` более недоступен, ошибка 410). В этой связи предлагается задействовать плитки [Немецкой аэрофотосъемки СССР](http://retromap.ru/061942) с Ретромап взамен Warfly (по договоренности с администрацией Ретромап).

Начало [обсуждения в комментариях](https://pastvu.com/news/154?hl=comment-2923130).

**Comment by kabalin** [comment]
Шаблон слоя http://www.hutun.ru/tiles/4/061942/Z{z}/{y}/{x}.jpg добавлен в #616 Так как доступа к плиткам по `https` нет, будет ошибка `mixed content`, потребуется после отладки сделать прокси с ssl терминированием.

**Comment by kabalin** [comment]
Локально (http://pastvu.local:3000) работает:
![image](https://github.com/PastVu/pastvu/assets/329780/69b92fd3-c1c3-45c0-97c7-7538b320d781)

**Comment by hutun** [comment]
ОК, предложите, что нужно сделать на retromap, чтобы слой стал доступен

**Comment by aeifn** [comment]
> ОК, предложите, что нужно сделать на retromap, чтобы слой стал доступен

Мы уже сделали https-прокси,теперь должно работать после релиза. Релиз запланирован на сегодняшний вечер.

**Comment by hutun** [comment]
Егор,

 

Правильно ли я понимаю, что вы сделали доступ к тайлам на hutun через свой прокси сервер для того, чтоб обращения по http не блокировались?

Нельзя ли узнать немного деталей – нам это тоже нужно

 

С уважением, Сергей Тарасов

**Comment by aeifn** [comment]
> Егор, Правильно ли я понимаю, что вы сделали доступ к тайлам на hutun через свой прокси сервер для того, чтоб обращения по http не блокировались? Нельзя ли узнать немного деталей – нам это тоже нужно

Да, всё так.

Я использовал кэширующий прокси [Varnish](https://varnish-cache.org), вот его конфигурация:

```vcl
vcl 4.1;

backend default {
  .host = "www.hutun.ru";
  .port = "80";
}

sub vcl_recv {
  if (req.http.referer !~ "pastvu.com") {
    return(synth(403, "Forbidden."));
  }
}
```

**Comment by hutun** [comment]
Егор, мы постепенно будем переводить архивы и сайт на https. Немецкая аэрофотосъемка сейчас идет с сегодняшнего дня  не с www.hutun.ru. а с hutun.ru.
Полагаю, у вас нужно скорректировать host - тайлы на pastvu перестали отображаться
Я сообщу, когда аэрофотосъемка будет переведена на https

**Comment by kabalin** [comment]
@hutun: Егор поменял хост, и перестало работать, ошибка 404.

**Comment by hutun** [comment]
Сейчас тайлы снимка вот такие (без www)
http://hutun.ru/tiles/4/061942/Z15/10242/19804.jpg
И к ним открыт доступ с pastvu по http и https

**Comment by kabalin** [comment]
> Сейчас тайлы снимка вот такие (без www) http://hutun.ru/tiles/4/061942/Z15/10242/19804.jpg И к ним открыт доступ с pastvu по http и https

У нас исправлено в настройках прокси. А referer домен как прописан у вас? Запрос к вам должен приходить c https://hutun.pastvu.com

**Comment by hutun** [comment]
Сейчас тайлы снимка вот такие (без www)
http://hutun.ru/tiles/4/061942/Z15/10242/19804.jpg
И к ним открыт доступ с pastvu по http и https

> > Сейчас тайлы снимка вот такие (без www) http://hutun.ru/tiles/4/061942/Z15/10242/19804.jpg И к ним открыт доступ с pastvu по http и https
> 
> У нас исправлено в настройках прокси. А referer домен как прописан у вас? Запрос к вам должен приходить c `https://hutun.pastvu.com` (если не ошибаюсь, @aeifn может сказать точнее)
Для немецких снимков вот такое в .htaccess - сделано специально для вас. Если что-то нужно, можем исправить.
Перед этим просто www убрали в адресе обращения к тайлам этого снимка - и у вас перестало отображаться  

RewriteEngine On
RewriteBase /
RewriteCond %{HTTP_REFERER} !^(http|https)://(.+\.)?(retromap|hutun|pastvu)(.*)/ [NC]
RewriteRule .*\.(jpe?g|gif|bmp|png)$ -

**Comment by hutun** [comment]
> @hutun: Егор поменял хост, и перестало работать, ошибка 404.

Перевели тайлы аэрофотосъемки на https - теперь так:
https://hutun.ru/tiles/4/061942/Z15/10244/19804.jpg

**Comment by kabalin** [comment]
> > @hutun: Егор поменял хост, и перестало работать, ошибка 404.
> 
> Перевели тайлы аэрофотосъемки на https - теперь так: https://hutun.ru/tiles/4/061942/Z15/10244/19804.jpg

ОК, попробуем использовать напрямую без прокси.

**Comment by kabalin** [comment]
@hutun изменения внесены, но по прежнему ошибка 404. Попробуйте отладить со своей стороны, прокси больше не используется.

**Comment by hutun** [comment]
> @hutun изменения внесены, но по прежнему ошибка 404. Попробуйте отладить со своей стороны, прокси больше не используется.

А у меня всё работает с указанными тайлами  при доступе с pastvu

**Comment by kabalin** [comment]
> А у меня всё работает с указанными тайлами при доступе с pastvu

Отлично! У меня тоже сейчас работает. Спасибо!

Скажите, может быть у вас есть еще какой-то набор карт с большим зумом и хорошим покрытием, который можно было бы использовать по аналогии с аэрофотосъемкой с практической пользой? Можно было бы немного реорганизовать источники и скажем назвать последнюю секцию Retromap вместо Others.

**Comment by kabalin** [comment]
Да это понятно что много, я просто думал что может быть есть какая-то универсальная которая может быть полезна всем, по отдельности города добавлять смысла нет.

**Comment by hutun** [comment]
> Да это понятно что много, я просто думал что может быть есть какая-то универсальная которая может быть полезна всем, по отдельности города добавлять смысла нет.

Нее, универсальной и подробной нет. В этом отношении и аэрофотосъемка вполне обычный материал - ничем не лучше кучи шпионских снимков 1964-1970х годов. Разница лишь в том, что аэрофотосъемку с разными местами и датами загрузили в один директорий.

**Comment by aeifn** [comment]
> аэрофотосъемку с разными местами и датами загрузили в один директорий.

Используя, опять же, кэширующий прокси, можно некоторый класс непересекающихся локальных карт объединить в глобальную карту.

**Comment by hutun** [comment]
> > аэрофотосъемку с разными местами и датами загрузили в один директорий.
> 
> Используя, опять же, кэширующий прокси, можно некоторый класс непересекающихся локальных карт объединить в глобальную карту.

Да мы можем это сделать и без прокси - только адресация становится немного запутанной. Оставляю вопрос выбора карт на усмотрение pastvu. У нас есть статистика обращений - самые популярные карты собраны здесь https://retromap.ru/Популярные_карты

**Comment by mkgrgis** [comment]
Вот здесь обсуждалось более тонкое решение по интеграции https://github.com/PastVu/pastvu/issues/458

**Comment by mkgrgis** [comment]
Дальше всего обсуждение продвинулось на https://github.com/PastVu/pastvu/issues/197
