### ISSUE TITLE
Identical user logins / идентичные логины

### ISSUE THREAD

**Issue by kabalin** [PastVu/pastvu#651]
There are some users in the system who have same login name written in different case, looks like they were treated differently at some point. At this point it is not possible to access profile page of one of them, as browser sends lowercased URL in request.

Example: https://pastvu.com/u/Misha
Discussion: https://pastvu.com/news/155?hl=comment-2998191

**Comment by mkgrgis** [comment]
Maybe this is not browser. In my JavaScript web applications there is mixedcase translation of parameters from URL like `...?p1=b1&p2=v2...`. Also mixedcase naming (and values) is normal for MongoDB (and PostgreSQL). I think the problem is in middleware code.

**Comment by kabalin** [comment]
> Maybe this is not browser. In my JavaScript web applications there is mixedcase translation of parameters from URL like `...?p1=b1&p2=v2...`. Also mixedcase naming (and values) is normal for MongoDB (and PostgreSQL). I think the problem is in middleware code.

Just take a look what browser sends in Request URI when you change case in the username URL.

**Comment by kabalin** [comment]
> Maybe this is not browser. In my JavaScript web applications there is mixedcase translation of parameters from URL like `...?p1=b1&p2=v2...`. Also mixedcase naming (and values) is normal for MongoDB (and PostgreSQL). I think the problem is in middleware code.

Yes, you are right. Host is case insensitive, path and params are sensitive, it is browser cache that made me feel it treats path as case-insensitive.
