### ISSUE TITLE
Export a Docker container with DB and files 

### ISSUE THREAD

**Issue by reds2006** [PastVu/pastvu#667]
How to export a Docker  with the database and files for transfer to another computer?

Hello,

I have a Docker  that includes several services (app, worker, notifier, uploader, downloader, sitemap) using MongoDB and Redis as databases, as well as volumes for storing files. I would like to know how I can export this project entirely, including the database and files, for transfer to another computer.

I would appreciate instructions or advice on this matter. Thank you!

**Comment by kabalin** [comment]
Hello, this is outside the scope of the project. You may find some relevant info on Docker forums, e.g. https://forums.docker.com/t/how-to-transfer-docker-data-to-new-computer/127469
