### ISSUE TITLE
Incorrect country name

### ISSUE THREAD

**Issue by krozhdestvenski** [PastVu/pastvu#682]
Change Belarus name to common international variant.
On global map we can see correct name:
![image](https://github.com/PastVu/pastvu/assets/36443562/da09f903-fb6d-452e-bb68-1a5790fbe39e)
But country tag name is different:
<img width="818" alt="image" src="https://github.com/PastVu/pastvu/assets/36443562/345ac167-61f5-4159-a291-50221d072bfc">
Please, change country name to "Беларусь".

**Comment by aeifn** [comment]
Country names are not set in the source code, this is part of the content management.

Please consider discussing the proposed change with the non-technical community of the site.

**Comment by paul-k-pastvu** [comment]
Done. Topic of this question is for comments in https://pastvu.com/news/104
