### ISSUE TITLE
Unsupported browsers / Неподдерживаемые браузеры

### ISSUE THREAD

**Issue by anvaruk** [PastVu/pastvu#94]
показывать какое нибудь сообщение, чтобы пользователь понял в чем проблема

**Comment by paul-k-pastvu** [comment]
+держать на сайте страничку с явным указанием на минимальные требования к браузерам.
+ на этой же страничке - сообщение "В Вашем браузере сайт (не) должен работать корректно."

**Comment by kabalin** [comment]
Мне кажется это уже реализовано:

https://pastvu.com/badbrowser

https://github.com/PastVu/pastvu/blob/master/config/browsers.config.js#L5-L13

**Comment by kabalin** [comment]
Закрываю как реализованную задачу. Создал задачу перехода к использованию `browserlist` в перспективе: #501
