### ISSUE TITLE
Subscriptions bug / баг с подпиской

### ISSUE THREAD

**Issue by anvaruk** [PastVu/pastvu#99]
https://pastvu.com/news/115?hl=comment-1178636

Не сработала автоподписка при первом комментировании

Такое бывает, если комментируемое фото открыто кликом по точке на карте со станицы, на которую подписки нет /news/123?hl=comment-764978. Также случается, если впервые комменитруемое фото открыто из ленты пользователя выше карты, или ленты Ближайшие фотографии ниже карты, или из галереи. У меня такие случаи происходят постоянно, уже перестал про них писать

**Comment by kabalin** [comment]
Проблема все еще на месте

**Comment by kabalin** [comment]
При переходе на фото с другого на котором была у пользователя подписка, статус подписки сохраняется:
![image](https://user-images.githubusercontent.com/329780/186475135-3ce5c075-ff1b-4864-bc11-984faef3144e.png)
Соответственно новой подписки не происходит. 

Должен быть чекбокс на всех фото где пользователь оставляет первый комментарии и прежде не был подписан:
![image](https://user-images.githubusercontent.com/329780/186474783-58df7dd2-8977-43b4-b2f2-3fcde930f070.png)
